### ISSUE TITLE
GetUser

### ISSUE THREAD

**Issue by santhoshthangaraj** [auth0/express-openid-connect#10]
Thank you for the great package.

How to use the getuser in the auth and refresh token . Please guide on this. 

We tried this, but not working
app.use(auth({  getUser: (tokenSet) => {
    console.log(tokenSet);
  },
  authorizationParams: { scope: "openid profile full", response_type: "code" }
  
}));

**Comment by joshcanhelp** [comment]
@santhoshthangaraj - Glad you like it! 

I'm not sure what you mean about the refresh token but you can adjust the user profile and do any additional user processing you want with the `getUser` config you mentioned. Here is a quick sample to add a custom property to the profile on login:

```js
app.use(auth({
  getUser: (tokenSet) => {
    tokenClaims = tokenSet.claims || {};
    return Object.assign(tokenClaims, { lastLogin: Date() });
  }
}));
```
