### ISSUE TITLE
Destroy session before logout

### ISSUE THREAD

**Issue by BartoGabriel** [auth0/express-openid-connect#101]
In the example of using [session handling](https://github.com/auth0/express-openid-connect/blob/master/EXAMPLES.md#4-custom-user-session-handling) I see that logout is redirecting to the identity server logout url.
But nowhere do I see where the cookies are cleared from the session.
The destroy function should be called:  https://github.com/expressjs/session#sessiondestroycallback

**Comment by adamjmcgrath** [comment]
Hi @BartoGabriel - thanks for raising this. 

We don't use `express-session` - the session object is cleared here https://github.com/auth0/express-openid-connect/blob/master/lib/context.js#L126 and the cookies are cleared here https://github.com/auth0/express-openid-connect/blob/master/lib/appSession.js#L54

Do you have a reproducible case where the session cookies are not being cleared when you logout?

**Comment by BartoGabriel** [comment]
Hello @adamjmcgrath , sorry, I think I am not expressing myself well.
It is not an `express-openid-connect` bug. But, I think the examples need to be better explained:

In this example line: https://github.com/auth0/express-openid-connect/blame/master/EXAMPLES.md#L109

The session is set to false. Since the session data stores them in the `express-session` session.

The `express-session` session is setter:
https://github.com/auth0/express-openid-connect/blame/master/EXAMPLES.md#L112

The `express-session` session is getter:
https://github.com/auth0/express-openid-connect/blame/master/EXAMPLES.md#L116

**But the `express-session` session is never destroy.**

The line that you told me: https://github.com/auth0/express-openid-connect/blob/master/lib/context.js#L126 It never runs since config.appSession is false.

**But this is not a bug. I think the examples should be improved.**

Since it is very common that an express-openid-connect user, for example, must have stored the access token to send to an API. It also occurs to me that there could be an example where tokens are saved directly in cookies (http-only).

On the other hand, thanks, the project is very useful to me.

**Comment by adamjmcgrath** [comment]
Oh, my bad - I misread your question. Yes, that example should include destroying the session on logout. 

At the moment you'd need to write your own logout handler and call `session.destroy` in addition to [res.openid.logout()](https://github.com/auth0/express-openid-connect/blob/master/API.md#response)

**Comment by DDDDDanica** [comment]
Hey @adamjmcgrath Thanks for the suggestions. I'm trying to implement similar logout, but the openid is not included outside route. Here's my setup:
```
app.use(async (req, res, next)=> {
  const fullUrl =  req.headers.host +  req.url;
  const router =  auth({
    required: req => req.originalUrl !== '/',
    authorizationParams: {
      requestURL: fullUrl
    },
    handleCallback: async function (req, res, next) {
      ...
      next();
    },
  });
  if(req.url === "/logout") {
      console.log(res.openid)
      req.session.destroy();
  }
  router(req,res,next)
})
```

And i got undefined for `res.openid`. 
Can you help with this one? Thanks a lot.

**Comment by adamjmcgrath** [comment]
Closing - as this is being resolved in the next Beta

**Comment by Pmarouga** [comment]
Hello, how was this resolved? Do we still need to write our own logout handler? Is there any new example about this? I have the problem of never getting logged out even though I use idpLogout: true. Even when i close the browser, and the session should be terminated, when i come back I am instantly logged in.

**Comment by adamjmcgrath** [comment]
Hi @Pmarouga - this SDK creates a logout handler at `${baseUrl}/logout` you need to visit that route in order to log out
