### ISSUE TITLE
Logout function and tokens

### ISSUE THREAD

**Issue by BartoGabriel** [auth0/express-openid-connect#103]
In the logout function, req.openid.tokens is used but this variable does not exist:
https://github.com/auth0/express-openid-connect/blob/master/lib/context.js#L137

It would be nice to have a function that returns the tokens (similar to the getUser function). And by default, save these tokens in cookies (http-only), but by having the function, the user will be able to use another method to save tokens (such as express-sessions).

At the same time the function would be very useful for the user to have the tokens, and use for example in calls to the api.

**Comment by adamjmcgrath** [comment]
Thanks for raising @BartoGabriel 

Yes - that should be `openidTokens` https://github.com/auth0/express-openid-connect/blob/master/index.d.ts#L21

Will raise some work to fix this

**Comment by adamjmcgrath** [comment]
fyi - this is fixed in the next Beta
