### ISSUE TITLE
Removal of automatic refresh

### ISSUE THREAD

**Issue by fredvollmer** [auth0/express-openid-connect#11]
What was the rationale behind removing the automatic refresh feature? Is there a recommended approach to automatically refreshing sessions if the access-token has expired?

Thanks in advance!

**Comment by joshcanhelp** [comment]
Apologies for the delay here. 

Long story short ... we couldn't settle on an implementation we were completely happy with so we pulled it out and, for now, are recommending that application developers do the refresh call themselves ([example here](https://github.com/auth0/express-openid-connect/pull/9#issuecomment-536068323)).

We'll explore adding refresh functionality to this library before beta release, though.
