### ISSUE TITLE
CORS error on accessing cross domain API of express apps

### ISSUE THREAD

**Issue by rahuliet** [auth0/express-openid-connect#135]
### Description

> Allowing access to API (cross-domain) and treating the API request as authenticated and avoid redirecting to authorize/ end point

### Reproduction

> Hit localhost/app/app1 where internally front end of app1 is sending a request to localhost:8022/app/app1/fetch . Below is the code 
Gateway App which is front facing app for all of the sub apps ( app0,app1,app2) - http://localhost/app/
App1 URL - http://localhost/app/app1/
API URL - http://localhost:8022/app/app1/fetch

**Gateway App Code**

`
const express = require('express');
const app = express();

//per application entry

const app0 = require("./app_folder1");
const app1 = require("./app_folder2");
const app2 = require("./app_folder3");
const app3 = require("./app_folder4");

require('dotenv').config();

const {
  auth , requiresAuth
} = require('express-openid-connect');

app.use(auth({
  required:function (req) {
    console.log(req.isAuthenticated());
    if (req.headers['x-requested-with'] === 'XMLHttpRequest')
    return true;
    else
    return false;
    },
  issuerBaseURL: process.env.ISSUER_BASE_URL,
  baseURL: process.env.BASE_URL,
  clientID: process.env.CLIENT_ID,
  clientSecret: process.env.APP_SESSION_SECRET,
  redirectUriPath:'/app/callback',
  authorizationParams: {
    response_type: 'code',
    scope: 'openid profile email',
    custom_param: "custom-value",
    response_mode: 'form_post',
  },
  idTokenAlg: 'RS256',
  appSession: {
    secret: process.env.APP_SESSION_SECRET,
    duration: 3600
  },
  handleCallback: async function (req, res, next) {
    req.appSession = req.appSession || {};
    try {
      next();
    } catch (e) {
      next(e);
    }
  }
}));

// Add headers
app.use(function (req, res, next) {
  res.setHeader('Access-Control-Allow-Origin', '*'); // for reverse proxy
  next();
});

//per application path mapping

app.use('/app/app0/', app0);
app.use('/app/app1/', app1);
app.use('/app/app2/', app2);
app.use('/app/app3/', app3);
app.listen(8022);
`

**Libraries and Dependencies** 

NodeJS - 11
express-openid-connect - 1.0.2
express - 4.16.3
Browser - Google Chrome
Identity provider -  Okta

**Comment by rahuliet** [comment]
@stevehobbsdev - Any help here ?

**Comment by adamjmcgrath** [comment]
Hi @rahuliet - thanks for raising this

```js
required: function(req) {
    console.log(req.isAuthenticated());
    if (req.headers['x-requested-with'] === 'XMLHttpRequest')
        return true;
    else
        return false;
},
```

You need a UI to login, and if you're only requiring auth for XHR requests, then I don't see how you will be able to prompt the user to login.

This MW is for protecting UI routes, for protecting an API you should take a look at https://auth0.com/docs/quickstart/backend/nodejs

**Comment by rahuliet** [comment]
@adamjmcgrath - basically there is no app specific UI to login ,

- gateway redirect to Okta (OAuth implementation) 
- Okta UI  comes to provide org's email and password
- Okta sends back to redirect path within gateway app
- gateway app redirects to app1
- app1 sends API call (here express openid connect triggers authorize request) which fails because of being an xhr request

I need a way to stop this authorize request .

**Comment by adamjmcgrath** [comment]
Hi @rahuliet - apologies, I missed your last update

This SDK is for protecting a UI (not an API). To protect an API you should get an access token from Okta and use it to access your API (see our quickstart here https://auth0.com/docs/quickstart/backend/nodejs/01-authorization for an example)

**Comment by adamjmcgrath** [comment]
Hi @rahuliet - closing this, feel free to reopen if you have any other questions

**Comment by rahuliet** [comment]
thanks @adamjmcgrath .
