### ISSUE TITLE
Authorization code flow

### ISSUE THREAD

**Issue by Cyben** [auth0/express-openid-connect#146]
Hey, I'm interested if there is a way for using this lib with the "Authorization Code Flow" ?
And if so, what configuration should I add?

**Comment by frederikprijck** [comment]
Hi @Cyben ,

You should be able to use Authorization Code flow by setting the following properties on the config provided to the Auth0 middleware:

```
authorizationParams: {
  response_type: 'code',
  response_mode: 'query'
}
```

You will also need to ensure you provide a `CLIENT_SECRET`, either through the environment variables (`process.env.CLIENT_SECRET=SECRET_GOES_HERE`) or as part of the Auth0 config:

```
authorizationParams: {
  response_type: 'code',
  response_mode: 'query'
},
clientSecret: 'SECRET_GOES_HERE'
```

You should be able to try this out by making the above modification to the example application found here: https://github.com/auth0-samples/auth0-express-webapp-sample/tree/master/01-Login

Let me know if this doesnt help.
