### ISSUE TITLE
Not able to get API responses using Postman

### ISSUE THREAD

**Issue by elewin** [auth0/express-openid-connect#147]
### Description

> I have this module installed in my Express app, and while it seems to work perfectly fine when attempting to make a GET request to a protected endpoint in the browser, making the same request in postman results in this response being returned regardless of what protected endpoint I try to hit:

```html
<html>

<head>
	<title>Submit This Form</title>
</head>

<body onload="javascript:document.forms[0].submit()">
	<form method="post" action="http://localhost:3000/callback">
		<input type="hidden" name="id_token" value="eyJhbGciOiJSUzI1NiIsInR5cCI6Ikp..."/><input type="hidden" name="state" value="eyJyZXR1cm5..."/></form>
</body>

</html>
```
(Tokens redacted of course).

### Reproduction

I have set up Postman according to this guide and I am able to successfully log in and get a bearer token using it
https://auth0.com/blog/manage-a-collection-of-secure-api-endpoints-with-postman/

I then make a request to a protected endpoint that ought to return a simple JSON object, but instead get the above HTML with a status code of 200

### Environment

Node 10.22.0
Express 4.17.1
express-openid-connect 2.0.0
Windows 10
Postman 7.34.0

**Comment by adamjmcgrath** [comment]
Hi @elewin - this library is for protecting UI routes (routes that you would visit in your browser), so I wouldn't expect this to work for requests not made in a browser (eg through Postman). What you're seeing is the form post callback page served by the Authorization server (see the "Form with ID Token field sent to browser" in the aArchitecture docs https://github.com/auth0/express-openid-connect/blob/master/ARCHITECTURE.md#protect-a-route)

To protect an API, take a look at this QuickStart https://auth0.com/docs/quickstart/backend/nodejs/01-authorization
