### ISSUE TITLE
Support: spa and backend on different subdomains, but same domain

### ISSUE THREAD

**Issue by amadeus-x1** [auth0/express-openid-connect#148]
Is this library recommended for the scenario where spa and backend are on different subdomains?
I am not able to find a way to do the final redirect to a different subdomain (i.e., redirect to subdomain belonging to app with cookie being set)
For now I am using another set of redirect, post the setting of cookies, just to redirect from backend subdomain to app subdomain.
Is this flow recommended?

**Comment by adamjmcgrath** [comment]
Hi @amadeus-x1 are you serving the UI from the SPA only or both the SPA and the Express App?

**Comment by haritabh-z01** [comment]
In my current configuration I am serving it from spa only.
SPA is at app.domain.com, while express app is at gateway.domain.com
Post successful retrieval of tokens from oidc provider, I am doing a 302 redirect from gateway.domain.com to app.domain.com

SPA gets a 403
SPA redirects to gateway.domain.com/app (protected route)
gateway redirects browser to oid provider (auth.domain.com)
user authenticates and is redirected to gateway.domain.com/app/callback
gateway sends cookies to browser and redirects back to gateway.domain.com/app

express handler for gateway.domain.com/app redirects browser to app.domain.com

**Comment by amadeus-x1** [comment]
In my current configuration I am serving it from spa only.
SPA is at app.domain.com, while express app is at gateway.domain.com
Post successful retrieval of tokens from oidc provider, I am doing a 302 redirect from gateway.domain.com to app.domain.com

SPA gets a 403
SPA redirects to gateway.domain.com/app (protected route)
gateway redirects browser to oid provider (auth.domain.com)
user authenticates and is redirected to gateway.domain.com/app/callback
gateway sends cookies to browser and redirects back to gateway.domain.com/app

express handler for gateway.domain.com/app redirects browser to app.domain.com

**Comment by adamjmcgrath** [comment]
> In my current configuration I am serving it from spa only.

If you are serving your UI from a SPA and your api from the express app. then you should protect your express API using access tokens (see this quickstart: https://auth0.com/docs/quickstart/backend/nodejs/01-authorization) and you should get your access token in your SPA (eg using the auth0 spa sdk https://auth0.com/docs/libraries/auth0-single-page-app-sdk#call-an-api)

This SDK is for protecting Express UI routes only.

**Comment by amadeus-x1** [comment]
@adamjmcgrath thanks for prompt reply.
Our design is still up for debate, I can start serving the SPA from express, or move over to access tokens based auth.
I am undecided about which route is more secure.
from https://auth0.com/docs/tokens/token-storage
> When the SPA calls only an API that is served from a domain that can share cookies with the domain of the SPA, no tokens are needed. OAuth adds additional attack vectors without providing any additional value and should be avoided in favor of a traditional cookie-based approach.

In my case api layer and SPA can share cookies (due to same root level domain), so shouldn't cookie based auth be preferred?

**Comment by amadeus-x1** [comment]
Also, to clarify, while the backend isn't serving SPA directly, all the calls made by SPA will be via that backend only. (gateway.domain.com) and have route protection via this sdk.

**Comment by adamjmcgrath** [comment]
> In my case api layer and SPA can share cookies (due to same root level domain), so shouldn't cookie based auth be preferred?

Yep, you're right - sorry, I misread your original message. If the Express MW is running on `gateway.domain.com` then the user must access `gateway.domain.com` over a browser for login to work.

When you say "SPA gets a 403", do you mean that it's making an xhr request to `gateway.domain.com` which is failing with a 403, when you're expecting it to be authenticated?

**Comment by amadeus-x1** [comment]
@adamjmcgrath yep, the SPA makes a xhr call to `get current user` as its first call to `gateway.domain.com/api`, and if the cookie doesn't exist, the response is 401 (sorry, I meant 401, not 403)
in case any xhr request evaluates in 401, we do a redirect on SPA side
`window.location.href=gateway.domain.com/app/login`
and then the login flow happens as I described earlier.

I guess the essence of my question is how to properly implement authentication cookies using authorization code grant on backend side, when backend and spa have different subdomains.

**Comment by adamjmcgrath** [comment]
Yes, this should be possible, you just need to make check that the "appSession" cookie is set on "domain.com" (not "gateway.domain.com") it should do this by default if the `session.cookie.domain` option is not set.

gateway.domain.com should also set CORs headers like:
```
Access-Control-Allow-Origin: https://app.domain.com
Access-Control-Allow-Credentials: true
```

And your spa should send a request to the other subdomain with credentials included:
```js
fetch('https://gateway.domain.com/api', {
  credentials: "include"
});
```

Let me know if any of those suggestions are helpful (we should create an example for this use case)

**Comment by amadeus-x1** [comment]
@adamjmcgrath yeah, this is how I have implemented it currently.
I guess my only concern is that is this pattern recommended, I have never seen it being used elsewhere.
Also, it results in couple extra redirects right now, since there is no way to configure the middleware to redirect to a different subdomain post successful auth. So I have to manually do another redirection post auth.

i.e., the last two steps here [comment](https://github.com/auth0/express-openid-connect/issues/148#issuecomment-709931996)

> gateway sends cookies to browser and redirects back to gateway.domain.com/app
> express handler for gateway.domain.com/app redirects browser to app.domain.com

**Comment by adamjmcgrath** [comment]
> I guess my only concern is that is this pattern recommended, I have never seen it being used elsewhere.
Yes, I see no problem with your architecture. It would be simpler if the SPA and API were on the same domain, but I see no issue with using separate subdomains and cors (just make sure your restrictive with your CORS headers, eg no `Access-Control-Allow-Origin: *`)

There's a similar architecture here https://auth0.com/docs/sessions-and-cookies/spa-authenticate-with-cookies (except for the subdomain stuff)

> Also, it results in couple extra redirects right now

There's currently 1 extra redirect, but you can remove this by setting the `returnTo` param in `login` to point to your SPA, eg:

```js
app.use(
  auth({
    routes: {
      // Override the default login route
      login: false,
    },
  })
);

app.get('/login', (req, res) => res.oidc.login({ returnTo: 'https://app.domain.com' }));
```

**Comment by amadeus-x1** [comment]
thanks a lot. I was able to get it working and remove the extra redirect.
