### ISSUE TITLE
Inconsistency in Docs for Refresh Tokens

### ISSUE THREAD

**Issue by qstearns** [auth0/express-openid-connect#153]
### Description

The docs suggest that you can [use refresh tokens by requesting the offline_access scope](https://github.com/auth0/express-openid-connect/blob/master/EXAMPLES.md#5-obtaining-and-using-refresh-tokens), however this conflicts with the behavior in the source, which suggests that if the `response_type` is `code` that [the refresh flow will use PKCE](https://github.com/auth0/express-openid-connect/blob/0def341d71ef08a48fe82d19fb8c2dc8d61d0ecb/lib/context.js#L211-L217).

I don't view this as being as simple as removing the conflicting example from the docs, because the example treats with what I view as a core use-case of this library: providing a refresh token to use from the JS side of your application. There is no obvious way (nor am I confident that it is secure) to pass the PKCE challenge to a client and even if you get the PKCE challenge to the client, auth0 does not provide a clear path to inject the PKCE challenge into a browser client. I'm happy to open up a pull request removing the conflicting API example if it doesn't make sense to include a replacement for the old flow.

### Reproduction

You can reproduce this issue by trying to read an accessToken off of the RequestContext when requesting Offline Access from your OIDC client.

### Environment

> Please provide the following:

- Library Version: 2.0.0
- Node: 14.8.0

**Comment by frederikprijck** [comment]
Hi @qstearns ,

I am not sure I fully understand the inconsistency you are talking about.

You can request a refresh token by specifying the `offline_access` scope.
Using the `response_type` set to `code` ensures OAuth's `PKCE` flow is being used. 

Bot of the above are correct and not directly related to each other, so I do not see why there two statements would be in conflict. The first one is saying you want to receive a refresh token when asking for a token wheres the other is saying how you will be retrieving those tokens.

> There is no obvious way (nor am I confident that it is secure) to pass the PKCE challenge to a client and even if you get the PKCE challenge to the client, auth0 does not provide a clear path to inject the PKCE challenge into a browser client

Could you elaborate on what you mean here ?

Generally, when using the PKCE, this is what is happening in the browser:
- A random string is generated which is known as the `code_verifier`
- This string is hashed. This hashed value is what we call the `code_challenge`
- The `code_challenge` together with the hash method being use, the `client_id` and `scopes` (which can include `offline_access`) is sent to the `/authorize`
- The `/authorize` endpoint returns an `authorization code`
- The `code_verifier` is sent to the `/token` endpoint, together with the `client_id`
- The `/token` endpoint will then compare the `code_challange` and the `code_verifier`, by re-hashing the code_verifier using the provided hashing method when calling the `/authorize` endpoint. If they match, it will return an Access Token and, depending on the provided scopes, an ID Token and Refresh Token.

This flow is invented for applications which can not securely store a Client Secret, however, using PKCE in that case does not involve storing any sensitive information in the client. So I am not sure which part you are seeing as unsecure here,

More info on using PKCE can be found at https://auth0.com/docs/flows/authorization-code-flow-with-proof-key-for-code-exchange-pkce

**Comment by qstearns** [comment]
Hey @frederikprijck,

Thanks for the quick reply. I don't mean to suggest anything is insecure, I just have a sense there is an inaccuracy in the documentation. Certainly clear at this point I'm missing something in the bigger picture.

To backtrack, the reason I assumed to be related to PKCE is that I am not getting a refresh token in my `OidcContext` when I add `offline_access` to the scopes in my client. I had understood PKCE to be an alternative to refresh tokens, and as such, I thought perhaps PKCE was the reason for the absence of my  refresh token.

I am working on coming with a reproduction of the issue of the missing refresh token, so I can show you what is going on more specifically. I am having trouble with this as the examples in the repo are failing with:
```
BadRequestError: state mismatch, expected eyJyZXR1cm5UbyI6Ii9zZXJ2aWNlLXdvcmtlci5qcyJ9, got: eyJyZXR1cm5UbyI6Ii8ifQ
    at /home/qstear/src/express-openid-connect/middleware/auth.js:105:31
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

The "old flow" I am referring to is serving a refresh token alongside a server-rendered webpage, so that my browser client can use the refresh token for continued access to my API. I am also happy to accomplish this by implementing the PKCE flow in my client (though I do not believe this is what is intended).

**Comment by qstearns** [comment]
Just to update on the state mismatch error from above, it appears that for some reason the example OIDC provider wants to change the `returnTo` param to go to `serviceWorker.js`

**Comment by frederikprijck** [comment]
In the initial post, you mentioned the reproduction steps as follows:

> You can reproduce this issue by trying to read an accessToken off of the RequestContext when requesting Offline Access from your OIDC client.

However, [refresh tokens should be requested by calling refreshToken on the RequestContext](https://github.com/auth0/express-openid-connect/blob/master/lib/context.js#L89). Does that return any value ?

Another thing to verify: Is the application in Auth0 configured to be using Refresh Tokens ?

**Comment by qstearns** [comment]
Ah, yes the above was a typo. I am using the following code to access the refreshToken:

```ts
tokens: {
  accessToken: req.oidc.accessToken?.access_token,
  refreshToken: req.oidc.refreshToken
}
```

and `tokens.refreshToken` will always be `undefined`.

My application is set to use the Rotating token behavior.

**Comment by qstearns** [comment]
Still trying to reproduce outside of my own environment, but I'm still having trouble wrestling with the OIDC server

**Comment by frederikprijck** [comment]
Feel free to provide a reproduction sample connected to Auth0 instead of the example OIDC if that would be easier. As long as we can reproduce the bug you are experiencing we should be able to investigate what is going on.

**Comment by adamjmcgrath** [comment]
hey @qstearns - some idps require `prompt=consent` when requesting the `offline_access` scope https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.11

See the running example https://github.com/auth0/express-openid-connect/blob/master/examples/access-an-api.js#L12-L15

**Comment by qstearns** [comment]
Hey @adamjmcgrath, thanks for hopping on the thread. I'm starting to get a bit worried that there's no bug and this is pure user error, in which case I'll happily close and pop over to Auth0 community.

I have managed to reproduce this issue using the consent flag here (at least on my machine):

https://github.com/qstearns/express-openid-connect/blob/master/examples/access-an-api.js

This example is simplified to just print the refresh token to stdout from the default access-an-api example. You can run it with (while adding an `AUDIENCE` and other `OIDC` environment variables)

```
npm run start:example --access-an-api
``` 

Right now it prints:

```
the refresh token is:  undefined
```

I'm using auth0 as my idp and my application is configured with the OIDC-compliant flag. If this is just something dumb on my end, I'll go ahead and close and I'd be happy to contribute some docs that prevent someone else from falling into the same situation that I have.

**Comment by qstearns** [comment]
If either of you have any luck reproducing with my example, please let me know and thanks for looking into this so far.

**Comment by qstearns** [comment]
Okay I'm definitely having problems getting refresh tokens out of my app. I'll close for now and revisit with the auth0 community.

**Comment by qstearns** [comment]
@adamjmcgrath or @adamjmcgrath, would you guys be open to a PR that throws an exception (or perhaps at least a debug log line) if the client requested `offline_access`, but doesn't receive a `refresh_token`? I'm not sure if that makes sense in the larger scheme of things as I know that it's allowed (and encouraged) in the spec for providers to ignore `offline_access`

**Comment by frederikprijck** [comment]
I am still not sure what the actual problem is you are facing. I tested your example branch, and running it instantly logged a refresh token for me.

```
Starting a mock authorization server. You can login with any credentials.
Authorization server started at http://localhost:3001
API started at http://localhost:3002
Example app started at http://localhost:3000
the refresh token is:  CUjnq6iFgevogQ1KyYOocYLrG1WNV9idGqE2u0l_47z
```

I don't think an error in our SDK is going to be helpful in this case, but I am curious to understand why you are not getting one that makes you think such an error could be useful.

**Comment by qstearns** [comment]
Ah, so my problem was ultimately that my auth0 API wasn't configured to allow offline access (though my Application and client were configured correctly). The issue was just my own misconfiguration.

I think I could have diagnosed this problem much more quickly, if I knew that the OIDC client was expecting to receive a refresh token, but didn't (as opposed to me incorrectly using the API to access it.) It was not clear to me in the beginning that it's common to request `offline_access`, but not receive it. It seems like there are many conditions that might cause a newcomer to misconfigure the provider, which would result in no refresh token -- perhaps failing to pass an audience or failing to pass prompt=consent.

The assumption that this would be useful rests on the idea that it is actually expected that, if an OIDC client requests offline_access, it will receive a refresh token (which I could be wildly incorrect about). But if it is expected, I thought it might make it easier for developers to get a warning (an exception is probably drastic) that they didn't get what they expected.
