### ISSUE TITLE
Dynamic Client Authentication

### ISSUE THREAD

**Issue by madaster97** [auth0/express-openid-connect#161]
### Describe the problem you'd like to have solved
I'm trying to develop against an OIDC provider where for a single issuer I may use several different sets of client authentication, even for a single client ID.

Currently, if I startup a single instance of express-openid-connect, I can only assign a single client secret. I would like to be able to dynamically "route" what client authentication I use based on the parameters of the "/login" request.

### Describe the ideal solution
Expose client authentication as part of the <a href="https://auth0.github.io/express-openid-connect/interfaces/loginoptions.html">LoginOptions</a> interface, that way we can dynamically assign the client authentication credentials based on the request itself. Specifically, the /login request to my server will expect a query string param indicating what "instance" to route to and what client authentication to use at the token endpoint for that request.

For this use case, we know precisely what authentication to use by the time the "/login" request comes in.

I think it's a fair assumption that "Dynamic Client Credentials" will only depend on the "/login" request, and that we don't need to do anything fancy like a dynamic function at the "/callback" endpoint.

The challenging bit may be securing the authentication credentials used. For each login flow, we shouldn't be independently storing the client secret in the request's session, as this seems like a security risk. Maybe assigning a key or indicator to the request, and having a sort of key map built into the config would be best.

For instance, lets say that on my "/login" request I can receive a query string param called "issuer" that I will use to route my application. This parameter could have values of "issuer_1" or "issuer_2" which correspond to client secrets "secret_1" and "secret_2" respectively.

In my auth config, I could now include a "clientSecretMap" JSON object containing all of my client secrets keyed to the "issuer"
```javascript
const config = {
  // Other config...
  clientSecretMap: {
    "issuer_1": "secret_1",
    "issuer_2": "secret_2"
  }
};
```
Then, within a new parameter on the login request, we could dynamically "route" to any of these pre-configured keys based on the login request itself, rather than re-caching a dynamically generated secret in the requests session.
```javascript
router.get('/launch', function(req, res, next) {
  res.oidc.login({
    // Other config ...
    clientSecretKeyMap: req.query.issuer
  });
})
```
If an application tried to route to an issuer that wasn't in the key-map, the request should fail rather than sending a null client secret. This map should be just smart enough so that the developer doesn't need to "double-check" the issuer before attempting to pass the key in.

I don't think we should allow for both a static clientSecret and a key map in the same config. Developers should choose one or the other, and if needed include a default key in their map that they can route to as needed.

## Alternatives and current work-arounds
I could spin up several instances of the application with duplicate config (other than the client credentials).

The thing is, this significantly increases startup time, and all of the startup middlewares would be independently calling to the same OIDC metadata endpoint.

I'm also not 100% on how managing several sets of this middleware in one process would work.

**Comment by adamjmcgrath** [comment]
Hey @madaster97

Thanks for sharing this use case with us, unfortunately it doesn't sound like something we'd want to add support for, but happy to hear more about your high level use case to see if we can help. As you point out, you could do this with multiple instances of the mw

> and all of the startup middlewares would be independently calling to the same OIDC metadata endpoint.

The discovery endpoint calls are memoized by issuer, so if you have a single issuer you will have a single request (if you have multiple issuers you will have multiple requests, regardless of how many middlewares you have)

> I'm also not 100% on how managing several sets of this middleware in one process would work.

Yeah, it would be tricky. Since the `/callback` route does the code exchange (with the client secret) you'd need multiple instances of that, which would not be possible without multiple instances of the whole middleware

**Comment by madaster97** [comment]
Hey @adamjmcgrath 

Thanks for the response. 

Would I be able to support several sets of the middleware on the same endpoint? Do you think that the internal session(s) of the different middleware would collide somehow?

My current idea is to instantiate all the middlewares on startup, and then dynamically call one depending on the routing parameter. For the same key map above:
```javascript
let keyMap = JSON.parse(
  fs.readFileSync(`./keyMaps/${process.env.KEY_MAP}.json`)
);
let middlewares = {};

for (key in keyMap) {
  middlewares[key] = auth({
    ...config,
    clientSecret: keyMap[key],
  });
}

app.use(function (req, res, next) {
  const { iss } = req.query;

  // Store routing param in session
  // req.session.iss = iss;

  // Apply middleware
  middlewares[iss](req, res, next);
});
```

**Comment by adamjmcgrath** [comment]
Hey @madaster97 - not tested this, but here's how I would do multiple auth mw's sharing the same session

```js
// set cookie path to `/` to make session available at http://localhost:3000/
app.use('/issuer-a', { ...config, clientSecret: 'a', baseUrl: 'http://localhost:3000/issuer-a', session: { cookie: path: '/' }});
app.use('/issuer-b', { ...config, clientSecret: 'b', baseUrl: 'http://localhost:3000/issuer-b', session: { cookie: path: '/' }});

app.get('/login', (req, res) => {
  const { iss } = req.query;
  req.redirect(`/${iss}/login`); // /issuer-a/login or /issuer-b/login
})
```

**Comment by madaster97** [comment]
Thanks Adam,

I managed to get this to work with my code above. I dynamically assign which instance of the middleware to use based on parameters at a "launch" endpoint. I did this so I could have the separate instances on the same endpoint (rather than /issuer-a or /issuer-b like you have above).
