### ISSUE TITLE
Support JWT-Based Client Authentication

### ISSUE THREAD

**Issue by madaster97** [auth0/express-openid-connect#162]
### Describe the problem you'd like to have solved
I am trying to develop against on OIDC provider that only accepts private_key_jwt client authentication, and am unable to with this middleware.

### Describe the ideal solution
Add support for private_key_jwt and client_secret_jwt client authentication methods. In the startup config, a field for a JWKs set would be best, where the specific KID to be used on a request could be routed on login (similar to solution in this <a href="https://github.com/auth0/express-openid-connect/issues/161">issue</a>). If the JWK only had one key, then that could be used as a default client authentication value.

## Alternatives and current work-arounds
None for this library. I'm currently trying to wrap express around openid-client myself, but that loses a lot of the awesome functionality in this lib :)

**Comment by adamjmcgrath** [comment]
Hey @madaster97 - thanks for your suggestion, let me kick the idea round with my team and get back to you on it. 

Response may be a bit slow next week because of thanksgiving

**Comment by madaster97** [comment]
Thanks Adam. Have a nice Thanksgiving!

**Comment by madaster97** [comment]
Adding one more item here. Some authorization servers support "none" for client authentication.

For issuers that support public clients, it would be great if this library could be used for authorization code or hybrid flows without using client authentication.

**Comment by adamjmcgrath** [comment]
Hey @madaster97 

Regarding `private_key_jwt` and `client_secret_jwt` - adding these new client methods is out of scope for us, mainly because Auth0 doesn't support them. We'd of course be happy to look at a pull request - with the caveat that we may be opinionated about how it's implemented 😄 

We support the 'none' `clientAuthMethod` with implicit, but we won't support it with hybrid since this is a backend SDK that can keep a secret

**Comment by madaster97** [comment]
Thanks Adam. I'll consider it! Right now I'm just using openid-client manually with express. Also, the none bit makes sense. Thanks!
