### ISSUE TITLE
Set the redirect uri dynamically

### ISSUE THREAD

**Issue by june07** [auth0/express-openid-connect#166]
### Describe the problem you'd like to have solved

Current dev environment is...

my-dev-domain.com -> (30x redirect) -> some-dynamic-tunnel.ngrok.io

Given this setup, auth will not work because the configured callback domain (my-dev-domain.com in this case) cookies will not be set because of the 30x redirect that is happening above. Changing the callback domain manually won't help because the tunnel is dynamic and that would break a smooth workflow.  The whole point of the setup above is to have a static redirect and smooth out the workflow.

### Describe the ideal solution

Ideal solution is to configure the redirect uri to match the referrer, thus the cookies will be set on the tunnel address and all is well in the world.

The following commit to my fork works nicely.  Auth0 allows wildcard callbacks and it's working excellently.
https://github.com/june07/express-openid-connect/commit/667b7662cca7ae42f2e722ab79161644f88140e8

The referrerRedirect option by default would have zero effect.

**Comment by adamjmcgrath** [comment]
Hi @june07 - Thanks for raising this.

I'm not sure I understand the issue - as long as the domain of you login url matches the domain of your callback url, then the callback will pick up the cookies dropped by the login and should work fine - regardless of how many redirects happen in between.

Could you explain more about why you can't set the domain of the redirect uri to the domain of the login at the time of login?

**Comment by june07** [comment]
@adamjmcgrath Thanks for the update.  I can't duplicate the issue now as I found a workaround.  But I'll open this in the future if I ever come across it again.  Thanks.
