### ISSUE TITLE
Type definition of config params conflict with Joi Validation

### ISSUE THREAD

**Issue by sheunglaili** [auth0/express-openid-connect#167]
### Describe the problem

installed package have different definition with github repository 
![螢幕截圖 2020-12-14 下午1 54 09](https://user-images.githubusercontent.com/31618202/102045373-d98b0700-3e13-11eb-930c-9fc13bd960b5.png)

### What was the expected behavior?

should have same index.d.ts with github master branch 

### Reproduction
- npm install express-openid-connect
- check the node_modules
- see the difference of index.d.ts between installed package and master branch

### Environment
express-openid-connect: 2.0.0.
node: v12.19.0
npm: v6.14.8

**Comment by davidpatrick** [comment]
The installed package is from the release cut on Sept 17 https://github.com/auth0/express-openid-connect/releases/tag/v2.0.0 -- the code in the master branch has not been cut for a release yet.
