### ISSUE TITLE
OPError: expected 200 OK with body but no body was returned

### ISSUE THREAD

**Issue by cjwiseman11** [auth0/express-openid-connect#174]
### Describe the problem

I am migrating over to express-openid-connect from the auth0 passport flow and I seem to receive this error when trying to hit any of the endpoints (/login /logout etc): OPError: expected 200 OK with body but no body was returned.

Everything worked fine with the Passport flow. If I run my server (node index.js) in Windows, this error occurs when I try to hit any of the endpoints, however in the same environment using Ubuntu with WSL2, it works fine - Ubuntu itself also works fine.

The issue only seems to occur in my Windows environments. I tried this on 2 different computers. 

The issue seems to be that nothing is returned when trying to get the .well-known config (error occurs at /openid-client/lib/helpers/process_response.js:48:11 so perhaps this is an openid issue?)

### What was the expected behavior?

When hitting any of the provided endpoints like /login, I should be redirected to Universal Login, but instead I get this error.

### Reproduction

- Step 1: Download and run the auth0 express quickstart project in Windows environment
- Step 2: Try to login

### Environment

- Version 2.1.0
- Node.js
- The error occurs in my project and the auth0 express quickstart so I reckon it's Windows related rather than any other modules

**Comment by frederikprijck** [comment]
Hi @cjwiseman11 ,

I ran the Auth0 Express Quickstart on my Windows 10 system and it's working fine. 
I am not using WSL or anything, so it should be working fine on Windows.

Is there anything showing up in your Tenants Logs in Auth0?
Does the issue persist if you create a new Application of type Web Application in Auth0 and use it's settings?

**Comment by cjwiseman11** [comment]
Hiya, thank you for your response.

I just tried creating a new application as suggested and that does seem to work with the Express quickstart, so it must be something with the application. I'll look to use the new one - I can't see any obvious differences but I've obviously broken something!

Thanks for your help.
