### ISSUE TITLE
auth ConfigParams

### ISSUE THREAD

**Issue by dhall2211** [auth0/express-openid-connect#178]
Is it possible to use dynamic values in the config.route.postLogoutRedirect example: 
`const authRequestHandler = auth({
  issuerBaseURL: process.env.IDENTITY_URL,
  baseURL: process.env.BASE_URL,
  clientID: process.env.CLIENT_ID,
  clientSecret: process.env.CLIENT_SECRET,
  secret: process.env.COOKIE_SECRET,
  authRequired: false,
  idpLogout: true,
  routes: {
    callback: '/signin-oidc',
    login: '/login',
    logout: '/logout',
    postLogoutRedirect: '${dynamicValue}',
  },`

if so where would you add this on a router.replace()?

**Comment by adamjmcgrath** [comment]
Hi @dhall2211 - thanks for raising this

Yes, this is possible using the `returnTo` argument of the `logout` middleware, which you can call yourself if you override the logout route, eg

```js
app.use(
  auth({
    routes: {
      // Override the default logout route
      logout: false,
    },
  })
);

// Create your own logout route
app.get('/logout', (req, res) => {
  res.oidc.logout({ returnTo: '${dynamicValue}' })
});
```
