### ISSUE TITLE
Please add base64url to dependencies for use with YARN 2 packager

### ISSUE THREAD

**Issue by JMS-1** [auth0/express-openid-connect#179]
### Describe the problem

We are using the package with yarn 2. yarn 2 will respect all dependencies and create a package bundle. When our application starts it reports a missing base64url dependency. Concerning yarn 2 this is correct: base64url is indirectly referenced through openid-client but you [require it directly in your own code](https://github.com/auth0/express-openid-connect/blob/6e516f1e99365b245a23efff6a20b659b986b196/lib/hooks/getLoginState.js#L1). This is fine for yarn 1 or npm which will recursivly project all indirect dependencies in the tree.

Generally it's a good rule to always add dependencies for each require/import and not rely on other packages.

### What was the expected behavior?

Should well behave with yarn 2.

### Reproduction

I hope we can go without since reason and fix are more than obvious ;-)

### Environment

- package version is 2.1.0 - package.json not really change towards 2.2.0
- yarn 2 with node 14.15.4 and debian buster

**Comment by JMS-1** [comment]
FYI: after the update of openid-client to 4.2.3 this night your package fails with yarn 1 as well. The made base64url a devDependency: https://github.com/panva/node-openid-client/compare/v4.2.2...v4.2.3#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by bolmaster2** [comment]
This is also a problem with node 15 and npm 7, not just with yarn
