### ISSUE TITLE
Missing package.json requirement

### ISSUE THREAD

**Issue by mattgodbolt** [auth0/express-openid-connect#181]
### Describe the problem

Installing the package and trying to require it led to a module not found:

```
  requireStack: [
    '/home/mgodbolt/dev/personal/ce/compiler-explorer/node_modules/express-openid-connect/lib/hooks/getLoginState.js',
    '/home/mgodbolt/dev/personal/ce/compiler-explorer/node_modules/express-openid-connect/lib/config.js',
    '/home/mgodbolt/dev/personal/ce/compiler-explorer/node_modules/express-openid-connect/middleware/auth.js',
    '/home/mgodbolt/dev/personal/ce/compiler-explorer/node_modules/express-openid-connect/index.js',
    '/home/mgodbolt/dev/personal/ce/compiler-explorer/app.js'
  ]
```

### What was the expected behavior?

Importing the module should work.

### Environment

- **Version of this library used:** 2.2.0
- **Which framework are you using, if applicable:** express
- **Other modules/plugins/libraries that might be involved:** n/a
- **Any other relevant information you think would be useful:**

I solved the problem by manually installing `base64url` with `npm install`.

**Comment by alexmuller** [comment]
I agree, I've also just run into this problem today, found your issue and resolved it the same way 👍 

I think this was fixed by #180 and it'll need a release to npm.

**Comment by NotMyself** [comment]
This issue is also affecting our express based lab applications.

**Comment by davidpatrick** [comment]
We will get a patch release out today with the recent fix.  Thanks everybody for raising the impact visibility
