### ISSUE TITLE
Stub protected routes

### ISSUE THREAD

**Issue by yaakovfeldman** [auth0/express-openid-connect#184]
What is the best way to perform integration testing when the test script tries calling a route that is protected?

My test script checks for 200 responses but it gets 302 responses as it is not logged in. One option is to stub the auth middleware in the test environment using a package like Sinon but how can this be done when `authRequired` is set to true?

**Comment by adamjmcgrath** [comment]
Hi @yaakovfeldman - I added a simple example of testing `express-openid-connect` protected routes when `authRequired` is set to `true` here https://github.com/adamjmcgrath/eoidc-testing-example

**Comment by yaakovfeldman** [comment]
@adamjmcgrath Thank you, that is really clear!
