### ISSUE TITLE
Add the ability to introspect tokens

### ISSUE THREAD

**Issue by Luffyyy** [auth0/express-openid-connect#186]
### Describe the problem you'd like to have solved

There's no way to introspect tokens. There are cases where you want to make sure the tokens are valid. I'm using Keycloak and without introspection of tokens I sometimes can hit an error if the user's token isn't valid anymore while the library thinks it is (You can get this effect by forcibly logging out the user through the KeyCloak admin console).

### Describe the ideal solution

Either add a function for that or have the library introspect the tokens.

## Alternatives and current work-arounds
Forcibly adding it yourself and then checking if the token is active.
Adding this to lib/context.js: 
```js
  async introspectToken(token, tokenHint) {
    const { config } = weakRef(this);

    const client = await getClient(config);
    try {
      const introspect = await client.introspect(token, tokenHint);
      return introspect;
    } catch (err) {
      return undefined;
    }
  }
```
Not making this a pull since I'm not really sure how it should be setup.

### Additional information, if any

Seems to be a feature in https://github.com/panva/node-oidc-provider which I understand the library uses.

**Comment by adamjmcgrath** [comment]
Hi @Luffyyy - thanks for your suggestion

Auth0 doesn't support token introspection, so we don't have much of an appetite to add it.

That said, always happy to look at a PR

I would imagine it to be implemented similar to how `client.userinfo()` was implemented here https://github.com/auth0/express-openid-connect/pull/124/commits/0885357c4881e714efdb394ceab3b0e2f7e03717

**Comment by surensinghkhatana** [comment]
> Auth0 doesn't support token introspection, so we don't have much of an appetite to add it.

 Then how does a resource server supposed to verify the validity of the access token ? Is it that Auth0 only supports self-contained tokens and not reference/opaque tokens ?

**Comment by adamjmcgrath** [comment]
@surensinghkhatana 

> How does a resource server supposed to verify the validity of the access token ?

This SDK is not designed for resource servers, it's designed for OpenID Connect clients - so your question does not relate to this SDK

>  Is it that Auth0 only supports self-contained tokens and not reference/opaque tokens ?

You can get full details on what type of Access Tokens Auth0 supports here https://auth0.com/docs/tokens/access-tokens

**Comment by surensinghkhatana** [comment]
@adamjmcgrath Thanks for your response. It's clear now.
