### ISSUE TITLE
Static OAuth state param

### ISSUE THREAD

**Issue by dkleber89** [auth0/express-openid-connect#189]
Hello,

we are going to launch a new public application. And finally we make a pen test.

We using this lib for the auth process with an identity server 4. Now in the pen test there are a security vulnerability that the state param of the oauth url are static.

Is there a way to generate a random number?

Thanks for help

**Comment by adamjmcgrath** [comment]
Hi @dkleber89 - thanks for raising this

Can I confirm that you're suggesting that we allow customisation of the value of the state parameter we pass to the authorisation server in the authentication request, eg

`/authorize?state=xyz123` -> `/authorize?{some random number}=xyz123`

An [openid connect compliant authorization server will be expecting](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) the parameter to be named `state`, so I don't think there's much we can do here.

Could you share more details about what vulnerability identity server 4 has identified?

**Comment by dkleber89** [comment]
Hi @adamjmcgrath 

the pen test security issue means xyz123 is on every request static ... but to prevent csrf attacks this should be on every request another value

 /authorize?state=xyz123 ->  /authorize?state={random number}

On our Application it seems to be static but i don´t know how make this value random ... Maybe i make something wrong?

Thanks for help

**Comment by adamjmcgrath** [comment]
Hi @dkleber89 - ah, I get it now

If you're using the implicit flow (the default for this SDK) then the `nonce` parameter provides CSRF protection.
If you're using the code flow with PKCE, then PKCE will provide CSRF protection

In openid-connect flows - you don't need to rely on the `state` parameter for CSRF.

See "OAuth 2.0 Security Best Current Practice"

> Clients that have ensured that the authorization server supports PKCE [RFC7636]
> MAY rely the CSRF protection provided by PKCE.  In OpenID Connect
> flows, the "nonce" parameter provides CSRF protection.

https://datatracker.ietf.org/doc/draft-ietf-oauth-security-topics/?include_text=1

You should update your pentest accordingly

**Comment by dkleber89** [comment]
Oh thanks for your Explanation
