### ISSUE TITLE
Question: SilentLogin / SSO config first request

### ISSUE THREAD

**Issue by dkleber89** [auth0/express-openid-connect#195]
Hi,

i have multiple next.js apps and use this sdk für the session handling.

PROBLEM DESCRIPTION:
on "app1" one public page and all other are behind login.
on "app2" all sites are behind login

the apps share all the same domain so we have the ability for sso in our environment. attemptSilentLogin is true.

When i switch from "app2" (user is logged in)  to "app1" the initial request loads the ssr page.

My problem is that the login is not done on the first request so my page shows the user the login button (The user think he is not logged in) but in behind the login is done for this user ... When the user reloads the page then he is logged in.

MY QUESTION:
is there a way to block the first request until the silent login is done so also the first request have the right data for ssr? Or is there an other way for this usecase? I think this is a common usecase?

Thanks,
dkleber89

**Comment by adamjmcgrath** [comment]
Hi @dkleber89 - thanks for sharing your use case

I'm not sure I understand the mechanics of what you're doing - would you be able to share some code I can take a look at?

**Comment by dkleber89** [comment]
Hi @adamjmcgrath 

Code sharing is a little bit tricky ...

We have a central Identity Server for all of our apps -> login.company.com

We have 2 apps at this time:
  * app1.company.com
  * app2.company.com

This is the config of the auth middleware on all apps the same -> 
```
const authRequestHandler = auth({
  issuerBaseURL: process.env.IDENTITY_URL,
  baseURL: process.env.BASE_URL,
  clientID: process.env.CLIENT_ID,
  clientSecret: process.env.CLIENT_SECRET,
  secret: process.env.COOKIE_SECRET,
  authRequired: false,
  idpLogout: true,
  routes: {
    callback: '/signin-oidc',
    login: '/login',
    logout: '/logout',
    postLogoutRedirect: '/',
  },
  authorizationParams: {
    scope: 'openid email offline_access profile user.sapdata user.portal',
    response_type: 'code',
  },
  session: {
    name: process.env.PROJECT === 'project1' ? 'project1SC' : 'project2SC',
    cookie: { domain: process.env.COOKIE_DOMAIN },
    absoluteDuration: 36000,
    rollingDuration: 1800,
  },
});
```

Steps:
 1. The user is logged in in app1 everything is fine.
 2. He switch to app2 (Landing page is public) on first request the silent login is performed by the sdk (Same Cookie name on same domain .company.com so we have the session for silent login) also fine.

But this first request goes also straigth through to the nextjs req handler and the ssr renders the page for the user.
At this time we have no token because of the pending silent login so ssr think the user is not logged in and renders the page with the login button. Bad :-( User is logged in in Background

3. The User makes a reload of the page ... The User can see it is logged in


So my Question is ... Is there a way to avoid this? Maybe there is a way to e.g. block the first request as long as the login is pending or something else?

I think this is a very common usecase in SSO? Or do i think too complicated?

Thanks for help

**Comment by dkleber89** [comment]
Seems we have a problem in the dev environment ... we use no https ... when we test it on staging (with https) it works as expected
