### ISSUE TITLE
Unable to get UserInfo in afterCallback

### ISSUE THREAD

**Issue by oookoook** [auth0/express-openid-connect#197]
### Describe the problem

Hello, I am migrating from v1 to v2 and I am having an issue with obtaining the user info.

The `handleCallback` function iv v1 worked as expected:

```js
handleCallback: async function (req, res, next) {
      const client = req.openid.client;
      req.appSession = req.appSession || {};
      try {
        var t = await client.userinfo(req.openidTokens);
        //console.dir(t);
        req.appSession.claims = t;
        next();
      } catch(e) {
        next(e);
      }
    }
```

However, when using `afterCallback` in v2, the call to `fetchUserInfo` fails:

```js
afterCallback: async (req, res, session, decodedState) => {
      console.log(`accessToken in afterCallback: ${JSON.stringify(req.oidc.accessToken)}`);
      const additionalUserClaims = await req.oidc.fetchUserInfo();
      return {
        ...session,
        ...additionalUserClaims
      };
}
```

The error is: 
```
OPError: invalid_token (Invalid access token: undefined)
    at throwAuthenticateErrors (/opt/spidertraits/spider-trait-database/backend/node_modules/openid-client/lib/helpers/process_response.js:18:11)
    at processResponse (/opt/spidertraits/spider-trait-database/backend/node_modules/openid-client/lib/helpers/process_response.js:41:7)
    at Client.userinfo (/opt/spidertraits/spider-trait-database/backend/node_modules/openid-client/lib/client.js:1123:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.afterCallback (/opt/spidertraits/spider-trait-database/backend/index.js:103:36)
    at async /opt/spidertraits/spider-trait-database/backend/node_modules/express-openid-connect/middleware/auth.js:113:23
```

Which is true - I have the `console.log` statement in `afterCallback` and the value is `undefined`.

However, later the `accessToken` is correctly filled in. In middleware later in the chain, I can make the call to `fetchUserInfo` with no problems and it seems I might be even able to store the claims for further use so I don't have to make the call with every request:

```js
const myMiddleware = async function (req, res, next) {
    if(!req.oidc.user || Object.keys(req.oidc.user).length == 0) {
        console.log(`Getting user info...`);
        const additionalUserClaims = await req.oidc.fetchUserInfo();
        console.log(`Additonal claims: ${JSON.stringify(additionalUserClaims)}`);
        req.oidc.user = Object.assign(req.oidc.user || {}, additionalUserClaims);
    }
}
```

However, even in this case it seems that I don't get all the claims as with v1. My authorization params look like this:

```js
authorizationParams: {
        response_type: "code",
        response_mode: "query",
        scope: "openid profile eduperson_entitlement"
    }
```

And it seems I don't get the claims from the `eduperson_entitlement` scope, just the `profile` claims.

### What was the expected behavior?

I'd expect the `afterCallback` handler and `fetchUserInfo` method the same functionality as `getUserInfo` and `handleCallback` in release 1. I suppose I am doing something wrong in v2, but I can't figure out what.

### Reproduction

Honestly, I am not sure how to replicate this, I suspect it might be related to the setup of my OIDC Identity Provider, which is not publicly available.

### Environment

- **Version of this library used:** 2.2.1
- **Which framework are you using, if applicable:** Express
- **Other modules/plugins/libraries that might be involved:** I do not know about anything that would interfere with OIDC
- **Any other relevant information you think would be useful:** The repo branches for [v1](https://github.com/oookoook/spider-trait-database/blob/v1auth/backend/index.js) and [v2](https://github.com/oookoook/spider-trait-database/blob/v2auth/backend/index.js)

Anyway, thanks for this great project!

**Comment by adamjmcgrath** [comment]
Hi @oookoook - thanks for raising this

`req.oidc.fetchUserInfo` requires a session, which you don't have in `afterCallback`, so you'll need to use a route handler after this as you've done. Or just call `${issuerBaseURL}/userinfo` yourself in `afterCallback`

> However, even in this case it seems that I don't get all the claims as with v1. My authorization params look like this:

`fetchUserInfo` (just like `client.userinfo`) wil just return the content of `${issuerBaseURL}/userinfo` - if you're getting different claims, this means that the data returned by `/userinfo` must be different, ther are not changes to v2 that would cause the differences you're describing.

**Comment by oookoook** [comment]
Hello @adamjmcgrath, thank you for clarifying this. I'll re-check the claims I am getting.

As for the modifying the `req.odic.user` by `req.oidc.user = Object.assign(req.oidc.user || {}, additionalUserClaims);` - is this OK? Can I break something with this approach?

As for the `afterCallback` code I used, it was copy-pasted from [the docs](https://auth0.github.io/express-openid-connect/interfaces/configparams.html#aftercallback) - so if this is not the way to obtain userInfo, you might want to update or clarify the docs. Or am I missing something?

Thanks for your work!

**Comment by adamjmcgrath** [comment]
Hey @oookoook 

> As for the modifying the req.odic.user by req.oidc.user = Object.assign(req.oidc.user || {}, additionalUserClaims); - is this OK? Can I break something with this approach?

I wouldn't expect that to be persisted, you would want to update `req.appSession` (or return the extra props from `afterCallback`)  - any additional properties you add to `req.appSession` will end up being persisted in the session cookie.

`req.oidc.user` is just the decoded claims of the id token, you could only update it by updating the id_token

> As for the afterCallback code I used, it was copy-pasted from the docs - so if this is not the way to obtain userInfo, you might want to update or clarify the docs. Or am I missing something?

Do'h - your're quite right. I'll update those docs. What I think I'll do is allow `fetchUserInfo` to accept an optional tokenSet so it works like it did before. So that example would become something like:

```js
  afterCallback: async (req, res, tokenSet, decodedState) => {
    const additionalUserClaims = await req.oidc.fetchUserInfo(tokenSet);
    return {
      ...tokenSet,
      additionalUserClaims
    };
  }
```

But for now, I would just fetch the userinfo yourself

```js
  afterCallback: async (req, res, tokenSet, decodedState) => {
    const additionalUserClaims = await request(`${issuerBaseURL}/userinfo`, { headers: { authorization: `Bearer: ${tokenSet.access_token}` } });
    return {
      ...tokenSet,
      additionalUserClaims
    };
  }
```

**Comment by oookoook** [comment]
Thanks for the clarification! The option to provide optional tokenSet looks great. I'll check for it in further releases. I guess this issue can be closed then. :)

**Comment by sfkpmr** [comment]
I've also gotten stuck at using fetchUserInfo, and I take it I need to use a token/session to use it, but the examples I see don't seem to do so. So I'm wondering what the current way of achieving this is.

Based on [this](https://github.com/auth0/express-openid-connect/blob/master/EXAMPLES.md#6-calling-userinfo) and [this](https://github.com/auth0/express-openid-connect/blob/master/examples/userinfo.js) I tried this without luck:

```
app.use(
    auth({
        authRequired: false,
        auth0Logout: true,
        issuerBaseURL: process.env.ISSUER_BASE_URL,
        baseURL: process.env.BASE_URL,
        clientID: process.env.CLIENT_ID,
        secret: process.env.SECRET,
        clientSecret: process.env.CLIENT_SECRET,
        idpLogout: true,
        authorizationParams: {
            response_type: 'code id_token',
        },
    })
);
```

Side note: is fetchUserInfo() the only way of getting a user's username? req.oidc.user.nickname provides something completely different.

**Comment by adamjmcgrath** [comment]
@sfkpmr - can you show me an example of how you're using `fetchUserInfo` and what response/error you get?

> Side note: is fetchUserInfo() the only way of getting a user's username? req.oidc.user.nickname provides something completely different.

How about `req.oidc.user.name`?

**Comment by sfkpmr** [comment]
> @sfkpmr - can you show me an example of how you're using `fetchUserInfo` and what response/error you get?
> 
> > Side note: is fetchUserInfo() the only way of getting a user's username? req.oidc.user.nickname provides something completely different.
> 
> How about `req.oidc.user.name`?

Thanks for replying!

Example:

```const express = require("express");
const app = express();
require("dotenv").config();
const { auth, requiresAuth } = require('express-openid-connect');
const e = require("express");

app.use(
    auth({
        authRequired: false,
        auth0Logout: true,
        issuerBaseURL: process.env.ISSUER_BASE_URL,
        baseURL: process.env.BASE_URL,
        clientID: process.env.CLIENT_ID,
        secret: process.env.SECRET
    })
);

app.get("/", requiresAuth(), async (req, res) => {
	const name = await req.oidc.user.name
	const email = await req.oidc.user.email
	res.send(name + " " + email);
});

app.get("/test", requiresAuth(), async (req, res) => {
	const data = await req.oidc.fetchUserInfo()
	res.send(data);
});

const port = process.env.PORT || 3000;
app.listen(port, () => {
    console.log(`Listening on port ${port}`);
});
```

/ works fine, but when I go to /test, I get this error:

```
(node:25096) UnhandledPromiseRejectionWarning: TypeError: access_token not present in TokenSet
    at Client.requestResource (C:\Users\sfkpmr\Desktop\test\node_modules\openid-client\lib\client.js:1034:15)
    at Client.userinfo (C:\Users\sfkpmr\Desktop\test\node_modules\openid-client\lib\client.js:1133:33)
    at RequestContext.fetchUserInfo (C:\Users\sfkpmr\Desktop\test\node_modules\express-openid-connect\lib\context.js:153:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async C:\Users\sfkpmr\Desktop\test\server.js:25:15
(Use `node --trace-warnings ...` to show where the warning was created)
(node:25096) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:25096) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by adamjmcgrath** [comment]
@sfkpmr you need to do the code flow if you want an access token:

```js
authorizationParams: {
  response_type: 'code', // or 'code id_token'
},
```
