### ISSUE TITLE
When getting jwks.json redirects are not followed.

### ISSUE THREAD

**Issue by djimenezinvysta** [auth0/express-openid-connect#203]
### Describe the problem

When getting the jwks json from the provider, the client gets redirected from http to https receiving a 303.
The client does not follow the redirect and uses the html of the redirect message as the json.

### What was the expected behavior?

I expected it to follow the redirect and get the json using https.

### Reproduction
1. Create a provider server that redirects all http request to https.
2.  Use that provider to login.
3. Callback fails because uses html as json for jwks.

### Environment

- **"express-openid-connect": "^2.1.0"d:**
- **oidc-provider node**
- **nginx**

### IS THIS A FIX?
I "fixed" this by changing the default behavior of the request.
I added 
options.followRedirect = true;
to client.js on line 35.
I am worried that this is breaking protocol. Is their a way to force https for all request?

**Comment by adamjmcgrath** [comment]
Hey @djimenezinvysta - thanks for raising this

`options.followRedirect = true` would certainly fix your issue and we could allow you to customise that in the SDK.

But first I'd like to understand why your issuer is publishing `http` urls in its discovery then redirecting them to https

Could you share your issuerBaseURL?

**Comment by adamjmcgrath** [comment]
Hey @djimenezinvysta  - it looks like you're using `oidc-provider` behind a TLS terminating reverse proxy.

You need to get oidc-provider node to trust the proxy, then it will know to return `https` urls in it's discovery:

See https://github.com/panva/node-oidc-provider/blob/v5.5.6/docs/configuration.md#trusting-tls-offloading-proxies

**Comment by djimenezinvysta** [comment]
@adamjmcgrath Thanks for pushing me in the right direction. The issue was actually with express. I did not enable trust proxy on both the provider and the client.
