### ISSUE TITLE
Exception from appSession.js after upgrade to 2.3.0

### ISSUE THREAD

**Issue by appagg** [auth0/express-openid-connect#204]
### Describe the problem
After upgrade to 2.3.0, getting exception on login and crash the app.

[2021-03-20T06:04:41.772Z] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (D:\raymond\github\heroku\joyrideclub\node_modules\express\lib\response.js:771:10)
    at ServerResponse.append (D:\raymond\github\heroku\joyrideclub\node_modules\express\lib\response.js:732:15)
    at ServerResponse.res.cookie (D:\raymond\github\heroku\joyrideclub\node_modules\express\lib\response.js:857:8)
    at setCookie (D:\raymond\github\heroku\joyrideclub\node_modules\express-openid-connect\lib\appSession.js:135:13)
    at CookieStore.set (D:\raymond\github\heroku\joyrideclub\node_modules\express-openid-connect\lib\appSession.js:150:7)
    at ServerResponse.resEnd (D:\raymond\github\heroku\joyrideclub\node_modules\express-openid-connect\lib\appSession.js:295:21)
    at ReadStream.onend (_stream_readable.js:628:10)
    at Object.onceWrapper (events.js:273:13)
    at ReadStream.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)

### What was the expected behavior?
No exception.

### Reproduction
Login to auth0

### Environment

auth0Config:
"auth0Config": { "authRequired": false, "auth0Logout": true, "secret": "...", "baseURL": "https://www.joyridesclub.com", "routes": {"postLogoutRedirect": "https://www.joyridesclub.com/loggedout"}, "clientID": "...", "issuerBaseURL": "..." }
Environment

- **Version of this library used:2.3.0**
- **Which framework are you using, if applicable: Node/Express**

**Comment by adamjmcgrath** [comment]
Hi @appagg - thanks for raising this

I'm not able to reproduce your issue with any of our example apps, do you have a minimal reproducable app you could share?

**Comment by qstearns** [comment]
I am also experiencing this issue, but only when running the application in docker after upgrading to 2.3.0. I'm working on patching the issue, but I can try to post a more isolated fix after I'm done.

**Comment by adamjmcgrath** [comment]
Thanks @qstearns! I'll see if I can repro this on Docker, let me know if you find out more

**Comment by adamjmcgrath** [comment]
I'm not able to repro running https://github.com/auth0-samples/auth0-express-webapp-sample with `2.3.0` on Docker.

@appagg or @qstearns - let me know if you find out any more steps to reproduce

**Comment by ls-joris-desmedt** [comment]
@adamjmcgrath I could easily reproduce this by using a proxy in combination with `express-openid-connect`.

```ts
import express from 'express';
import { auth } from 'express-openid-connect';
import { createProxyMiddleware } from 'http-proxy-middleware';

const app = express();

app.use(auth());
app.get('*', createProxyMiddleware({ target: 'http://localhost:3001', changeOrigin: true }));

app.listen(3000, () => {
  console.log('Server listening on port 3000 🚀');
});
```

You'll get the same error as above. Downgrading to version `2.2.0` fixes this issue.

**Comment by adamjmcgrath** [comment]
@ls-joris-desmedt @qstearns @appagg - can you try using this branch and let me know how you get on: https://github.com/auth0/express-openid-connect/tree/fix-headers-sent

You can install it directly using `npm i "auth0/express-openid-connect#fix-headers-sent"`

**Comment by ls-joris-desmedt** [comment]
@adamjmcgrath just installed that specific version and this indeed fixes the above error.

Thanks a lot!

**Comment by jigar288** [comment]
I'm having this issue as well. Thanks for posting @appagg

**Comment by jigar288** [comment]
> I'm having this issue as well. Thanks for posting @appagg

I was able to fix my isssue as well by downgrading dependency

**Comment by adamjmcgrath** [comment]
@jigar288 @appagg @qstearns - let me know if https://github.com/auth0/express-openid-connect/issues/204#issuecomment-808368954 fixes the issue for you

**Comment by dkleber89** [comment]
@adamjmcgrath i have the same issue here ... https://github.com/auth0/express-openid-connect/issues/204#issuecomment-808368954 fix the issue for me -> u can see it also in the demo app mentioned in #212
