### ISSUE TITLE
Any "clean" way to set session id prefix?

### ISSUE THREAD

**Issue by JaneJeon** [auth0/express-openid-connect#205]
Hey all, I was looking at the config options (especially the cookie options) to try to see if I can control the cookie/session IDs (or at the very least, their prefixes), but it looks like it is mostly impossible, if not impossibly convoluted: https://github.com/auth0/express-openid-connect/blob/5566d1a941fc2a1487c242204c07e5805c4913f7/lib/appSession.js#L230

The use case for this is that I'm using a redis session store (it's relevant) and trying to implement (generic) SCIM endpoints. One of them is "deleting" a user, and part of it includes invalidating their session.

The easiest way to invalidate said user's session would be to basically do a redis `DEL $sessionPrefix:$userId*` request. However, as is, this is impossible to do due to express-openid-connect's sessionid being completely opaque to the user.

Unless if there's an easier way I'm overlooking, this would most likely require an addition from the auth0 team on this library to support such feature.

Thanks

**Comment by adamjmcgrath** [comment]
Hi @JaneJeon 

Assuming you're using a [custom session store](https://auth0.github.io/express-openid-connect/interfaces/sessionconfigparams.html#store), the default [session name](https://auth0.github.io/express-openid-connect/interfaces/sessionconfigparams.html#name) and you want the id that the session has been stored at, you can do `cookie.parse(req.get('cookie')).appSession`
