### ISSUE TITLE
Insecure example in the documentation?

### ISSUE THREAD

**Issue by JaneJeon** [auth0/express-openid-connect#206]
Hi all,

I was trying to write some `afterCallback` when I noticed this in the example: https://github.com/auth0/express-openid-connect/blob/master/EXAMPLES.md#8-validate-claims-from-an-id-token-before-logging-a-user-in

It's not clear that `express-openid-connect` *verifies* the request from the IdP in the authentication lifecycle by the point the callback is called.

In the documentation, it is only noted that: "Function for custom callback handling after receiving tokens" - again, because of the wording the user can't be sure that the tokens are to be trusted or not.

If you don't know whether to trust the token or not, then the obvious thing would be to verify the JWT's signature, but on the documentation (see the first link in this issue), it only *decodes* the `id_token`, and not *verify* it.

So, my question is: can we *trust* the request that populated the `session.id_token` **AND** that `express-openid-connect` has verified that trust before `afterCallback` is called? Or can we actually NOT trust aforementioned request and, therefore, the `id_token`?

If it's the former, then it should be noted in the documentation for `afterCallback`. If not, the documentation for usage of `afterCallback` should be updated to use `JWT.verify` instead (so either way the documentation would need to be updated).

Thank you.

**Comment by adamjmcgrath** [comment]
Hi @JaneJeon - thanks fro raising this

I can confirm that the ID Token's signature is verified before the `afterCallback` hook is called. Have updated the documentation in #208 to make it more clear.
