### ISSUE TITLE
Use strict typing for user object

### ISSUE THREAD

**Issue by jigar288** [auth0/express-openid-connect#207]
### Describe the problem you'd like to have solved

Use strict typing for user object

https://github.com/auth0/express-openid-connect/blob/5566d1a941fc2a1487c242204c07e5805c4913f7/index.d.ts#L111

### Describe the ideal solution

Possibly use typescript interface similar to this:
https://github.com/auth0/express-openid-connect/blob/5566d1a941fc2a1487c242204c07e5805c4913f7/index.d.ts#L574

`export type User = {
    name: string
    email: string
    given_name: string
    family_name: string
    user_id: string
    picture: string
}`

**Comment by adamjmcgrath** [comment]
Hi @jigar288 - thanks for the suggestion, we'll add something to our backlog

**Comment by omermorad** [comment]
@adamjmcgrath added a temporary fix to it until the full interface will be added #225
