### ISSUE TITLE
Turn off PKCE with response_type code?

### ISSUE THREAD

**Issue by alphster** [auth0/express-openid-connect#211]
I *think* I need a way to turn off PKCE with response_type code. That's my analysis, but I could be wrong.

I'm able to use this lib with one of my providers successfully, using response_type code.  However, I'm using it against another provider that was custom written.  I dont see any other clients using challenges so I believe it was never implemented.  I have no control/sway to make this happen; I can only work on the client API.  I believe PKCE is relatively new and perhaps I would not have run into these issues if I have been hooking this library in the past before PKCE was introduced. 

The reason I believe this, is I keep getting "invalid_grant" after client.callback (after entering my creds and being redirected back to callback route) and my callback route throws a 400.

My suggestion:
ConfigParams should have an override to specify usePKCE: false (or something similar) even while using response_type code.

I can "fix" this by modifying /lib/middleware/auth.js, line 100
` session = await client.callback(redirectUri, callbackParams, {`
`  max_age,`
`  code_verifier, // <-- REMOVE THIS LINE`
`  nonce,`
`  state,`
` });`

I believe /lib/hooks/context.js, line 204 is crucial as well.  It says that "code" must always use PKCE.
 
`const usePKCE = options.authorizationParams.response_type.includes('code');`
`if (usePKCE) {`
`  debug(`
`    'response_type includes code, the authorization request will use PKCE'`
`  );`
`  stateValue.code_verifier = transient.generateCodeVerifier();`
`}`

Any thoughts/insights would be appreciated.  I understand that perhaps forcing certain things into place is best to keep the library as secure for users as it can be, but using this lib w/out PKCE for older implementations might still be better than trying to roll your own.  I know this is achievable by using openid-client directly, but i was hoping to avoid that and reuse the great work in this lib.  In my case, this is not a "public client" (it's an onprem express node api) and I think does not have the vulnerabilities that could be said of a mobile app.

Great library and thanks!

**Comment by adamjmcgrath** [comment]
Hi @alphster - I think making `usePKCE` configurable sounds reasonable. I don't have time to do it at the moment, but happy to look into it in the future or review a PR for it

**Comment by alphster** [comment]
Thanks, i'd be happy to provide a PR.  I'll try to work on it today or tomorrow.
Hopefully there are no concerns with allowing the option to fall back to more of a "legacy" authorization code flow by optionally disabling PKCE.

**Comment by adamjmcgrath** [comment]
Hi @alphster - I've had a chat with my team and they pointed out to me that the extra PKCE parameters should be backwards compatible. Any idp should ignore all unrecognized parameters at all endpoints, so it doesn't make sense to have a flag to disable passing the PKCE parameters.

So we would not accept a PR to make `usePKCE` configurable and I suggest you take a look at this custom written provider for a solution.

Closing this issue, feel free to ping me if you'd like to reopen this to discuss further

**Comment by alphster** [comment]
Hey Adam,

I believe the IDP does ignore the extra params which originate from the client. It will take whatever it understands, and let you peform login with creds and then redirect you back to the client.  However the client has already been configured to setup the code_verifier/code_challenge flow, and will expect to test it when we redirect back to it. After we have redirected back to the client, it will use the code_verifier to test.  client.callback() will fail if we try to pass it a code_verifier because there's nothing to verify since IDP didn't do any handling for these things, and that results in invalid_grant.

I'm still a bit green to the whole oauth flow, but this is a small bit I think I pulled from investigating the code.

**Comment by panva** [comment]
Hey Ralph, the PKCE verification happens entirely on the OP side based on the parameters passed in. If the IdP would indeed just ignore the PKCE parameters then the flow would still pass. In your case however, it is either - not processing the S256 PKCE method correctly, or being stubborn and rejecting the grant request on the basis of unknown (to it) parameters passed in. We cannot tell which one it is from our end tho and I can confirm the PKCE extension is really backwards compatible in a way that if an IdP does not support it, it is meant to ignore its parameters and it will still work, albeit - without the added benefits of PKCE.

**Comment by alphster** [comment]
Thanks for the extra detail.  I'll take a further look and let you know if I find something more concrete.
