### ISSUE TITLE
attemptSilentLogin option prompt login page on very first request of public page

### ISSUE THREAD

**Issue by dkleber89** [auth0/express-openid-connect#212]
### Describe the problem

On the very first reqest (NO Cookie set in browser) the silent login prompt the login page also on public page.

When i try again on the same Page it works as expected. After investigation i can see there is a "skipSilentLogin" cookie in browser set.

Btw. when i try the same page and have a valid sessionCookie ... silent login works perfect

``` ts
// Setup Open ID Connect
const authRequestHandler = auth({
  issuerBaseURL: process.env.IDENTITY_URL,
  baseURL: process.env.BASE_URL,
  clientID: process.env.CLIENT_ID,
  clientSecret: process.env.CLIENT_SECRET,
  secret: process.env.COOKIE_SECRET,
  authRequired: false,
  idpLogout: true,
  attemptSilentLogin: true,
  routes: {
    callback: '/signin-oidc',
    login: false,
    logout: '/logout',
    postLogoutRedirect: '/',
  },
  authorizationParams: {
    scope: 'openid email offline_access profile user.sapdata user.portal_emobility',
    response_type: 'code',
  },
  session: {
    name: cookieName,
    cookie: { domain: process.env.COOKIE_DOMAIN },
    absoluteDuration: 36000,
    rollingDuration: 1800,
  },
});
````

### What was the expected behavior?

SilentLogin should check if silent login is possible also on the very first request. 
* When possible -> Login in background
* When not possible -> Do "nothing"

### Environment

- Lib Version v2.3.0
- Express Lib 4.17.0
- Identity Server 4

**Comment by adamjmcgrath** [comment]
Hi @dkleber89 - thanks for raising this

I can't reproduce the issue you described using the following app with similar configuration:

```js
require('dotenv').config();
const express = require('express');
const app = express();
const { auth } = require('./');

app.use(
  auth({
    authRequired: false,
    idpLogout: true,
    attemptSilentLogin: true,
    routes: {
      login: false,
      logout: '/logout',
      postLogoutRedirect: '/',
    },
    authorizationParams: {
      scope:
        'openid email offline_access profile user.sapdata user.portal_emobility',
      response_type: 'code',
    },
    session: {
      absoluteDuration: 36000,
      rollingDuration: 1800,
    },
  })
);

app.get('/', (req, res) => {
  res.send(
    req.oidc.isAuthenticated()
      ? `Logged in. Welcome ${req.oidc.user.sub}! <a href="/logout">Logout?</a>`
      : 'Logged out. <a href="/login">Login?</a>'
  );
});

app.listen(3000, () => console.log('Visit http://localhost:3000'));
```

When I visit http://localhost:3000 for the first time, with no cookies, the app attempts silent login.

Could you share a small application that demoonstrates the issue?

**Comment by dkleber89** [comment]
Here i make a setup of a little demonstration application -> [Auth Test App](https://github.com/dkleber89/auth-test-app-1)

Would this help to investigate? I have exactly the same behavior as in the main app...

**Comment by adamjmcgrath** [comment]
Thanks for sharing that app @dkleber89 - will take a look and get back to you next week

**Comment by adamjmcgrath** [comment]
Hi @dkleber89 - thanks for sharing your example app. I've noticed a bug where `prompt=none` was not being passed correctly on silent login, #217 should resolve your issue.

**Comment by dkleber89** [comment]
@adamjmcgrath thanks for investigating this issue
