### ISSUE TITLE
Package have dependency for deprecated package - @hapi/joi

### ISSUE THREAD

**Issue by bartholomew-gander** [auth0/express-openid-connect#213]
### Describe the problem

express-openid-connect@2.3.0 npm package refers to deprecated packages. This causes NPM to throw warnings:

```
npm WARN deprecated @hapi/pinpoint@2.0.0: Moved to 'npm install @sideway/pinpoint'
npm WARN deprecated @hapi/formula@2.0.0: Moved to 'npm install @sideway/formula'
npm WARN deprecated @hapi/address@4.1.0: Moved to 'npm install @sideway/address'
npm WARN deprecated @hapi/joi@17.1.1: Switch to 'npm install joi'
```

### What was the expected behavior?

No warnings on NPM install :)

### Reproduction

Simply run following on new npm project

```
npm install express-openid-connect --save
```

### Environment

- express-openid-connect@2.3.0
- npm@7.8.0
- Node v14.16.0

Tested on macOS Big Sur and on GitHub actions "windows-latest". Both throw the same warning.

**Comment by adamjmcgrath** [comment]
Thanks for raising this @bartholomew-gander - will take a look at this soon
