### ISSUE TITLE
login_required exeption on silent login

### ISSUE THREAD

**Issue by dkleber89** [auth0/express-openid-connect#219]
### Describe the problem

After fixing Silent Login Bug (#212 #217) it seems to get a step forward.
But when i have no valid session the callback from the identity called in this way -> 
`... /signin-oidc?error=login_required&state=eyJ ...`

And this produce this exeption -> 
```
BadRequestError: login_required
    at C:\Projekte\auth-test-app-1\node_modules\express-openid-connect\middleware\auth.js:109:31
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

I think this exeption should not thrown when silent login happens. But is it a problem in lib or in my config?

Demonstration application -> [Auth Test App](https://github.com/dkleber89/auth-test-app-1)

### What was the expected behavior?

No exeption on silent login when no valid session is available.

### Environment

- Lib Version v2.3.1
- Express Lib 4.17.0
- Identity Server 4

**Comment by adamjmcgrath** [comment]
Hi @dkleber89 - yep I see what you mean. Let me have a think about how best to resolve this and get back to you

**Comment by dkleber89** [comment]
Hi @adamjmcgrath - did u have some news for me? ... I have a app in production with this issue that the login prompt also on public pages and i can´t update because of this one.

When it takes longer to fix this, i have to make a workaround in the meantime. Please can u give me some insights

Thanks

**Comment by adamjmcgrath** [comment]
Hi @dkleber89 - sorry for the delay, I'll try and take a look this week

**Comment by dkleber89** [comment]
@adamjmcgrath in the meantime im looking for a workaround ... and there i can see another issue but maybe this issue comes only from my workaround tryouts -> on silentlogin the returnTo url is empty or completely not send to identity so i come back with a {baseUrl}/#_=_ url ... i think there should be send the actual url of the user?

**Comment by adamjmcgrath** [comment]
Hi @dkleber89 - I've created a branch to fix the issue https://github.com/auth0/express-openid-connect/tree/swallow-error-on-silent-auth

You can install this in the meantime, let me know if it works for you and I'll create a PR

**Comment by dkleber89** [comment]
Hi @adamjmcgrath thanks ->  seems to be working in our dev environment. But at i mention before on the very first request some hashes added to our url -> {Base URL}/register#\_=\_ <- This happen only on the very first request of a public page when skipSilentLogin cookie is not set

**Comment by adamjmcgrath** [comment]
>  But at i mention before on the very first request some hashes added to our url -> {Base URL}/register#_=_ <- This happen only on the very first request of a public page when skipSilentLogin cookie is not set

Hi @dkleber89 - I'm not sure I understand the issue, could you give more details?

**Comment by dkleber89** [comment]
Hi @adamjmcgrath sorry for my english:

I try to Explain again:

1. I open a new icognito browser tab so i have no cookies or other cache stuff
2. Then i go to our public page in this case to our "myAccount" app to the register page -> {baseUrl}/register
3. then in the background the silent login tryout happens
4. after that the url in the browser looks like that -> {baseUrl}/register#\_=\_ 

Where comes this "#\_=\_" ?

**Comment by adamjmcgrath** [comment]
hey @dkleber89 - Thanks for describing the steps

Fisrt off, it looks like the login attempt is correctly returning you back to `/register`.  The SDK doesn't add a fragment to the return URL, in fact it's unlikely that any server side component would add a `#` fragment to your url. My guess is that something on your frontend is adding that fragment.

Is it possible to reproduce this using https://github.com/dkleber89/auth-test-app-1 ?

**Comment by dkleber89** [comment]
Hi @adamjmcgrath ... okay hmm at this time i cant figure it out where it comes from and i can reproduce it with the https://github.com/dkleber89/auth-test-app-1 ... i updated it

**Comment by adamjmcgrath** [comment]
Hi @dkleber89 - I can't reproduce the issue you describe using https://github.com/dkleber89/auth-test-app-1 

I follow the steps in https://github.com/auth0/express-openid-connect/issues/219#issuecomment-828949541

The app attempts silent login, which silently fails and return the user to `{baseUrl}/register` (no `#_=_`)

![image](https://user-images.githubusercontent.com/1299658/117109947-572cc080-ad7d-11eb-95df-1e62df48fb38.png)

**Comment by dkleber89** [comment]
Hmm interesting ... i look at the same place and see also the same as u here but i have this additional fragments can´t figure it out where it comes .... In the future i take some time and investigate it deeper and in the meantime its working 

 Thank you for your help
