### ISSUE TITLE
Get access token for different protected resource

### ISSUE THREAD

**Issue by salmanmanekia** [auth0/express-openid-connect#220]
Hi,

While it is possible to have accessToken for a single protected resource. I was wondering if its possible to have the access token for different API audiences. 
In our case, different teams in the organisations are managing different API resources and we would need to have a solution where it is easy to access any protected resource without the user needing to re-login. 

Thanks!

**Comment by jmussman** [comment]
Half-assed. You can't get an access token for the Management API on behalf of a user, and an access token to enroll MFA in the same application.

**Comment by mcelotti** [comment]
I managed to get multiple access tokens using multiple middlewares with paths, like `app.use("some-path", auth(authConfigForAudience));`.  I got the idea from this issue: https://github.com/auth0/express-openid-connect/issues/263
