### ISSUE TITLE
Allow a custom function for generating a session id when using a custom session store.

### ISSUE THREAD

**Issue by nholik** [auth0/express-openid-connect#227]
When using a custom session store, it would be useful to allow passing in a custom session-id generation function.  This is already a standard part of express-session options.  See https://github.com/expressjs/session#genid 

I believe this would be a rather straightforward change mainly here - https://github.com/auth0/express-openid-connect/blob/d529ea0d22f09af41d303e0141d562749cba448a/lib/appSession.js#L305 to allow falling through to genid option of the custom store if defined otherwise going to the default implementation.

I'd be happy to submit a PR for the change if this is something that is willing to be accommodated.

**Comment by adamjmcgrath** [comment]
Hi @nholik - thanks for the suggestion, makes sense - happy to look at a PR
