### ISSUE TITLE
Auth0 returns error when I am trying to login

### ISSUE THREAD

**Issue by jackmatrix75** [auth0/express-openid-connect#229]
I successfully created a new app on Auth0 but I cannot login from my node.js/expressjs app using the `BASE_URL` I provided. 

I've followed this [tutorial][1] but when it comes to the part when I request the `/login` page, my app just send me a `{"message": "Internal server error"}`.

my logs show :

    {
        "errorType": "Runtime.UnhandledPromiseRejection",
        "errorMessage": "AggregateError: Issuer.discover() failed.\n    RequestError: connect ECONNREFUSED 127.0.0.1:443\n    RequestError: connect ECONNREFUSED 127.0.0.1:443",
        "reason": {
            "errorType": "AggregateError",
            "errorMessage": "Issuer.discover() failed.\n    RequestError: connect ECONNREFUSED 127.0.0.1:443\n    RequestError: connect ECONNREFUSED 127.0.0.1:443",
            "name": "AggregateError",
            "stack": [
                "AggregateError: Issuer.discover() failed.",
                "    RequestError: connect ECONNREFUSED 127.0.0.1:443",
                "    RequestError: connect ECONNREFUSED 127.0.0.1:443",
                "    at Function.discover (/var/task/node_modules/openid-client/lib/issuer.js:265:17)",
                "    at process._tickCallback (internal/process/next_tick.js:68:7)"
            ]
        },
        "promise": {},
        "stack": [
            "Runtime.UnhandledPromiseRejection: AggregateError: Issuer.discover() failed.",
            "    RequestError: connect ECONNREFUSED 127.0.0.1:443",
            "    RequestError: connect ECONNREFUSED 127.0.0.1:443",
            "    at process.on (/var/runtime/index.js:37:15)",
            "    at process.emit (events.js:198:13)",
            "    at process.EventEmitter.emit (domain.js:448:20)",
            "    at emitPromiseRejectionWarnings (internal/process/promises.js:140:18)",
            "    at process._tickCallback (internal/process/next_tick.js:69:34)"
        ]
    }

Current config in my `app.js` :

    app.use(auth({
      authRequired: false,
      auth0Logout:true,
      issuerBaseURL: process.env.ISSUER_BASE_URL,
      baseURL: process.env.BASE_URL,
      clientID: process.env.CLIENT_ID,
      secret: process.env.SECRET,
      idpLogout: true,
    }))

My app is hosted on lambda so instead of entering `localhost:3000`,  my `BASE_URL` is my lambda function base url `https://xxxxxxx.execute-api.us-east-2.amazonaws.com/dev/`

Did I make something wrong ?

  [1]: https://www.youtube.com/watch?v=QQwo4E_B0y8

**Comment by adamjmcgrath** [comment]
Hi @jackmatrix75 - looks like this is related to #158 

Can you look at https://github.com/auth0/express-openid-connect/issues/158#issuecomment-747593688 and see if it resolves your issue?

**Comment by adamjmcgrath** [comment]
I suspect this is resolved by #158
