### ISSUE TITLE
TypeScript errors when defining custom session store

### ISSUE THREAD

**Issue by urbanhusky** [auth0/express-openid-connect#234]
I'm trying to use a custom session store, but I get TypeScript errors.

```typescript
import express from 'express';
import { auth } from 'express-openid-connect';
import session from 'express-session';
import createMemoryStore from 'memorystore';
…

const MemoryStore = createMemoryStore(session);
const app = express();
app.use(
  auth({
    // …
    session: {
      store: new MemoryStore({
        checkPeriod: 86400000,
      }),
    },
  }),
);
```

> TS2322: Type 'MemoryStore' is not assignable to type 'SessionStore'.
   Types of property 'get' are incompatible.
     Type '(sid: string, callback: (err: any, session?: SessionData | null | undefined) => void) => void' is not assignable to type '(sid: string, callback: (err: any, session?: SessionStorePayload | null | undefined) => void) => void'.
       Types of parameters 'callback' and 'callback' are incompatible.
         Types of parameters 'session' and 'session' are incompatible.
           Type 'SessionData | null | undefined' is not assignable to type 'SessionStorePayload | null | undefined'.
             Type 'SessionData' is missing the following properties from type 'SessionStorePayload': header, data

I can circumvent this error by casting `MemoryStore` to `any`, but that's not really a solution.
```typescript
store: new MemoryStore({
  checkPeriod: 86400000,
}) as any,
```

**Comment by adamjmcgrath** [comment]
Hi @urbanhusky - thanks for raising this, we'll take a look at it before the next release. 

In the meantime, please continue to use the workaround you described

**Comment by HartS** [comment]
> I can circumvent this error by casting `MemoryStore` to `any`, but that's not really a solution.

I had this same issue with PrismaSessionStore; I solved it by using a type assertion to the `SessionStore` interface from `express-openid-connect`

**Comment by htadeusiak** [comment]
I'm running into this issue too, any update?

**Comment by HartS** [comment]
I'm not involved with the project, but in case my previous comment clear, I think this is the best workaround until they have a fix (for this example, I use the PrismaSessionStore by https://github.com/kleydon/prisma-session-store):

```
import { auth, SessionStore } from 'express-openid-connect';
import { PrismaSessionStore } from '@quixo3/prisma-session-store';

const AdminSessionStore = new PrismaSessionStore(prisma, {
  ...settings
});

const OpenIdMiddleware = auth({
  authRequired: ...,
  issuerBaseURL: ...,
  baseURL: ...,
  clientID: ...,
  secret: ...,
  session: {
    store: AdminSessionStore as SessionStore,
    name: 'myoidcname',
  }
});
```

**Comment by HartS** [comment]
I'm not sure which dependency changing broke my workaround, but I do now have to use `as any` to get this to work
