### ISSUE TITLE
checkClaims causing infinite redirect

### ISSUE THREAD

**Issue by mouth147** [auth0/express-openid-connect#236]
I'm attempting to use the check claims middleware functions (claimEquals, claimIncludes, claimChecks) but the browser seems to be infinitely redirecting between my tenant and callback url when the checks end up being false. I'm running a basic example from the documentation:

```
const express = require('express');
const app = express();
const port = 8080;
const { auth, claimEquals } = require('express-openid-connect');

const config = {
    baseURL: 'https://localhost',
    clientID: '<client-id>',
    secret: 'abcdefghijk', // this is the actual secret i'm using to test
    issuerBaseURL: 'https://<actual-tenant>.auth0.com'
};
app.use(auth(config));
app.get('/', claimEquals('name', 'test'), (req, res) => {
    res.send('success');
});

app.listen(port, () => {
    console.log(`listening on port: ${port}`);
});
```

If I change the claims check to be something that will be true, I'm able to log in fine and I get the response expected. I'm running this behind a caddy reverse proxy locally:
`caddy reverse-proxy --from localhost:443 --to localhost:8080`

I've set up the application on auth0 to use the callback url `https://localhost/callback` which works when the claims check passes (if claimEquals evaluates to true). When it's false my browser infinitely redirects to this url: 
`https://<actual-tentant>.auth0.com/authorize?client_id=<client-id>&scope=openid%20profile%20email&response_type=id_token&redirect_uri=https%3A%2F%2Flocalhost%2Fcallback&response_mode=form_post&nonce=<nonce>&state=<state>`

Logs from the application: 
```
::1 - - [14/May/2021:20:54:28 +0000] "GET / HTTP/1.1" 302 704 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
::1 - - [14/May/2021:20:54:33 +0000] "POST /callback HTTP/1.1" 302 46 "https://<actual-tenant>.auth0.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
::1 - - [14/May/2021:20:54:33 +0000] "GET / HTTP/1.1" 302 704 "https://<actual-tenant>.auth0.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
::1 - - [14/May/2021:20:54:33 +0000] "POST /callback HTTP/1.1" 302 46 "https://<actual-tenant>.auth0.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
```
I suspect that I'm not logging out correctly or there's some session/cookie that needs to be cleared out if the claims check fails. That or I'm missing some additional configuration. 

Library versions are
- express: 4.17.1
- express-openid-connect: 2.4.0

**Comment by adamjmcgrath** [comment]
Hi @mouth147 - thanks for raising this.

`claimEquals('name', 'test')` is designed to redirect you to the login page if the session's id token claim does not have the `name: test` claim. The login callback page is designed to redirect you to the home page after a successful login.

So if you have a piece of middlware that redirect's you to login page from the home page all the time (as you do with `claimEquals('name', 'test')`) and you redirect to the homepage after a successful login (which you do becuase this is the default behaviour), then it is expected that you will get an infinite loop.

> I suspect that I'm not logging out correctly or there's some session/cookie that needs to be cleared out if the claims check fails. 

It sounds like you want to prevent a successful login depending on a specific claim of an ID Token. If that's the case, you should take a look at https://github.com/auth0/express-openid-connect/blob/master/EXAMPLES.md#8-validate-claims-from-an-id-token-before-logging-a-user-in which is an example of preventing login based on an `org_id` claim

**Comment by mouth147** [comment]
@adamjmcgrath That makes total sense. Thank you for the clarification.

Your assumption was right, I was trying to prevent the user from logging in and the example provided was exactly what I needed. 

Thank you!
