### ISSUE TITLE
Logout fails, cookie never gets cleared.

### ISSUE THREAD

**Issue by Pmarouga** [auth0/express-openid-connect#239]
Im trying to implement an authentication using myID. Login works like a charm, but I cant logout. The only way to logout is manually clearing the cookies. I cant implement this to my code since cookies are httponly and not accessible. What could be of great use is the fact that my issuer probably doesnt have the standard endpoint for logout. If i dont specify the one that they use, when i visit ${baseURL}/logout i get a page by them The web page you were trying to reach could not be found on our service. I know their logout page, so I add it in the authParams route:{logout:"issuer/extraPathOfIssuer"}.
When I add it i get that I cannot GET /logout which is normal since i havent created it. 
So, I'm a but lost on how to produce the experience that i need. I want when the browser is closed the cookie to be either expired or deleted, do you have any ideas, any examples I could use? I give you my standard authParams (I leave out the 4 basic ones for sec issues.)
       idpLogout: true,
	auth0Logout:true,
	routes:{
		logout:"idp/startSLO.ping"
	},
    authorizationParams: {
      response_type: "code",
      response_mode: "form_post",
      scope: "openid",

**Comment by adamjmcgrath** [comment]
Hi @Pmarouga 

If your identity provider's logout does not confirm to OpenID Connect, you can:

- set `idpLogout: false` so that the SDK does not attempt to log you out of your IDP using OpenID Connect
- set `routes: { postLogoutRedirect: 'idp/startSLO.ping' }` so that the SDK redirects you to your IDPs logout after logging out locally

**Comment by Pmarouga** [comment]
Thanks a lot, however this still doesn't give me the expected behavior. Ill be back in a couple of days since I have a feeling that my issuer can cover this topic.

**Comment by adamjmcgrath** [comment]
Hi @Pmarouga 

> Thanks a lot, however this still doesn't give me the expected behavior.

What behaviour does the config I suggested give you and what behaviour are you expecting?

**Comment by Pmarouga** [comment]
Hello again, so I have narrowed down my problem. I want to implement the logout while exiting the browser. I dont want to use a button or a specific logout way,  just clear the session-logging out when the browser exits. The behavior I get is very strange, however I understand this is due to weird events that need to be listened for in order to execute a fetch to the logout endpoint. Do you have a similar scenario were logout takes place on browser exit? Its weird because at the moment for the logout to work properly, I need to have multiple tabs, close my programs tab, then close the browser and only then do i get cleared from all cookies and properly relogin when i reopen the page. If i just close the browser i get relogged instantly when i open the page. Anyway this is not a bug or problem of the SDK, im just asking because maybe you have had a similar experience.
In order for me to logout i have a listener for beforeunload, or visibilitychange (have played with both, pretty much same output), and inside i await a fetch to my logout endpoint where keepalive:true. Doesnt work even if I fetch the logout endpoint of my issuer. I also feel it would not be nice to logout first thing when the app opens, but it might be the case. 
Thank you for your time.

**Comment by adamjmcgrath** [comment]
@Pmarouga 

> I want to implement the logout while exiting the browser. I dont want to use a button or a specific logout way, just clear the session-logging out when the browser exits.

You can set the [transient](https://auth0.github.io/express-openid-connect/interfaces/cookieconfigparams.html#transient) option, eg

```js
app.use(auth({ session: { cookies: { transient: true } } }));
```

This will set a "session cookie" ( a cookie with no expiration):

> If (expires is) unspecified, the cookie becomes a session cookie. A session finishes when the client shuts down, and session cookies will be removed.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#attributes

So the cookie should be cleared when you shut down the browser.

Unfortunately, Chrome has a feature called  "Continue where I left off" that will prevent your session cookies from being cleared, so you'll need to disable this if you're using Chrome for the session cookie to work as you want, see https://bugs.chromium.org/p/chromium/issues/detail?id=128513

**Comment by Pmarouga** [comment]
I get an error session.cookies is not allowed.

**Comment by adamjmcgrath** [comment]
Sorry, that example should read

```js
app.use(auth({ session: { cookie: { transient: true } } }));
```

Note: `cookie` rather than `cookies`

**Comment by Pmarouga** [comment]
Thanks you have been most helpful. The SDK is truly amazing.
