### ISSUE TITLE
Show unauthorized page when login callback fails or when claimCheck etc. fail?

### ISSUE THREAD

**Issue by urbanhusky** [auth0/express-openid-connect#242]
Is there a possibility to show some form of unauthorized page when validation in `afterCallback` or when `claimCheck` etc. fail due to missing/wrong claims?

**Comment by adamjmcgrath** [comment]
Hi @urbanhusky - you can throw an unauthorized error from `afterCallback` and set [errorOnRequiredAuth](https://auth0.github.io/express-openid-connect/interfaces/configparams.html#erroronrequiredauth) to `true` in the config.

Then you can catch either of those errors in your error handling to show an unauthorized page.

```js
const createError = require('http-errors');

app.use({
  errorOnRequiredAuth: true,
  afterCallback(req, res, session) {
    const claims = parseJwt(session.id_token);
    if (claims.some !== 'claim') {
      throw new createError.Unauthorized('Missing claim');
    }
  }
});

app.get('/test-auth', claimEquals('some', 'claim'), (req, res) => { res.send('authorized'); });

app.use(function (err, req, res, next) {
  if (err.status === 401) {
    res.render('unauthorized.html');
  }
})
```

* see https://stackoverflow.com/a/38552302 for `parseJwt`

This should also answer #240

**Comment by urbanhusky** [comment]
As far as I understand the documentation of `errorOnRequiredAuth` that would cause the app to no longer redirect to the auth server when the user is not logged in?

I still want users to be automatically redirected (and logged in) when they open any page/route - but only be logged in if they have some specific claims. They should be shown an unauthorized page if they don't have the necessary claims.

I may also want to further restrict access for some routes to users with additional claims.

**Comment by adamjmcgrath** [comment]
@urbanhusky - if you want different behaviour for different auth checks, you can simple write your own middlwares using the SDK's apis, eg

```js
const claimCheckA = (req, res, next) => req.user?.claimA === 'foo' ?  next() : next(new UnauthorizedError());
const claimCheckB = (req, res, next) => req.user?.claimB === 'bar' ?  next() : res.oidc.login();
```

**Comment by adamjmcgrath** [comment]
@urbanhusky - closing, feel free to ping me if you want to discuss further
