### ISSUE TITLE
Get id_token from request outside middleware (e.g.  from cookie to secure websockets etc.)

### ISSUE THREAD

**Issue by urbanhusky** [auth0/express-openid-connect#243]
Is there some way to get the id_token, or user information, claims etc., from a request that is not running through the express/auth middleware (using TypeScript)?

For example: I want to prevent websocket upgrade for users that are not authenticated (or don't have specific claims).

**Comment by adamjmcgrath** [comment]
Hey @urbanhusky - I put an example of how to implement this here https://github.com/adamjmcgrath/eoidc-testing-example/tree/ws

**Comment by urbanhusky** [comment]
> 
> 
> Hey @urbanhusky - I put an example of how to implement this here https://github.com/adamjmcgrath/eoidc-testing-example/tree/ws

Unfortunately I was unable to get that to work. I found that the callback for app.handle is never invoked.

Also, from a TypeScript perspective: `app.handle` and `res.socket` are private and _probably_ shouldn't be used.

**Comment by adamjmcgrath** [comment]
@urbanhusky - we don't have any other examples of using this SDK with websockets I'm afraid.

I'll leave this open as a possible future enhancement

**Comment by Ciunkos** [comment]
> > Hey @urbanhusky - I put an example of how to implement this here https://github.com/adamjmcgrath/eoidc-testing-example/tree/ws
> 
> Unfortunately I was unable to get that to work. I found that the callback for app.handle is never invoked.
> 
> Also, from a TypeScript perspective: `app.handle` and `res.socket` are private and _probably_ shouldn't be used.

FYI: I got it working by removing the [`res.assignSocket(socket);`](https://github.com/adamjmcgrath/eoidc-testing-example/blob/ws/index.js#L38) line - the callback is now being called 👍
