### ISSUE TITLE
Abstract away refresh tokens

### ISSUE THREAD

**Issue by richardscarrott** [auth0/express-openid-connect#246]
### Describe the problem you'd like to have solved

Correct me if I'm wrong, but my understanding is 99% of use-cases would want to be using `refresh_tokens` to ensure a logged in session isn't limited to the access_token's lifetime; short lived access tokens are a good thing.

### Describe the ideal solution

Therefore would it be useful if this middleware pushed people down the 'pit of success' and offered an abstraction for this a bit like auth0-spa-js does with `getAccessTokenSilently` e.g.

```js
app.use((req, res, next) => {
  req.oidc.getAccessToken = async (refresh = true) => {
    const token = req.oidc.accessToken;
    if (!token.isExpired() || !refresh) {
      return token;
    }
    return await token.refresh();
  };
  next();
});
```

## Alternatives and current work-arounds

The workaround is of course to manually define this in user land or explicitly make these checks at each call site.

### Additional information, if any

I'm somewhat creating this issue to ensure my understanding of oauth best practices are correct; i.e. `session !== access_token` (I've seen many many implementations conflate these two concepts).

**Comment by adamjmcgrath** [comment]
Hi @richardscarrott - thanks for raising this

We recommend you `set the validity period of your token based on the security requirements of your API` (but yes, they should be no longer than necessary) see https://auth0.com/docs/tokens/access-tokens#access-token-lifetime

Changing the default behaviour of `getAccessToken` to auto update your access tokens would be a breaking change, so you'll have to implement these few lines of code in userland for now, and [we have an example here](https://github.com/auth0/express-openid-connect/blob/master/EXAMPLES.md#5-obtaining-and-using-refresh-tokens) for you to do so.

Closing this, but I'll make sure it comes up as a discussion point when we're planning the next major release

**Comment by thomasmicro** [comment]
+1 for the feature!

To avoid a breaking change, it could be a feature that needs to be turned on manually in the config.
