### ISSUE TITLE
Mulitple OpenId providers

### ISSUE THREAD

**Issue by dasarindam** [auth0/express-openid-connect#247]
Hi Team, 
             I am looking for an option where I can authorized my api access based on multiple auth provider based of different profile.  
With some more explanation my application api can be accessed by multiple client's. Everyone has there own  OpenId setup.  So when I call the requiresAuth() method it should be able to do validation depends on which client is calling the service and redirect to their authorization login page.

TIA.

**Comment by adamjmcgrath** [comment]
Hi @dasarindam - there's no reason why you couldn't create different configurations of the SDK based on the request context, eg

```js
app.use((req, res, next) => {
  const config = getConfigByReq(req); // TODO: get user's 'openid setup'
  auth(config)(req, res, next); // TODO `auth()` makes some network requests on setup so this should be cached per setup
});
```

**Comment by dasarindam** [comment]
@adamjmcgrath Thanks. Will try this method with one client as of now.
