### ISSUE TITLE
allow configuration of oidc client timeout

### ISSUE THREAD

**Issue by jmacvey** [auth0/express-openid-connect#249]
### Describe the problem you'd like to have solved

We have an internal oidc issuer whose response time is less than performant.  To accommodate them, I'd like to be able to configure the http timeout.   If I leverage the `openid-client` package directly without using the sdk, I can do the following:

```
const { custom } = require('openid-client')

custom.setHttpOptionsDefaults({
  timeout: 10000, // set custom timeout
})
```

This doesn't work with the SDK, however, because the timeout is always overridden to 5000ms in [client.js](https://github.com/auth0/express-openid-connect/blob/master/lib/client.js#L35). 

### Describe the ideal solution

Depends.  If you want to control the interface, you could expose a `timeout` option on the `ConfigParams` object.  Otherwise the quick solution would be to just to check if the timeout if null / undefined just before you set it in  [client.js](https://github.com/auth0/express-openid-connect/blob/master/lib/client.js#L35), and let consumers override default http options using the underlying open-id client package as shown above.

## Alternatives and current work-arounds

Haven't considered alternatives.  If the above sounds like a good idea let me know and I'll submit a PR.

Thanks!

**Comment by adamjmcgrath** [comment]
> If the above sounds like a good idea let me know and I'll submit a PR.

Yep - good idea, thanks @jmacvey 

If you raise a PR can you call the config param `httpTimeout` and set it in ms
