### ISSUE TITLE
Handling Seesion Store using Redis

### ISSUE THREAD

**Issue by dasarindam** [auth0/express-openid-connect#250]
Hi Team , 
             I am trying to create a app where I thought of saving the token in the session and reuse the same in other different API call. Pls can some one said if this is the right way ? Is this implementation is the correct way ? Does session has been declared in coreect place ? TIA 
1. index.js
`openauth.init()`

2. openauth.js
```
var session = require...
const redisStrore = require('connect-redis')(session)
app.use(
auth({
session : {
    name : "SessionKey",
    store : new redisStore({client : redisClient})
}
})
```

3. partnerVerify.js
```
app.use('/verify', requireAuth(), req, res) =>{.
// all fine here.
// how do I get the SessionKey or Redis Session Key which is generated in the Redis  DB ?
}
app.use('callAPI', req,res) => {

// how to get the key and the redis data ?

}
```

**Comment by adamjmcgrath** [comment]
Hi @dasarindam 

> I am trying to create a app where I thought of saving the token in the session and reuse the same in other different API call. 

Have a look at the example [Obtaining access tokens to call external APIs](https://github.com/auth0/express-openid-connect/blob/master/EXAMPLES.md#4-obtaining-access-tokens-to-call-external-apis) and let me know if that answers your question

**Comment by dasarindam** [comment]
I have done the above solution and works fine. 
But What I am looking for is that, I am storing the session information into the RedisMemory using custom session. Later in the partnerVerify.js I want to retrieve using the redis key .  So I want to read the key from the session that has been created by the openauth.

**Comment by adamjmcgrath** [comment]
Hey @dasarindam - you can get everything you need from the session data to read user claims and access an api using the `req.oidc` api, eg

```js
app.use('callAPI', req,res) => {
  req.oidc.user; // user 
  req.oidc.accessToken; // accessToken
}
```

What do you need the Redis session key and Redis data directly for?

**Comment by dasarindam** [comment]
I need this key and the data for further API call. It looks like after some call I am loosing the accessToken. 
So once I store the key in the Redis later I can fetch the same and make a another Spring/Java call passing the Token.

**Comment by adamjmcgrath** [comment]
> I need this key and the data for further API call. It looks like after some call I am loosing the accessToken.

As long as the user is logged in (you have session data in redis), you will always be able to get the access token from the API: `req.oidc.accessToken`. If you are losing the accessToken when you believe you shouldn't be, this could be a bug, please create a small reproducable example and I can debug it for you.

**Comment by dasarindam** [comment]
OK. Thats fine for now. I will provide a sample code, so that you may be able to reproduce. 
Mean while can you tell me the how to get the value of the "SessionKey" once the user pass through the login process inside the method with requireAuth() function ?

**Comment by adamjmcgrath** [comment]
Thanks @dasarindam 

There is currently no way to get the value of "SessionKey" - but once https://github.com/auth0/express-openid-connect/pull/252 get's released (I'll try and cut a release this week) you should be able to make the "SessionKey" value predictable

**Comment by adamjmcgrath** [comment]
Custom Session Key generation is available in the latest release https://github.com/auth0/express-openid-connect/releases/tag/v2.5.0
