### ISSUE TITLE
Session cookie is not fully cleared on logout when custom properties are added

### ISSUE THREAD

**Issue by javonclarke** [auth0/express-openid-connect#254]
### Describe the problem

I'm testing setting and retrieving data from session. Here I have a basic route when visited sets some data on the session.
```typescript
app.get("/", (req, res) => {
  req.appSession.test = "this is a test"
  req.appSession.user = { dob: '2020-07-02' }

  res.send();
})
```

Here I can retrieve the session.
```typescript
app.get("/test", (req, res) => {
  console.log(req.appSession.test)

  res.send();
})
```

Here are my basic routes for login and logout using `express` router:

```typescript
router.get('/auth/login', (req, res) => {
  res.oidc.login({ returnTo: '/' })
})

router.get('/auth/logout', (req, res) => {
  res.oidc.logout({ returnTo: '/' })
})

router.get('/auth/me', (req, res) => {
  if (!req.appSession.user) return res.status(401).send()

  res.send(req.appSession.user)
})
```

The issue here is, when I logout and visit `/auth/me` I still get data back. I don't get auth data, just the data I set.
eg. 
```javascript
{ test: "this is a test", user: { dob: '2020-07-02' } }
```

The cookie gets cleared when I don't add custom properties to `appSession` but remains when I do, but with only the properties I added.

### What was the expected behavior?

I'm expecting the `appSession` to be fully cleared when I call `res.oidc.logout()` . 

### Environment

- **Version of this library used:**  v2.4.0
- **Which framework are you using, if applicable:**  express v4.17.1
- **Other modules/plugins/libraries that might be involved:**  none
- **Any other relevant information you think would be useful:**  none

**Comment by arieldf** [comment]
@javonclarke Hi! What was the cause of/solution to this? I am experiencing the same. I really hope for an answer

**Comment by javonclarke** [comment]
Sorry, I forgot to post my solution.

What I found was new properties would stay behind after logout. Most likely because it's not attempting to remove properties that are added after the fact. What I did was clear my custom properties before logging out.

**Comment by adamjmcgrath** [comment]
Hi @javonclarke 

When you logout everything in `req.appSession` is removed, see:
https://github.com/auth0/express-openid-connect/blob/master/lib/context.js#L294

After you logout you are redirected to `/` by default. Your `/` handler looks like this:

```js
app.get("/", (req, res) => {
  req.appSession.test = "this is a test"
  req.appSession.user = { dob: '2020-07-02' }

  res.send();
})
```

So it looks like you're adding those properties back to `req.appSession` after logout, which is why you are seeing them persisted in your session after logout.

**Comment by javonclarke** [comment]
@adamjmcgrath You're right. The examples do show that I'm redirecting to `/` and resetting the props. I experienced the issue with the correct configuration. I'm not using the package at the moment, but if I do encounter it again I'll revisit it.
