### ISSUE TITLE
/login performs silent auth when it is configured to be false

### ISSUE THREAD

**Issue by singhprincejeet** [auth0/express-openid-connect#260]
### Describe the problem
My goal was that when my user goes to login, they shall be asked to enter reauthenticate themself. I configured my auth object with `attemptSilentLogin` to be false. I also remapped my `login` endpoint to call login with silent param as false (`res.oidc.login({silent: false})`). Even after these two settings, users were still silently reauthenticated.

### What was the expected behavior?
Expected behavior should have been to be prompted to enter their username and password instead of being authenticated. 

### Reproduction
<details> 
<summary>My index.js: </summary>

```
const express = require('express')
const { auth, requiresAuth, attemptSilentLogin } = require('express-openid-connect');
require('dotenv').config();

const app = express()

app.use(
  auth({
    authRequired: false,
    auth0Logout: true,
    issuerBaseURL: process.env.ISSUER_BASE_URL,
    baseURL: process.env.BASE_URL,
    clientID: process.env.CLIENT_ID,
    clientSecret: process.env.CLIENT_SECRET,
    secret: process.env.SECRET,
    idpLogout: true,
    attemptSilentLogin: false,
    authorizationParams: {
      response_type: 'code',
      audience: process.env.API_AUDIENCE,
      scope: 'openid profile email offline_access',
    }
  })
);

app.get('/', attemptSilentLogin(), async (req, res) => {
  if (!req.oidc.isAuthenticated()) res.send("LoggedOut")

  const oidc = req.oidc

  let { token_type, access_token, isExpired, refresh, expires_in } = oidc.accessToken;


  if (isExpired()) {
    try {
      const { access_token, expires_in } = await refresh();
      res.send({
        "New Access Token": `${token_type} ${access_token}`,
        "Expires in": expires_in
      })
    } catch(error) {
      res.status(500).send(error)
    }
  }

  res.send({
    "Access Token": `${token_type} ${access_token}`,
    "Expires in": expires_in
  })
})

app.get('/login', (_req, res) => {
  res.oidc.login({silent: false})
})

const port = process.env.PORT || 3000
app.listen(port, () => {
  console.log(`Listening on port ${port}`)
})
```

</details>

Step 1: Authenticate myself with my username and password
Step 2: Wait for my refresh token to expire
Step 3: Go to `/login` endpoint

### Environment
Node version: 14.17.0
Express OIDC version: 2.4.0

**Comment by singhprincejeet** [comment]
My hunch is that this [call](https://github.com/auth0/express-openid-connect/blob/master/middleware/auth.js#L133) should be behind the config check. Anyways you folks will know more but I just wanted to share my idea.

**Comment by adamjmcgrath** [comment]
Hi @singhprincejeet - thanks for raising this. Couple of things:

> `app.get('/', attemptSilentLogin(), async (req, res) => {`

If you don't want the SDK to attempt silent login, you should not include the `attemptSilentLogin` middleware in your route handler

> Step 2: Wait for my refresh token to expire

Just because your RT has expired, doesn't mean you wont still have a session on your Identity Provider - if you do, it's likely that they're redirecting you straight back to your app without prompting the user to login again.

If you want to force reauthentication on your IDP, you should use `promp=login`, (with [these caveats](https://auth0.com/docs/login/max-age-reauthentication)) eg

```js
app.get('/login', (req, res) => res.oidc.login({ authorizationParams: { prompt: 'login' } }));
```

**Comment by singhprincejeet** [comment]
@adamjmcgrath Thanks for getting back to me so quickly. 

I made the changes you suggested but I am still not being prompted to login. I am being still authorised silently. Could you please have another look?

<details>
<summary> My changed index.js </summary>

```
const express = require('express')
const { auth, requiresAuth } = require('express-openid-connect');
require('dotenv').config();

const app = express()

app.use(
  auth({
    authRequired: false,
    auth0Logout: true,
    issuerBaseURL: process.env.ISSUER_BASE_URL,
    baseURL: process.env.BASE_URL,
    clientID: process.env.CLIENT_ID,
    clientSecret: process.env.CLIENT_SECRET,
    secret: process.env.SECRET,
    idpLogout: true,
    attemptSilentLogin: false,
    authorizationParams: {
      response_type: 'code',
      audience: process.env.API_AUDIENCE,
      scope: 'openid profile email offline_access',
    }
  })
);

app.get('/', async (req, res) => {
  if (!req.oidc.isAuthenticated()) res.send("LoggedOut")

  const oidc = req.oidc

  let { token_type, access_token, isExpired, refresh, expires_in } = oidc.accessToken;


  if (isExpired()) {
    try {
      const { access_token, expires_in } = await refresh();
      res.send({
        "New Access Token": `${token_type} ${access_token}`,
        "Expires in": expires_in
      })
    } catch(error) {
      res.status(500).send(error)
    }
  }

  res.send({
    "Access Token": `${token_type} ${access_token}`,
    "Expires in": expires_in
  })
})

app.get('/profile', requiresAuth(), (req, res) => {
  res.send(JSON.stringify(req.oidc.user))
})

app.get('/login', (_req, res) => {
  res.oidc.login({authorizationParams: { prompt: 'login'}})
})

const port = process.env.PORT || 3000
app.listen(port, () => {
  console.log(`Listening on port ${port}`)
})
```

</details>

**Comment by singhprincejeet** [comment]
Oh actually I figured it out, `authorizationParams: { prompt: 'login' }` were to be added in auth object and not in the oidc.login. That fixed it. 

Thanks for helping me @adamjmcgrath

**Comment by arpithparikh** [comment]
Hi @adamjmcgrath / @singhprincejeet  - can you explain how to achieve silently authenticate without redirecting to the login page?

The code appears to not be functioning correctly. Specifically, I have already logged into website A and am attempting to authenticate without having to log in again on website B.

    server.get('/', attemptSilentLogin(), (req, res) => {
      if (!req.oidc.isAuthenticated()) {
        res.sendStatus(404);
        return;
      }
      const user = JSON.stringify(req.oidc.user, null, 2);
      res.send(user);
    });

**Comment by adamjmcgrath** [comment]
@arpithparikh - both website A and website B need to visit the login page. It's "silent" because, if you already have a session on your IDP from logging in from website A, you will be immediately redirected back when trying to login from website B and the user will not be prompted for their credentials
