### ISSUE TITLE
checks.state argument is missing / state mismatch / Timeout awaiting 'request'

### ISSUE THREAD

**Issue by askurat** [auth0/express-openid-connect#262]
### Describe the problem
We are occasionally seeing some errors in our logs when our callback URL is hit:  `checks.state argument is missing`, `state mismatch`, `Timeout awaiting 'request'`. I'm not sure if the errors relate to each other or if one is causing the other to happen. It does seem like they coincide when looking at the logs. This is happening in our prod environment.

### Reproduction

Our prod auth api is deployed to a docker container and all requests are over https. 

Here is our config:
```
{
    issuerBaseURL: loginIssuerBaseUrl,
    baseURL: loginBaseUrl,
    clientID: loginClientId,
    clientSecret: loginClientSecret,
    secret: loginSessionSecret,
    authRequired: false,
    httpTimeout: 1000 * 10, // 10 seconds
    authorizationParams: {
      response_type: 'code',
      scope: loginScope,
    },
    routes: {
      callback: loginCallbackPath,
      login: false,
      logout: false,
    },
    afterCallback: async (req, res, session, decodeState) => {
      const userProfile = await getUserInfo(
        loginIssuerBaseUrl,
        session.access_token
      );
      return {
        ...session,
        userProfile, // access using `req.appSession.userProfile`
      };
    },
    session: {
      cookie: {
        domain: cookieDomain,
      },
      store: new MemoryStore({
        checkPeriod: 24 * 60 * 60 * 1000, // 24 Hours
      }),
    },
  }
```

### Environment

- **Version of this library used:** 2.5.0
- **Which framework are you using, if applicable:** NodeJs

I have looked at some of the other issues submitted: #191 #170 #173 #145 but haven't found a solution.

Would the timeouts be coming from theIDP?

**Comment by adamjmcgrath** [comment]
Hi @askurat 

> checks.state argument is missing
This is when you hit the `/callback?state=something` page without  a `state` cookie to compare with the callback state parameter. Users might hit this url from their history from time to time, if it's not happening a lot you can safely ignore it

> state mismatch
This is when you hit the `/callback?state=something` and your state cookie is `state=something-else`, see https://github.com/auth0/nextjs-auth0/issues/142 for explaination and mitigations of this error

> Timeout awaiting 'request'
This is probably when the request to `oauth_token` to do the code exchange times out, Since you've set the timeout to 10s would expect it to say `Timeout awaiting 'request' for 10000ms`. it's not related to the other errors, they would throw before trying to make this request

**Comment by adamjmcgrath** [comment]
> This is probably when the request to oauth_token to do the code exchange times out

Or it could be your request to `getUserInfo` - what's the timeout on that?

**Comment by askurat** [comment]
@adamjmcgrath Thanks for the quick reply

> checks.state argument is missing

Not sure what would be considered a lot. This site gets pretty heavy traffic and my logs show about 20 of these errors over a 24 hour period.

> state mismatch

Thanks for that [auth0/nextjs-auth0/issues/142](https://github.com/auth0/nextjs-auth0/issues/142).  I was actually in the process of implementing something like that.

> Timeout awaiting 'request'

It does seem to come from the `oath_token` request. Here is the stack trace:
```
BadRequestError: Timeout awaiting 'request' for 10000ms
    at /node_modules/express-openid-connect/middleware/auth.js:120:31
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
I'm not sure what the timeout would be for the `getUserInfo`. I am just calling the `userinfo` endpoint and returning the user.

If it is timing out on either the token or userInfo enpoint, would that be an issue with my IDP?

**Comment by adamjmcgrath** [comment]
Hey @askurat 

> Not sure what would be considered a lot. This site gets pretty heavy traffic and my logs show about 20 of these errors over a 24 hour period.

You could have a look at the referrer/user-agent, maybe `/callback` is getting indexed somehow? 20 requests to a random endpoint a day doesn't seem like a lot, but there may be some reason why that page is getting hit outside of the auth flow.

> If it is timing out on either the token or userInfo enpoint, would that be an issue with my IDP?

Yep - it could only mean that one of those endpoints (probably `oauth/token` given the log message) is taking >10s to respond

**Comment by askurat** [comment]
Thanks @adamauth.

I did have another question. How is `req.oidc.isAuthenticated` determined? It seems like I am always authenticated. Is there an expiration?

**Comment by adamjmcgrath** [comment]
@askurat 

> How is req.oidc.isAuthenticated determined? It seems like I am always authenticated. Is there an expiration?

`req.oidc.isAuthenticated` is determined by the existence of a valid session cookie, who's expiry is determined by the [absoluteDuration](https://auth0.github.io/express-openid-connect/interfaces/sessionconfigparams.html#absoluteduration) (default 7 days) and [rollingDuration](https://auth0.github.io/express-openid-connect/interfaces/sessionconfigparams.html#rollingduration) (default 24hrs) config options

**Comment by adamjmcgrath** [comment]
Hi @askurat - think that answers your question. Feel free to ping me if you'd like to reopen this
