### ISSUE TITLE
Multiple middleware instances

### ISSUE THREAD

**Issue by renarsvilnis** [auth0/express-openid-connect#263]
### Describe the problem you'd like to have solved

Need away to have multiple instances of the middleware.
I need to have 2 separate "logins" for admins and regulate users that both use the same SSO server, but have different client id's/secrets. Currently, the middleware extends `req` and `res` with `req.oidc, ..` that would be overridden if used side-by-side.

### Describe the ideal solution

Have multiple auth instances by having the ability to "customize" the names of the properties it extends e.g. have `req.oidcAdmin` or `req[Symbol.for('oidcAdmin')]`. 

Would imagine it would add a lot of complexity to code as they currently just check for the existence of `req.oidc`, having it configurable would require it to have the custom keys passed deeply into as config and have middlewares created from a factory function. And to avoid breaking changes the exported middlewares can be generated by the same factory function just passing it `oidc`.

**Comment by adamjmcgrath** [comment]
Hi @renarsvilnis - thanks for raising this

We don't currently support having 2 instances of the middleware on the same routes. Am assuming you can't scope the middlwares to differnt path prefixes?

```js
app.use(auth({ ...config }).unless('/admin'));
app.use('/admin', auth({ ...adminConfig, session: { name: 'appSessionAdmin' } }));
```

**Comment by renarsvilnis** [comment]
@adamjmcgrath unfortunately, no, they both end up in the same GraphQL apollo route where I then manage access to each query/mutation individually depending on "user type" and his permissions.

**Comment by adamjmcgrath** [comment]
@renarsvilnis - it sounds reasonable, it would be tricky to implement though (see [this code](https://github.com/auth0/express-openid-connect/blob/master/middleware/attemptSilentLogin.js#L24-L30) for example)

Happy to look at a PR with the understanding that you may have to fork if we don't like the implementation

**Comment by adamjmcgrath** [comment]
Also, normally we would recommend regular user / admin type roles would be handled by scopes/permissions on the same client

**Comment by renarsvilnis** [comment]
Ok, will try to do it in the next weeks.

@adamjmcgrapth why would it be tricky to implement it there?

```javascript
const resumeSilentLogin = (req, res) => {
  const {
    config: {
      session: {
        cookie: { domain, path },
      },
    },
  } = weakRef(req.oidc);
  res.clearCookie(COOKIE_NAME, {
    httpOnly: true,
    domain,
    path,
  });
};
```

would turn into a function that is created with passed in props. Then rinse and repeat for functions where it's used.

```javascript
const resumeSilentLogin = (clientConfig) => (req, res) => {
  const {
    config: {
      session: {
        cookie: { domain, path },
      },
    },
  } = weakRef(req[clientConfig.reqKeyOrAnotherYetToBeDeterminedName]);
  res.clearCookie(COOKIE_NAME, {
    httpOnly: true,
    domain,
    path,
  });
};

**Comment by adamjmcgrath** [comment]
@renarsvilnis - `config` in that example is the client config. So in order to get `reqKeyOrAnotherYetToBeDeterminedName` you'd need to know where on the request to look up `config`

**Comment by adamjmcgrath** [comment]
Closing due to innactivity - will keep on eye on the multiple SDK instances use case
