### ISSUE TITLE
Getting header issue when using Authorization header to pass the access token

### ISSUE THREAD

**Issue by purejgleason** [auth0/express-openid-connect#278]
### Describe the problem

When I try calling a protected endpoint using the Authorization header I get an error

### What was the expected behavior?

I should be able to access the resource

### Reproduction

1. Protect an endpoint using the JWT Protection...

        const jwtConfig = {
          authRequired: false,
          auth0Logout: true,
          baseURL: process.env.AUTH0_BASE_URL || "http://localhost:3000",
          secret: process.env.AUTH0_SECRET || "a long, randomly-generated string stored in env",
          clientID: process.env.AUTH0_CLIENT,
          issuerBaseURL: process.env.AUTH0_ISSUER_BASE_URL,
        };
        app.use(auth(jwtConfig));
        router.use(oid.requiresAuth());

2. Try to call the endpoint using something like postman. Make sure to use the Authorization header like `Authorization: Bearer <ACCESS_TOKEN>'

3. It throws the following error...

```
nodejs           | Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
nodejs           |     at ServerResponse.setHeader (_http_outgoing.js:561:11)
nodejs           |     at ServerResponse.header (/home/node/app/node_modules/express/lib/response.js:771:10)
nodejs           |     at ServerResponse.append (/home/node/app/node_modules/express/lib/response.js:732:15)
nodejs           |     at ServerResponse.res.cookie (/home/node/app/node_modules/express/lib/response.js:857:8)
nodejs           |     at TransientCookieHandler.store (/home/node/app/node_modules/express-openid-connect/lib/transientHandler.js:105:11)
nodejs           |     at ResponseContext.login (/home/node/app/node_modules/express-openid-connect/lib/context.js:258:17)
nodejs           |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

I think it might be related to not having an appSession token but I am not sure what to put in there. Is it just the id_token?

### Environment

- **Version of this library used:** latest
- **Which framework are you using, if applicable:** express
- **Other modules/plugins/libraries that might be involved:** Auth0
- **Any other relevant information you think would be useful:**

**Comment by thomasmicro** [comment]
It seems like you need https://github.com/auth0/express-oauth2-bearer for this purpose. I had the same problem and I would love to use the same library for the login-process AND for the backend-stuff, but sadly that doesn't look possible currently.

God bless :)

**Comment by adamjmcgrath** [comment]
@purejgleason - can you share a minimal running application that demonstrates the issue?

@thomasmicro - yes, we have separate SDKs for protecting Web Applications and APIs

**Comment by purejgleason** [comment]
@thomasmicro I am trying to use that but I can't get it working with a regular web app and I am not sure how to assign an API to one. I tried giving the permissions and using that audience but I still get unauthorized. But basically that is what I am reading too. How do people test their applications without having both? If you need both and this is a common issue I am surprised there are not more docs.

@adamjmcgrath I think you can close because I think the original issue was a promise not being returned properly on my side. But if you can help with the question part that would be awesome.

**Comment by adamjmcgrath** [comment]
@purejgleason - you should use an Access Token to access APIs - have a look at this example https://github.com/auth0/express-openid-connect/blob/master/EXAMPLES.md#4-obtaining-access-tokens-to-call-external-apis

**Comment by purejgleason** [comment]
@adamjmcgrath Rt I have the access_token, I set in in the header like `Authorization: Bearer <Token>` but all i get is unauthorized

**Comment by purejgleason** [comment]
For audience I am using a regular web app (This is just needed to test the endpoints) and I have the default audience set to give the app permissions. But I still get the unauthorized. I have tried both passport and these libs and I seem to get the same thing

**Comment by purejgleason** [comment]
@adamjmcgrath I notice when I add the audience to the oauth/token call the access code is a lot longer. Could that be the issue I wasn't getting the right token?

**Comment by adamjmcgrath** [comment]
You need a JWT access token (the big one) to access an API protected with `express-oauth2-bearer` (if you're using the default configuration)

Happy to help you debug if you can provide a full working example

**Comment by purejgleason** [comment]
@adamjmcgrath Thank you I will put something together soon.
