### ISSUE TITLE
Allow setting the User-Agent header

### ISSUE THREAD

**Issue by barryhagan** [auth0/express-openid-connect#295]
### Describe the problem you'd like to have solved

It is not possible to change the 'User-Agent' header that will be used when sending requests to an OIDC provider, e.g. when using the discover endpoint: (`.well-known/openid-configuration`).

Attempts to set this directly using the customizations for the underlying oidc-client library are overwritten by this library due to the behavior of `applyHttpOptionsCustom` and `defaultHttpOptions`.
https://github.com/auth0/express-openid-connect/blob/master/lib/client.js#L26

### Describe the ideal solution

Add a config parameter to optionally set the User-Agent header similar to what is available for `httpTimeout`. 

## Alternatives and current work-arounds

monkey patching or forking.

**Comment by adamjmcgrath** [comment]
Thanks for raising this @barryhagan 

Do you have a use case for this to help us prioritise it?

**Comment by barryhagan** [comment]
I was trying to use this with AWS bot control turned on: https://aws.amazon.com/waf/features/bot-control/

Their default ruleset will block traffic from non-browser user agents.   So I need to add an exclusion rule and would prefer to allow a custom user-agent string rather than allowing anything running `express-openid-connect/*`.

Alternatively if I didn't want to make firewall adjustments, I suppose I could also masquerade as a browser if I could set the user-agent in this library.
