### ISSUE TITLE
Handling errors thrown in callback

### ISSUE THREAD

**Issue by danielwong2268** [auth0/express-openid-connect#301]
### Describe the problem you'd like to have solved

Sometimes login fails with an error `access_denied` - for example when the user logs in with a social provider, but is not part of an organization. This redirects back to `/callback` with the parameters `?error=access_denied&error_description=user%20google-oauth2%12345%20is%20not%20part%20of%20the%20org_gSR39dK3yeqqqsMj%20organization`. I would like to surface some basic UX to the user, but am unsure what the best way is of doing this.

It looks like the error is thrown [here](https://github.com/auth0/express-openid-connect/blob/f718cc404c2f4a6fe20234c9296f8979f9750c77/middleware/auth.js#L120). From what I can tell, it's a generic `BadRequestError`.

I thought I could hook into `afterCallback` and maybe doing something there, but that's not called if an error is thrown above.

### Describe the ideal solution

Ultimately I need to surface some error to the user when something like this happens. Maybe provide a way to redirect to a configurable URL in the case of an error? Or provide a callback to handle the error.

## Alternatives and current work-arounds

Catch the exception above, parse the error message. Not great.

**Comment by adamjmcgrath** [comment]
Thanks for raising this @danielwong2268 - will add something to our backlog

**Comment by alexopenkowski-the-nu-company** [comment]
Thanks for looking into this @adamjmcgrath! However, I think #328 helps only a bit. It's still difficult to handle the error and, for example, redirect users to some specific URL. @danielwong2268 already described an ideal solution above:

> Ultimately I need to surface some error to the user when something like this happens. Maybe provide a way to redirect to a configurable URL in the case of an error? Or provide a callback to handle the error.

Maybe I also misunderstood something. Can you please explain how to achieve something like this now?

**Comment by danielwong2268** [comment]
@alexopenkowski-the-nu-company 

FWIW this is what I'm doing now

```
  const errorHandler: ErrorRequestHandler = (error, req, res, next) => {
    if (req.path === '/api/auth/businesses/callback') {
      // handle error here
    } else {
      next(error)
    }
  })
  app.use(errorHandler)
```

**Comment by alexopenkowski-the-nu-company** [comment]
Thanks for getting back at this, @danielwong2268! I think I will have to do the error handling like this then as well for the moment. 

@adamjmcgrath, any chance to add some better error handling for such cases to express-openid-connect?
