### ISSUE TITLE
Change the client_id depending on the URL

### ISSUE THREAD

**Issue by peveuve** [auth0/express-openid-connect#303]
### Describe the problem you'd like to have solved

My application has to identify users from different realms, managed in different authentication providers.
We want to configure one client per realm.
The application is accessed with different domain names, one for each realm.
Is there a way to change the client_id in the authorization request depending on the request hostname?

### Describe the ideal solution

I am not sure but something like that:
Create a custom middleware which would use ResponseContext.login(), would access the request and would be configured to select the proper client_id based on the hostname.

**Comment by peveuve** [comment]
Thanks, that's a better solution than my custom middleware!
One thing to do is also to set the client's secret in the middleware config, it is used to authenticate the client when getting the user's token (if you use client_secret_post or client_secret_basic for clientAuthMethod).

**Comment by adamjmcgrath** [comment]
no problem @peveuve
