### ISSUE TITLE
requiresAuth() not responding

### ISSUE THREAD

**Issue by momofarm** [auth0/express-openid-connect#311]
> Provide a clear and concise description of the issue
I called requireAuth() in middleware(expressjs) and not responding

package.json
```json
{
  "name": "server",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node ./bin/www"
  },
  "dependencies": {
    "cookie-parser": "~1.4.4",
    "debug": "~2.6.9",
    "dotenv": "^11.0.0",
    "express": "~4.16.1",
    "express-openid-connect": "^2.5.2",
    "http-errors": "~1.6.3",
    "jade": "~1.11.0",
    "mongodb": "^4.1.2",
    "morgan": "~1.9.1",
    "passport": "^0.5.2",
    "passport-google-oauth": "^2.0.0",
    "pug": "^3.0.2",
    "socket.io": "^4.2.0",
    "sqlite3": "^5.0.2"
  }
}
```

code:
app.js
```js
app.use(
  auth({
    authRequired: false,
  })
);

// requiresAuth checks authentication.
app.get('/admin', requiresAuth(), (req, res) =>
  res.send(`Hello ${req.oidc.user.sub}, this is the admin section.`)
);
```

### What was the expected behavior?
Get a picture tell me that I need to auth

I'm wondering if there is anyone still working on this project?

**Comment by momofarm** [comment]
some log i get from debug sesssion:
 express-openid-connect:requiresAuth authentication requirements not met with errorOnRequiredAuth() returning false, calling res.oidc.login() +2m
  express-openid-connect:context req.oidc.login() without returnTo, using: /admin +2m
  express-openid-connect:getLoginState adding default state { returnTo: '/admin' } +2m
  express:router logger  : /admin +12ms
  express:router jsonParser  : /admin +2ms
  express:router urlencodedParser  : /admin +2ms

**Comment by momofarm** [comment]
after having the error handler work correctly, the messages became:
express-openid-connect:appSession session was deleted or is empty, clearing all matching session cookies +128ms

TypeError: option sameSite is invalid
    at Object.serialize (C:\newsprog\Newprogress\node_modules\express\node_modules\cookie\index.js:174:15)
    at ServerResponse.res.cookie (C:\newsprog\Newprogress\node_modules\express\lib\response.js:853:36)
    at TransientCookieHandler.store (C:\newsprog\Newprogress\node_modules\express-openid-connect\lib\transientHandler.js:105:11)
    at ResponseContext.login (C:\newsprog\Newprogress\node_modules\express-openid-connect\lib\context.js:258:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
 I believe its related to https://community.auth0.com/t/option-samesite-is-invalid-auth0-express-quickstart/64691/4

**Comment by adamjmcgrath** [comment]
Hi @momofarm - thanks for raising this

I'm not able to reproduce your issue with the code you've shared, can you provide a full example that demonstrates the issue?

> I'm wondering if there is anyone still working on this project?

Yes, this project is actively maintained (we published a [new release](https://github.com/auth0/express-openid-connect/releases/tag/v2.5.2) 1 month ago)

**Comment by adamjmcgrath** [comment]
>    "express": "~4.16.1",

Also, the version of `express` you are using is over 2 years old, which means it might not be handling the `SameSite=None` cookie - could you try updating to the latest version of `express`?

**Comment by momofarm** [comment]
it works
