### ISSUE TITLE
auth.js : Most middleware (like urlencoded) is no longer bundled with Express and must be installed separately

### ISSUE THREAD

**Issue by ekimRA** [auth0/express-openid-connect#313]
### Describe the problem you'd like to have solved

I am getting this error when I use auth.
`Error: Most middleware (like urlencoded) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.
    at Function.get (/Users/{---}/node_modules/express/lib/express.js:99:13)
    at auth (/Users/{---}/node_modules/express-openid-connect/middleware/auth.js:46:30)`

It seems auth.js using urlencoded from express.
router.get(path, express.urlencoded({ extended: false }), (req, res) =>

### Describe the ideal solution

install body-parser and use it. https://github.com/auth0/express-openid-connect/blob/master/middleware/auth.js

**Comment by adamjmcgrath** [comment]
Hi @ekimRA - could you tell me which version of express you are using?

**Comment by ekimRA** [comment]
> 
express --version 
4.16.1
node -v
v12.22.1
npm -v
6.14.12

**Comment by adamjmcgrath** [comment]
Thanks for the info @ekimRA 

This SDK [requires express >= 4.17.0](https://github.com/auth0/express-openid-connect/blob/master/package.json#L69).

`body-parser` was added back to express in `6.14`

> The express.json() and express.urlencoded() middleware have been added to provide request body parsing support out-of-the-box. This uses the expressjs/body-parser module module underneath, so apps that are currently requiring the module separately can switch to the built-in parsers.
https://expressjs.com/en/changelog/4x.html#4.16.0
