### ISSUE TITLE
Client secret required in a PKCE flow

### ISSUE THREAD

**Issue by klikstermkd** [auth0/express-openid-connect#324]
### Describe the problem

When I want to request an access token to be returned upon login, I need to set `response_type: "code"`. In this case, [PKCE will be used](https://github.com/auth0/express-openid-connect/blob/c2557569e62b6136b249aa6b6fce41252af7dc5c/lib/context.js#L216) to perform the authorization request.

PKCE does not require passing the client secret, as explained [here](https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow-with-proof-key-for-code-exchange-pkce) and also not required when calling the `/oauth/token` [endpoint](https://auth0.com/docs/api/authentication#authorization-code-flow-with-pkce45). Instead of a client secret, it uses a code challenge and a code verifier.

But even though PKCE is used, if I set `response_type: "code"` it will [require](https://github.com/auth0/express-openid-connect/blob/c2557569e62b6136b249aa6b6fce41252af7dc5c/test/config.tests.js#L427) to also set a client secret.

My question is, what is the client secret used for in a PKCE flow? The `/oauth/token` endpoint will not use it for sure. Is this a bug or it's there intentionally? I could not find anything in the documentation where this is explained. It would be great if I can get an answer to this mystery 🙂

**Comment by adamjmcgrath** [comment]
Hi @klikstermkd - Thanks for raising this

>PKCE does not require passing the client secret, as explained [here](https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow-with-proof-key-for-code-exchange-pkce)

The link you've shared is for public clients (SPAs and native apps), this SDK is for confidential clients.

Confidential clients must authenticate with their issued credentials (in this case a Client Secret) - PKCE in this case is just an additional layer of security, for CSRF.

> The authorization server MUST require client authentication for confidential clients or for any client that was issued client credentials (or with other authentication requirements),
https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.3

**Comment by klikstermkd** [comment]
> Hi @klikstermkd - Thanks for raising this
> 
> > PKCE does not require passing the client secret, as explained [here](https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow-with-proof-key-for-code-exchange-pkce)
> 
> The link you've shared is for public clients (SPAs and native apps), this SDK is for confidential clients.
> 
> Confidential clients must authenticate with their issued credentials (in this case a Client Secret) - PKCE in this case is just an additional layer of security, for CSRF.
> 
> > The authorization server MUST require client authentication for confidential clients or for any client that was issued client credentials (or with other authentication requirements),
> > https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.3

Hi @adamjmcgrath. That makes a lot of sense actually, thanks for clarification!
