### ISSUE TITLE
Interoperability with express-session

### ISSUE THREAD

**Issue by nponeccop** [auth0/express-openid-connect#332]
### Describe the problem you'd like to have solved

I have a legacy app which passes Express session cookies over non-HTTP connections (think websockets or backend message queues). The app used `everyauth` which has been unmaintained for many years now. So I needed to use another social login library/service. But `express-openid-connect` didn't work for me because while it could use Express session stores, it doesn't use Express session cryptography or Express session cookie format, but instead implements its own `apiSession.js` session library, with JOSE/HKDF crypto instead of simple HMAC in `express-session`, symbols to avoid `req` pollution and so on.

### Describe the ideal solution

- implement an `express-session` compatibility mode where the existing Express infrastructure around sessions is used
- Extract `appSession.js` into a separate library/middleware which is used on its own as an alternative to `express-session` if someone wants a better cryptography or more features

## Alternatives and current work-arounds

- hack/fork `express-openid-connect` to use `express-session` and/or avoid extensive monkey-patching
- use `@okta/oidc-middleware` with Auth0

**Comment by adamjmcgrath** [comment]
Hi @nponeccop - thanks for raising this

It would require a considerable refactor to make this SDK compatible with `express-session` and we believe that the built in app session is sufficient.

Could you tell me more about what specifically is stopping you from using the built in session.

>  with JOSE/HKDF crypto instead of simple HMAC in express-session

Why is this an issue for you, and how does it prevent you from using the SDK?

> symbols to avoid req pollution and so on.

Which properties are we adding to `req` that `express-session` is avoiding using Symbols?

**Comment by adamjmcgrath** [comment]
Closing due to innactivity
