### ISSUE TITLE
No main module exports on requiresAuth 

### ISSUE THREAD

**Issue by rjcpereira** [auth0/express-openid-connect#337]
I'm using Nuxt 3, the `auth` property can be accessed `import { auth } from 'express-openid-connect';`, but if I try to import `requiresAuth` method, it's not found.
Also `import openId from 'express-openid-connect` and `openId.requiresAuth`.
I think it's because there is no `module.exports = ...` in middleware/requiresAuth.js

**Comment by adamjmcgrath** [comment]
Hi @rjcpereira 

The following works for me in the nuxt3 sample app:

```bash
$ npx nuxi init nuxt3-app
$ cd nuxt3-app
$ npm i
$ npm i express-openid-connect
$ echo """import pkg from 'express-openid-connect';
const { requiresAuth } = pkg;

export default (req, res) => {
  console.log(requiresAuth);
  return 'Hello World';
};
""" > server/api/foo.js
$ npm run dev
```

Visit `http://localhost:3000/api/foo`

```
✔ Nitro built in 36 ms
✔ Vite server built in 33ms
✔ Nitro built in 30 ms
✔ Vite server built in 31ms
[Function: requiresAuth] <=== requiresAuth function is found
```

**Comment by adamjmcgrath** [comment]
Closing due to innactivity
