### ISSUE TITLE
Bad Request: checks.state argument is missing 

### ISSUE THREAD

**Issue by nheyland** [auth0/express-openid-connect#341]
### Describe the problem
After writing a very simple app, like this: 

```
app.use(
  auth({
    issuerBaseURL: process.env.ISSUER_BASE_URL,
    baseURL: process.env.BASE_URL,
    clientID: process.env.CLIENT_ID,
    secret: process.env.SECRET,
    idpLogout: true
  })
);

app.get("/", (req, res) => {
    res.send(req.oidc.isAuthenticated() ? "logged in" : "logged out");
});

```
I am immediately getting this message
```
BadRequestError: checks.state argument is missing
    at /Users/m1/dev/paperTours/test/aut/node_modules/express-openid-connect/middleware/auth.js:121:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

My allowed callback url is http://localhost:3000/callback
and my allowed logout url is http://localhost:3000

Ive tried this with and without caddy to handle the https issue

Ive tried on Chrome and Safari 

I have no clue what to do now and I haven't seen anything recently reported on this issue.

**Comment by adamjmcgrath** [comment]
Hi @nheyland - thanks for raising this

I can't see anything wrong with the code you've shared.

Take a look at https://github.com/auth0/express-openid-connect/issues/145#issuecomment-707024770 and https://github.com/auth0/express-openid-connect/issues/267#issuecomment-902715653 for an explanation of the error and some tips on debugging.

**Comment by adamjmcgrath** [comment]
Closing - feel free to ping me if you want to reopen
