### ISSUE TITLE
SDK does not use hashing for nonce

### ISSUE THREAD

**Issue by madaster97** [auth0/express-openid-connect#353]
This SDK doesn't follow the `nonce` handling guidance from [OIDC Core 1.0](https://openid.net/specs/openid-connect-core-1_0.html#NonceNotes):
> The nonce parameter value needs to include per-session state and be unguessable to attackers. One method to achieve this for Web Server Clients is to store a cryptographically random value as an HttpOnly session cookie and use a **cryptographic hash** of the value as the nonce parameter. In that case, the nonce in the returned ID Token is compared to the hash of the session cookie to detect ID Token replay by third parties.

Instead, this SDK uses the same `nonce` value in both the authorization request and the id token verification check.

Here's where this SDK specifically grabs the `nonce` value from the auth cookie and later passes it as a check without hashing: 
https://github.com/auth0/express-openid-connect/blob/65bd19eeac63e00e9a5b76973a0a15ecbe2623af/middleware/auth.js#L97-L119

Something I found that backs this up, there are unit tests where this SDK checks the nonce request parameter (should be hashing instead):
https://github.com/auth0/express-openid-connect/blob/2f427f4ab4a3929436d2a16045add5f14a4a5aa5/test/login.tests.js#L101

How I've thought about this is that, anytime you see `nonce` in the spec, replace it with `nonce_challenge` (Similar to PKCE's `code_challenge`). What this SDK needs to store in the auth cookie is effectively a `nonce_verifier`, which isn't explicitly defined in the spec but is alluded to in the implementer notes above.

Without this in place, the `nonce` verification does little more than the `state` parameter can.

**Comment by madaster97** [comment]
Thought about this more, and I realized guidance I specifically linked to was for front-end JavaScript applications. I'm still partial to adding hashing, at least to make the use of nonce as secure as PKCE.

**Comment by adamjmcgrath** [comment]
Hi @madaster97 - thanks for raising this

While we don't use that specific implementation, we do mitigate against replay attacks by signing the nonce cookie and verifiying the signature when we retrieve it. See the code here https://github.com/auth0/express-openid-connect/blob/master/lib/transientHandler.js#L37-L41 - if the signature verification fails, the `nonce` value will not be retrieved and the nonce check will fail.

If you look at the test you shared `fetchFromAuthCookie` is ignoring the signature check for the sake of the test (see https://github.com/auth0/express-openid-connect/blob/2f427f4ab4a3929436d2a16045add5f14a4a5aa5/test/login.tests.js#L36)

**Comment by madaster97** [comment]
Thanks for pointing that out @adamjmcgrath, sounds good to me and closing this
