### ISSUE TITLE
Enable BaseURL to support subdomains as well as main domain

### ISSUE THREAD

**Issue by asyrialaK** [auth0/express-openid-connect#358]
### Describe the problem you'd like to have solved
My base url is `portal.mywebapp.com`, but I'd like to also be able to use the alias of `portal.eu.mywebapp.com` . Using `portal.eu.mywebapp.com` redirects back to `portal.mywebapp.com`

I have a traditional webapp (eg. portal.mywebapp.com)
We are using express-openid-connect
For debugging purposes, we have urls to hit different clusters directly (e.g portal.eu.mywebapp.com, portal.us.mywebapp.com)
When I try to use those, express-openid-connect causes a reauth, then callback, then a redirect to the baseURL of portal.mywebapp.com
I would like the ability to stay on the new subdomain.

### Describe the ideal solution
1. Allow express-open-id-connect to identify subdomains, and returnTo them
2. Allow us to update the baseDomain for a user based on the request url

## Alternatives and current work-arounds
Im not sure of any workarounds.

**Comment by adamjmcgrath** [comment]
Hi @asyrialaK - thanks for raising this

You can specify the `returnTo` in the `login` method (see https://auth0.github.io/express-openid-connect/interfaces/loginoptions.html#returnto)

So you can set it to to something per user based on the request url by doing the following:

```js
app.get('/login', (req, res) => {
  const returnTo = ... something per user base on req ...
  res.oidc.login({ returnTo })
});
```

You'll also need to set the [Cookie Domain](https://auth0.github.io/express-openid-connect/interfaces/cookieconfigparams.html#domain) to the naked domain (`mywebapp.com`), so the session cookie established in your redirect uri (`portal.mywebapp.com`) can be picked up by the url your user is returned to (`portal.eu.mywebapp.com`)

**Comment by asyrialaK** [comment]
Thanks! I'll try this out!

**Comment by adamjmcgrath** [comment]
@asyrialaK - closing, feel free to ping me if you have any issues with that advice

**Comment by asyrialaK** [comment]
> @asyrialaK - closing, feel free to ping me if you have any issues with that advice
@adamjmcgrath  How do you set the Cookie Domain? Im not seeing how I feed that to `auth(...)` when im setting up my middleware

**Comment by asyrialaK** [comment]
Ahh...nevermind. it's set through session domain

```
auth({
    session: ({
      domain: 'here'
    }),
```
