### ISSUE TITLE
sample app: response_type: code = 400 access_denied

### ISSUE THREAD

**Issue by bitsofinfo** [auth0/express-openid-connect#363]
### Describe the problem

1. I have a regular web application in auth0
2. I downloaded the sample app, and it works out of the box fine
3. My app needs to get an accessToken so I followed the directions about `response_type: code` in the `auth` config (below)
4. Now after successful login, and consent the redirect fails at `/callback` with a 400 and `access_denied`
5. auth0 logs show a `Failed Exchange` error of `Unauthorized`
6. the app's token endpoint auth method is POST

I'm not sure what to do here or what the issue is.

```
const config = {
  authRequired: false,
  auth0Logout: true,
  clientSecret: process.env.SECRET,
  authorizationParams: {
    response_type: 'code',
    scope: 'openid profile email read:whatever',
    audience: 'https://my-email-test-service',
    prompt: 'consent'
  } 
};
```

The 400 unauthorized is displayed on this uri
```
http://localhost:3000/callback?code=SditZiRrQswFl1bLW8veGnwsveNbxIxxxxxxxx&state=eyJyZXR1cxxxxxxxxJ9
```

**Comment by adamjmcgrath** [comment]
Hi @bitsofinfo - thanks for raising this

> `clientSecret: process.env.SECRET,`

This needs to be your [client secret](https://auth0.com/docs/get-started/applications/application-settings#:~:text=Client%20Secret%3A%20A,able%20to%20access.) - not the secret you generate yourself to encrypt the session cookie

If you're getting a 401 from the code exchange, you're probably providing an invalid client secret.

**Comment by bitsofinfo** [comment]
that did it, thanks!
