### ISSUE TITLE
When using a module in an Electron application, "Deriving bits failed" occurs.

### ISSUE THREAD

**Issue by TakamiChie** [auth0/express-openid-connect#367]
### Describe the problem

In an application created with Electron, when using the `auth()` method of the `exporess-openid-connect` module, an error of "Deriving bits failed".

```js
const express = require("express");
const { auth, requiresAuth } = require("express-openid-connect");
let params = {
  authRequired: false,
  auth0Logout: true,
  issuerBaseURL: process.env.ISSUER_BASE_URL,
  baseURL: process.env.BASE_URL,
  clientID: process.env.CLIENT_ID,
  secret: process.env.SECRET,
  clientSecret: process.env.CLIENT_SECRET,
  authorizationParams: {
    response_type: "code"
  }
}
const app = express();
app.use(auth(params)); // <-- This is where the error occurs.
```

When I checked the existing issue, I got information that Electron 14.x would work.

- https://github.com/auth0/express-openid-connect/issues/284

As mentioned in #284, Electron 14.2.9 confirmed that the method works without errors.
However, the latest versions of the later major versions, 15.5.7, 16.2.8, 17.4.8, and 18.3.4, will cause the "Deriving bits failed" error, as will the latest version of Electron as of today, 19.0.5.

### What was the expected behavior?

The error "Deriving bits failed" does not occur.

### Reproduction

- Step 1..
  - Install Electron 19.0.5 and Express-OpenID-Connect 4.18.1
- Step 2..
  - Run App.
- The smallest possible sample app that reproduces the undesirable behavior
  - [testapp.zip](https://github.com/auth0/express-openid-connect/files/8956180/testapp.zip)
  - It is the source code of the application using [Electron quick start](https://github.com/electron/electron-quick-start), but is there a problem?
- Screenshots is below
![image](https://user-images.githubusercontent.com/204666/174990402-456e1dfb-e01d-458c-9223-6dca42324d1d.png)

Note that there are no logs or configuration files.

### Environment

- **Version of this library used:4.18.1**
- **Which framework are you using, if applicable:electron 19.0.5, express 4.18.1**
- **Other modules/plugins/libraries that might be involved:Windows 11 21H2 build 22000.739**
- **Any other relevant information you think would be useful:The stack trace when an error occurs is shown below.**

```
Debugger listening on ws://127.0.0.1:58282/6647fa2e-8cd7-4870-9eee-3b563d9e5f27
    at Object.hkdfSync (node:internal/crypto/hkdf:140:35)
    at module.exports.signing (D:\Users\TakamiChie\Documents\test\testapp\node_modules\express-openid-connect\lib\hkdf.js:31:14)
    at D:\Users\TakamiChie\Documents\test\testapp\node_modules\express-openid-connect\lib\transientHandler.js:58:29
    at Array.forEach (<anonymous>)
    at new TransientCookieHandler (D:\Users\TakamiChie\Documents\test\testapp\node_modules\express-openid-connect\lib\transientHandler.js:57:13)
    at auth (D:\Users\TakamiChie\Documents\test\testapp\node_modules\express-openid-connect\middleware\auth.js:31:21)
    at BrowserWindow.<anonymous> (D:\Users\TakamiChie\Documents\test\testapp\main.js:48:13)
    at BrowserWindow.emit (node:events:526:28)
    at node:electron/js2c/browser_init:161:14116
    at process.processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**Comment by adamjmcgrath** [comment]
Hi @TakamiChie - thanks for raising this

This looks like a bug in Electron (which [should be fixed soon](https://github.com/electron/electron/issues/31634#issuecomment-1162299723)).

This SDK relies on a bunch of HKDF functions that are currently missing in the latest versions of Electron, so there's not much this SDK can do except wait for https://github.com/electron/electron/issues/31634 to be fixed
