### ISSUE TITLE
Package Install Error on production

### ISSUE THREAD

**Issue by Stavtastic** [auth0/express-openid-connect#374]
I am having issues installing this script, the following error is being served via Heroku. The packages were installed with Webstorm using the --legacy-peer-deps command (otherwise the error keeps crawling back). But deployment fails.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: dwl-v3@0.0.0
npm ERR! Found: express@4.16.4
npm ERR! node_modules/express
npm ERR!   express@"~4.16.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer express@">= 4.17.0" from express-openid-connect@2.7.3
npm ERR! node_modules/express-openid-connect
npm ERR!   express-openid-connect@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```

My list of npm modules -g
+-- express-generator@4.16.1
+-- express@4.18.1
+-- gulp-cli@2.3.0
+-- npm@8.3.1
+-- prettier@2.6.2
`-- yarn@1.22.18

I am a bit clueless here as I am new to this auth0 package.

**Comment by adamjmcgrath** [comment]
Hi @Stavtastic

Could you run `npm ls express`? 

The error `express@"~4.16.1" from the root project` is telling me that you have `express@~4.16.1` installed in your root project

**Comment by Stavtastic** [comment]
A buddy of mine created a bypass, but you can clearly see that 4.18.1 is installed
```
PS C:\Users\justi\WebstormProjects\dwl-v2> npm ls express
dwl-v2@0.0.0 C:\Users\justi\WebstormProjects\dwl-v2
+-- express-openid-connect@2.7.3
| `-- express@4.18.1 deduped
`-- express@4.18.1
```
and if we look deeper in the package json:

```
{
  "_args": [
    [
      "express@4.18.1",
      "C:\\Users\\justi\\WebstormProjects\\dwl-v2"
    ]
  ],
  "_from": "express@4.18.1",
  "_id": "express@4.18.1",
  "_inBundle": false,
  "_integrity": "sha512-zZBcOX9TfehHQhtupq57OF8lFZ3UZi08Y97dwFCkD8p9d/d2Y3M+ykKcwaMDEL+4qyUolgBDX6AblpR3fL212Q==",
  "_location": "/express",
  "_phantomChildren": {
    "ee-first": "1.1.1",
    "toidentifier": "1.0.1"
  },
  "_requested": {
    "type": "version",
    "registry": true,
    "raw": "express@4.18.1",
    "name": "express",
    "escapedName": "express",
    "rawSpec": "4.18.1",
    "saveSpec": null,
    "fetchSpec": "4.18.1"
  },
```

**Comment by adamjmcgrath** [comment]
Hi @Stavtastic - thanks for sharing that

I can't explain why you're getting an error that says `Found: express@4.16.4` when you only have `4.18.1` installed - perhaps you should delete your `node_modules` directory?

When I do the following:

```
npx express-generator eg-test
cd eg-test
npm i express@4.18.1
npm i express-openid-connect
```

`express-openid-connect` installs successfully

**Comment by adamjmcgrath** [comment]
Closing due to innactivity
