### ISSUE TITLE
Unexpected JWT alg received, expected HS256, got: RS256 

### ISSUE THREAD

**Issue by lissettdm** [auth0/express-openid-connect#378]
I am having issues using `HS256` signing algorithm:

`
BadRequestError: unexpected JWT alg received, expected HS256, got: RS256 at /<project-path>/node_modules/express-openid-connect/middleware/auth.js:121:19 at runMicrotasks () at processTicksAndRejections (internal/process/task_queues.js:95:5)
`

server.js

```
  app.use(
    auth({
      authRequired: true,
      idpLogout: true,
      idTokenSigningAlg: 'HS256',
      issuerBaseURL: process.env.ISSUER_BASE_URL,
      clientID: process.env.CLIENT_ID,
      authorizationParams: {
        response_type: "code",
        audience: process.env.AUDIENCE,
        scope: "openid profile email",
      },
    })
  );
```

.env
```
CLIENT_ID=Kr***********************WhTI
BASE_URL=http://localhost:3000
CLIENT_SECRET=wd************************************************tRLg99
AUDIENCE=https://my-audience
SECRET=0y************************ySlx
ISSUER_BASE_URL=https://mydomain.auth0.com
PORT=3000
```

Dependencies:
```
    "express": "4.18.1",
    "express-openid-connect": "2.8.0",
    "express-session": "^1.17.3",
```

-- node v14.17.6

Am I missing something?

I also added a console.log in `/node_modules/express-openid-connect/middleware/auth.js` to print `client` object, and I got:

```
Client {
  authorization_signed_response_alg: 'RS256',
  client_id: 'Kr**********************hTI',
  client_secret: 'wdj***************************************RLg99',
  grant_types: [
    'authorization_code'
  ],
  id_token_signed_response_alg: 'HS256',
  response_types: [
    'code'
  ],
  revocation_endpoint_auth_method: 'client_secret_basic',
  token_endpoint_auth_method: 'client_secret_basic'
}
```

**Comment by adamjmcgrath** [comment]
Hi @lissettdm - thanks for raising this

That error suggests that the AS is signing your ID Tokens with RS256 but your client is expecting them as HS256 (due to the `idTokenSigningAlg` setting you've applied). What setting do you have for "JSON Web Token (JWT) Signature Algorithm" in your Application's settings under "Advanced Settings > OAuth" in your auth0 dashboard?

**Comment by lissettdm** [comment]
Hi @adamjmcgrath, thank you for answering, this is what I have:

```
SON Web Token (JWT) Signature Algorithm: RS256
OIDC Conformant: true
```

**Comment by adamjmcgrath** [comment]
@lissettdm - thanks for sharing that

I've just tested your configuration of `idTokenSigningAlg: 'HS256'` on an application with "JSON Web Token (JWT) Signature Algorithm" set to "HS256" and am able to login successfully.

Can you share your tenant domain and client ID and I can investigate what the issue is.

**Comment by lissettdm** [comment]
@adamjmcgrath this is the data I am using. I just create this project for doing tests on my personal account after getting the same error using data of the company I work for:

```
CLIENT_ID=KrJR56whr1pp9uzW7otCMXRS3zkzWhTI
BASE_URL=http://localhost:3000
CLIENT_SECRET=wdjBJ1dlSlJBhQNlRsJIi1yE-C0GIFifmEGzfiOOT0iEp9X5W0xzAT6nNDtRLg99
AUDIENCE=https://signing-testing
SECRET=0yyWMHIHnfXdYwbusaLKFhCyjTT1ySlx
ISSUER_BASE_URL=https://lissettdm.auth0.com
PORT=3000
```

Audience Token Settings:
<img width="1100" alt="Screen Shot 2022-07-27 at 08 36 19" src="https://user-images.githubusercontent.com/52543504/181248426-08abc12e-ad71-4286-8cec-644d38d63d5c.png">

**Comment by adamjmcgrath** [comment]
Hi @lissettdm - thanks for sharing that

I notice that your application type is set to "Single Page Application", it should be set to "Regular Web Application"

I can reproduce your issue when I set my app to a "Single Page Application", but not "Regular Web Application" - so changing that should fix your issue.

However, I will check with the team about why "Single Page Application" apps are issuing ID Tokens signed with RS256 when they're set to HS256

**Comment by adamjmcgrath** [comment]
Hi @lissettdm - could you share how you were able to create a "Single Page Application" app with ID Token Signing Alg set to HS256?

When I try to create a SPA the dashboard only lets me set RS256. The only way I can create a SPA with HS256 is to do the following:

- Create a Regular Web Application
- Change ID Token Signing alg to HS256
- Save the application
- Switch the application type from "Regular Web Application" to "Single Page Application"

**Comment by lissettdm** [comment]
> Hi @lissettdm - could you share how you were able to create a "Single Page Application" app with ID Token Signing Alg set to HS256?

@adamjmcgrath 
This is what I did (Application was already created as SPA with signing algorithm RS256). To change signing algorithm I went to 
- Application Settings ->  Advanced Settings -> Oauth
- OIDC Conformant is active and JSON Web Token (JWT) Signature Algorithm dropdown is disabled

<img width="692" alt="Screen Shot 2022-07-27 at 09 25 17" src="https://user-images.githubusercontent.com/52543504/181258537-fff89aa7-e303-4279-a9b3-7a5efa8494bf.png">

- Deactivate OIDC Conformant option
-  JSON Web Token (JWT) Signature Algorithm dropdown is enable and you can switch between option
<img width="687" alt="Screen Shot 2022-07-27 at 09 26 26" src="https://user-images.githubusercontent.com/52543504/181258701-7bba18cc-1c0f-42d3-a781-c86b2b020f5d.png">
