### ISSUE TITLE
unable to get local issuer certificate

### ISSUE THREAD

**Issue by synthmusic** [auth0/express-openid-connect#379]
I basically have a comment on this closed thread

https://github.com/auth0/express-openid-connect/issues/183#issue-795744319

### Describe the problem
express app throws an 'unable to get local issuer certificate' exception even though everything appears to be configured correctly

### What was the expected behavior?
when accessing https://localhost/login I expected to see an auth screen (login form)

### Reproduction
add express-openid-connect.
Start caddy (optionally - see notes below)
Start my local app
attempt to hit https://localhost/login

### Environment
"node": "16.15.1"
"express-openid-connect": "^2.7.3"
Win 10, however,  and lastly, I deployed to Heroku (which runs linux), and the error is now:  
`RequestError: connect ECONNREFUSED 127.0.0.1:443
`
Got is definitely selecting localhost instead of the provided url.  the question is then why.

local config;
```
const config = {
    authRequired: false,
    auth0Logout: true,
    secret: "asblkfdjkdfbaweeifjbwaejnblaksdlei",
    baseURL: "https://localhost", // changed to the domain host on the heroku test
    clientID: "[the correct id]",
    issuerBaseURL: "https://[redacted].auth0.com",
};
```

### NOTES

I've followed along all the questions and steps on the original thread and done some debugging as well, and I am thinking it is related to a thread in the Got project, in that it's definitely happening in the Got call for me, though it appears not to be the 'fault' of the got project because of other packages, also in thread: (https://github.com/sindresorhus/got/issues/951).

It also fails when running behind a reverse proxy (Caddy) or w/ a self issued cert running directly in express, though with different errors, as would be expected
```
AggregateError: Issuer.discover() failed.
    RequestError: unable to get local issuer certificate
    RequestError: unable to get local issuer certificate
AggregateError: Issuer.discover() failed.
    RequestError: self signed certificate
    RequestError: self signed certificate

```
also ran the Got request as suggested in original thread and also ran it with node-fetch for reference:

```
fetch(`${config.issuerBaseURL}/.well-known/openid-configuration`)
    .then((res) => res.text())
    .then((text) => console.log(text));
```

```
    const response = await got(`${config.issuerBaseURL}/.well-known/openid-configuration`);
    console.log(response.body);

```

fetch successfully returns the config doc, and Got fails with the same cert error as above.

**Comment by adamjmcgrath** [comment]
Hi @synthmusic 

> I am thinking it is related to a thread in the Got project, in that it's definitely happening in the Got call for me, though it appears not to be the 'fault' of the got project because of other packages, also in thread: (https://github.com/sindresorhus/got/issues/951).

Could you run `npm ls agent-base` and share the output?

**Comment by synthmusic** [comment]
Thanks for identifying the offending package, @adamjmcgrath 

```
+-- @okta/okta-sdk-nodejs@6.5.0
| `-- https-proxy-agent@5.0.1
|   `-- agent-base@6.0.2
`-- mailgun-js@0.22.0
  `-- proxy-agent@3.1.1
    +-- agent-base@4.3.0
    +-- http-proxy-agent@2.1.0
    | `-- agent-base@4.3.0
    +-- https-proxy-agent@3.0.1
    | `-- agent-base@4.3.0 deduped
    +-- pac-proxy-agent@3.0.1
    | +-- agent-base@4.3.0
    | `-- https-proxy-agent@3.0.1
    |   `-- agent-base@4.3.0 deduped
    `-- socks-proxy-agent@4.0.2
      `-- agent-base@4.2.1
```

Went ahead and uninstalled the mailgun-js dependency, and...

fixed, hooray, thanks!  That package is deprecated anyway - it would seem the update decision has been forced.  :)
