### ISSUE TITLE
Using "response_type: id_token token" does not populate req.openid.user correctly(?)

### ISSUE THREAD

**Issue by balazsorban44** [auth0/express-openid-connect#38]
### Description

I have the following Express setup:

```js
//...
express()
  .use(auth({
    baseURL: '...',
    required: false,
    idpLogout: true,
    issuerBaseURL: '...',
    clientID: 'orderpages-client',
    authorizationParams: {
      response_type: 'id_token token',
      response_mode: 'form_post',
      scope: [
        'openid',
        'profile',
        'email',
        'address',
        'phone',
        'company_roles',
        'company_profile',
        'company_extended_profile',
        // APIs
        'customer-manager-api',
        'referral-manager-api',
        'order-pages-api',
      ].join(' ')
    }
  }))
.get('/user', requiresAuth(), (req, res) => res.json(req.openid.user))
//...
```
The last three of the scope are referring to API endpoints, which are called from the front-end application.

### Reproduction
The idea is the following:
A React app served from the Express server, using `express-openid-connect` and a custom IdP for auth.

The user logs in, and after that they can fetch their info through a `/user` endpoint.
This should ideally contain all the information like openid, profile, email, address, etc. as given in scope, as well as an access_token, that can be later used to make authenticated requests to the APIs also defined in scope.

The user object though does not contain the required fields, if token is present in `response_type`, which also breaks if scope contains any of the APIs.
![image](https://user-images.githubusercontent.com/18369201/69244479-4eeebe80-0ba5-11ea-9586-7e0cdc8ad9ca.png)

When removing token, and the APIs from scope, the user object looks fine, containing all the required fields

### Environment

- **Version of this library used:** latest
- **Version of the platform or framework used, if applicable:** Node 12
- **Other relevant versions (language, server software, OS, browser):** Linux, Chrome
- **Other modules/plugins/libraries that might be involved:** Custom Identity Provider

**Comment by joshcanhelp** [comment]
So, a few things going on here ... 

First, `response_type: 'id_token token'` is no longer a recommended method to get access tokens to a browser application. It's still being used in many cases but if you're building something new, we'd recommend going authorization code with PKCE. [Here's a great write-up on this from our principal architect](https://auth0.com/blog/oauth2-implicit-grant-and-spa/). We have an SDK that handles that but it's not completely OIDC compliant so it may not work with other IdPs. 

Second, your Express back-end should not be requesting access tokens for your front-end to use. If you're making an API call with the front-end, the front-end should be requesting and managing those access tokens. Requesting tokens from a backend and then distributing them to the browser makes your Express app like it's own authorization server. That blog post above covers the problems with this architecture.

Third, if you're requesting API scopes, you should be requesting an `audience` (that's the parameter that Auth0 uses) or `resource` or other parameter that tells your IdP what API you're requesting tokens for. 

All that said ... if your React app only ever calls the Express backend and that backend is only there to serve the React app then requesting, managing, renewing, accepting, and validation access tokens is more trouble than it's worth. Can you authenticate your React app a different way, like with cookies? That would be much easier to work with and you'd avoid all of the pitfalls of authenticating in a browser application.

As for the user object ... is that coming from the ID token or somewhere else? The non-API scopes you're requesting may or may not be served by your IdP. You should be able to see the OpenID scopes supported by your authorization server here (replacing the domain, of course):

https://auth0.auth0.com/.well-known/openid-configuration

... and everything else would have to be added in as custom scopes, which is handled in Auth0 like so:

https://auth0.com/docs/api-auth/tutorials/adoption/scope-custom-claims#custom-claims

Hope this helps a bit! The architecture here makes all the difference and things can get quite confusing when you've got these different parts working together this way.

**Comment by balazsorban44** [comment]
I think I should have been more specific with the app's architecture. It is a static site, generated by [Gatsby](https://www.gatsbyjs.org/) that uses React. We have a lot of articles we have to serve, which I think is perfect for Gatsby.

The problem is, that most of those articles are **behind an authentication wall**. Gatsby currently supports **client-side routes** only (meaning all pages dependent on authentication cannot be generated on build time, basically it will be served as a regular SPA, first needing to deliver all the JS to produce something on the screen, thus Gatsby looses its main purpose), so I came up with my **own solution**.

When Gatsby builds a site, it generates HTML files for each page/article, and a page-data.json file containing all the information needed to render that particular page. I serve all that from the above mentioned **Express server**, which then **can decide if a** certain **HTML document and the corresponding data** can be sent, **or the user must log in** first. The app still needs to have some client-side logic like authorization (serving articles differently based on the user's preference/job title, although it is not critical if they get served the same data, so I can easily do that part on client side, by using the user's roles sent by the server at `/user`.), **and make some authenticated calls to different APIs**.

The last part is what I need to solve here. I need a token sent from the server to be able to send authenticated requests. After reading the article you linked, I started to have my doubts, but still not sure how to go further then. As an alternative, we use [oidc-client](https://github.com/IdentityModel/oidc-client-js) in another "regular" SPA, but the problem is that we find the library hard to use, mainly because of lack of documentation, very complicated code base, and HUGE bundle size, with no option for tree shaking. I have asked the maintainers if they could spend some time on the documentation part, cause many of the open issues seems to me could be solved by proper docs and providing better type definitions, but of course it is up to them if they do anything on that part. We still have to ship the product in time, so I cannot wait on that, have to find alternatives. This is how I found this package. For me it sounded like the perfect match, but I am not certain after the article... We rely on OpenID, and at the moment we have our own IdP which makes it a bit more complicated, especially that none of us on the front-end is expert in this area. I do not know  if there exists any more client side alternatives like `oidc-client`, I assume you would recommend an approach like that then? At the end, the easiest for us at the front-end would be simply to use an "off-the-shelf" IdP solution, like Auth0, but it is a tiny bit more problematic to re-implement everything on the backend with a new IdP, so I threw it in the air, it will be considered, but again, we cannot wait with that to ship our product.

I hope I am still on the right channel and not totally off-topic, I really appreciate your help! 🙏

**Comment by joshcanhelp** [comment]
>  I serve all that from the above mentioned Express server, which then can decide if a certain HTML document and the corresponding data can be sent, or the user must log in first.

Just with my limited understanding of your architecture, it seems like the best way to do this is all server-side. Everything will be simpler and you won't have to deal with browser issues around token storage and renewal.  

> make some authenticated calls to different APIs from the client.

... but that sounds like you will have to keep some of this in the client. We have an SDK for single-page applications but, again, that might not work with another IdP:

https://github.com/auth0/auth0-spa-js

If you can build this in a way that the Express server is doing the auth as well as the API calls and serving a generated page back, I think that will simplify things a lot. SPAs are, put plainly, difficult to deal with, mainly due to token renewal and cross-site cookie implications thereof. You'l have less of that problem if you're able to do the work in Express. 

Hope that helps a bit more! I'm going to close this for now but happy to answer any further questions you have on how this SDK can fit into your product here.
