### ISSUE TITLE
Undefined behaviour on openid-configuration endpoint

### ISSUE THREAD

**Issue by ryanolee** [auth0/express-openid-connect#389]
### Describe the problem
When making a request to the discovery endpoint (/.well-known/openid-configuration) [`response_types_supported`](https://openid.net/specs/openid-connect-discovery-1_0.html) is returned as a required field. The current library behaviour seems to be that it ignores this configuration field and directly assume `id_token` is the correct `response_type` unless configured otherwise. This leads to undefined behaviour where the OIDC Provider will likely internally error leading to difficult to debug edge cases

### What was the expected behavior?

It might be an idea to log a warning an unsupported token type is in use or the library could surface an error raising that a request is using an unsupported `response` type. Not sure which one would be the best for this. But it is probably a better idea for the library to handle this over the OIDC Provider. Given the OIDC Provider's messaging can be pretty poor to non-existent at times for errors like these :laughing: 

### Reproduction
Use an OIDC provider that by default does not support id_token (I.e AWS Cognito). Configure the library with standard OIDC configuration and then look at the redirect made to `/oauth2/authorize`

**Comment by ryanolee** [comment]
Feel free to assign to me. Will look to get a PR for this open in the coming days.

**Comment by adamjmcgrath** [comment]
Hey @ryanolee - thanks for raising this

We do log a message in these instances https://github.com/auth0/express-openid-connect/blob/master/lib/client.js#L60-L74

You just have to have [debug enabled](https://github.com/auth0/express-openid-connect/blob/master/TROUBLESHOOTING.md#1-debug-logs)

**Comment by ryanolee** [comment]
Thanks for the quick reply!
That makes for more sense :eyes: . Sorry completely missed there was a troubleshooting.md!  I guess the follow up question to this is if it might make more sense to surface these errors with a higher severity. Given it is highly likely the OIDC Provider will trigger an error in the event an unsupported scheme is used.

At least to me it would make more sense to error out / warn as the default behaviour over relying on the OIDC Provider to handle the invalid behaviour. (Or raise it as a higher level warning like how the [ 'form_post' for response_mode]( https://github.com/auth0/express-openid-connect/blob/master/FAQ.md) is currently handled). Just because the mismatch will almost always cause an error in the OIDC Provider. And depending on the feedback the messaging from the provider can be really really poor :thinking: . (Possibly with a configuration option to suppress warnings from the platform if people are using the library in a non standard format :thinking: ). 

Though that is probably up for further discussion. If you think something like that could be helpful I would be more than happy to try to open a PR for it. If not feel free to close this issue!
Thanks @adamjmcgrath! :raised_hands:

**Comment by adamjmcgrath** [comment]
Thanks for the suggestion @ryanolee, where happy with using debug and the troubleshooting instructions. But we'll keep reviewing this in case more issues get raised around this
