### ISSUE TITLE
when accessing `req.oidc.user`, TypeError: Cannot read properties of undefined  

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [auth0/express-openid-connect#397]
### Describe the problem

My express server provide public APIs and private APIs both. Private APIs that can be used without auth0 authentication and a private api that requires authentication. example code:

```js
const app = express()

// public api
app.post('/public/api/a', handleA)
app.post('/public/api/b', handleB)
...

// auth0
app.use(auth({...}))

// private api
app.post('/api/c', handleC)
app.post('/api/d', handleD)
...
```

However, in this repo's TypeScript file `index.d.ts`, Adding `oidc` attribute as a non-optional Request and Response like below:

```ts
declare global {
  namespace Express {
    interface Request {
      oidc: RequestContext;
    }

    interface Response {
      oidc: ResponseContext;
    }
  }
}
``` 

So, in the public API handler, `handleA` function, the code below does not occur an error at compile time (tsc), but at runtime, `Cannot read properties of undefined (reading 'user')` this TypeError occurs.

```js
export const handleA = (req, res) => {
  const posts = getUserPosts(req.oidc.user)
}
```

### What was the expected behavior?

Accessing `req.oidc.something` without a type guard should occur `Object is possibly 'undefined'` tsc error.

![image](https://user-images.githubusercontent.com/15520015/196026319-995c49f5-4a07-4770-a15e-3759c3654eb3.png)

### Environment
- express-openid-connect: 2.8.0

**Comment by adamjmcgrath** [comment]
Hi @b6pzeusbc54tvhw5jgpyw8pwz2x6gs - thanks for raising this

> So, in the public API handler, handleA function, the code below does not occur an error at compile time (tsc), but at runtime, Cannot read properties of undefined (reading 'user') this TypeError occurs.

There's a tradeoff here, the SDK assumes you only use it in handlers where the `auth` middleware has run. That way when you use it correctly, you don't have to add branching logic for `req.oidc` being undefined.

eg

```js
app.use(auth({...}))

app.get('/my-login', (req, res) => {
  if (!req.oidc) {
    // Why do I have to write this unreachable branch? I know it's defined because of the lines above
  }
  return req.oidc.login();
})
```

You can't use `req.oidc` in a handler that runs before the `auth` middleware, so why would you ever reference it.

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
@adamjmcgrath That's a good point. 

If you know the `app.use(auth(...))` code exists above, and you don't want the if statement as type guard code, you can also use [Type Assertions](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions).

```ts
import { RequestContext } from 'express-openid-connect'

app.use(auth({...}))

app.get('/my-login', (req, res) => {
  return (req.oidc as RequestContext).login();
})
```

---

Nevertheless, the reason for posting this issue and PR is, We believe that in a large program it is possible to accidentally access `req.oidc` before using the `app.use(auth(...))` code. Types says that the `oidc` object exists, but in runtime it doesn't.

As you said, there's a tradeoff. As you may know, there are several options to choose from.

1. Some packages extend their non-optional properties to the Request type and warn that middleware must be used first.
    - https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a2487918e604a877f2ab68d6a631d9739c06da58/types/express-session/index.d.ts#L24

2. Other packages belows also define their extended properties as optional like my PR #398 
    - https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a2487918e604a877f2ab68d6a631d9739c06da58/types/express-paginate/index.d.ts
    - https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a2487918e604a877f2ab68d6a631d9739c06da58/types/express-ntlm/index.d.ts
    - https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a2487918e604a877f2ab68d6a631d9739c06da58/types/express-jwt/index.d.ts

3. Another way is, Providing a type that inherits the Request type instead modifying type like `OpenidRequest`: 
https://github.com/auth0/express-openid-connect/blob/cf1ffef21b2e11c90286188f2f85ebd6708f1051/index.d.ts#L42-L47

Personally, I like No. 3, but here it is deprecated.😭 TypeScript requires more code, but instead helps you catch errors at compile time and makes your product more stable at runtime. I think that applying TypeScript means choosing stability, not short code. So I prefer 3 or 2.

**Comment by adamjmcgrath** [comment]
> I like No. 3, but here it is deprecated.(😭Could you tell me why it was deprecated?) 

See https://github.com/auth0/express-openid-connect/issues/222

Don't want to go for option 2 for the reasons I've already explained (adding the type assertion would still be a pain), but happy to go with 1 if you want to add a comment similar to `express-session`'s

As I said, it's a trade off, whatever I choose wont suit everybody, but I'm happy that the existing solution suits the most use cases.

**Comment by adamjmcgrath** [comment]
Closing as I believe we've answered the question, feel free to ping me if you want to discuss some more.
