### ISSUE TITLE
Use form_post instead of fragment if supported by the provider

### ISSUE THREAD

**Issue by jfromaniello** [auth0/express-openid-connect#4]
We could use `form_post` instead of `fragment` for `fragment` response types IF the provider lists form_post as supported.

**Comment by joshcanhelp** [comment]
See #13 for reasons to keep `response_type=fragment` around

**Comment by panva** [comment]
@joshcanhelp the point here was to default to form_post when its supported, that is still something we should do. Please re-open.

**Comment by joshcanhelp** [comment]
It already defaults to `form_post`:

https://github.com/auth0/express-openid-connect/blob/master/lib/config.js#L6-L10

App fails on first load if that's invalid.
