### ISSUE TITLE
because every request will do redis set action, and sometimes will refreshtoken unsuccessfully.

### ISSUE THREAD

**Issue by xiawanan** [auth0/express-openid-connect#408]
### Describe the problem
When the refresh token is sandwiched between multiple requests, it will be overwritten by the set redis action triggered by subsequent requests, resulting in the value of the old appSession.

### What was the expected behavior?
It should have a flag to control the redis set action after the appSession has been created.
No need update the appSession in every request.

### Reproduction
1.use a custom store like [connect-redis](https://github.com/tj/connect-redis)
2.call multiple api's at the same time and have a refreshtoken in between

### Environment
"connect-redis": "^6.1.1",
"express": "^4.17.3",
"express-openid-connect": "^2.7.1",

**Comment by adamjmcgrath** [comment]
Hi @xiawanan - thanks for raising this

> When the refresh token is sandwiched between multiple requests,

I'm not sure I understand what you mean - what is the actual issue you are seeing with concurrent requests writing to the store?

**Comment by xiawanan** [comment]
Hi @adamjmcgrath - thanks for quick apply.

I printed the redis log to find this issue, and the below is a example what I see:
`
api1[2022-10-29 15:30:31] "get" "sess:2348b00680e4e8aa3d73aeb158f9a72c"
api1[2022-10-29 15:30:31] "set" "inssuite31:sess:2348b00680e4e8aa3d73aeb158f9a72c" access_token1 refresh_token1
api2[2022-10-29 15:30:31] "get" "sess:2348b00680e4e8aa3d73aeb158f9a72c"
api2[2022-10-29 15:30:31] "set" "inssuite31:sess:2348b00680e4e8aa3d73aeb158f9a72c" access_token1 refresh_token1
api3[2022-10-29 15:30:31] "get" "sess:2348b00680e4e8aa3d73aeb158f9a72c"
api3[2022-10-29 15:30:31] "set" "inssuite31:sess:2348b00680e4e8aa3d73aeb158f9a72c" access_token1 refresh_token1
refresh1[2022-10-29 15:30:31] "get" "sess:2348b00680e4e8aa3d73aeb158f9a72c"
refresh1[2022-10-29 15:30:31] "set" "inssuite31:sess:2348b00680e4e8aa3d73aeb158f9a72c" access_token2 refresh_token2
api4[2022-10-29 15:30:31] "get" "sess:2348b00680e4e8aa3d73aeb158f9a72c"
api4[2022-10-29 15:30:31] "set" "inssuite31:sess:2348b00680e4e8aa3d73aeb158f9a72c" access_token1 refresh_token1
api5[2022-10-29 15:30:31] "get" "sess:2348b00680e4e8aa3d73aeb158f9a72c"
api5[2022-10-29 15:30:31] "set" "inssuite31:sess:2348b00680e4e8aa3d73aeb158f9a72c" access_token1 refresh_token1
refresh2[2022-10-29 15:30:31] "get" "sess:2348b00680e4e8aa3d73aeb158f9a72c"
refresh2[2022-10-29 15:30:31] "del" "sess:2348b00680e4e8aa3d73aeb158f9a72c" (because use the refresh_token1(has been used) to refresh)
`
the refresh1 set action has been overwritten by api4 and api5..
so the next refresh2 will use the old refresh_token1 to refresh again, then will fail.

Do you have any way to prevent api4 and api5 from getting the old value to set in the case of high concurrency?

**Comment by adamjmcgrath** [comment]
Hi @xiawanan - thanks for sharing that

> so the next refresh2 will use the old refresh_token1 to refresh again, then will fail.

Are you using Refresh Token Rotation? This isn't required for confidential clients and in cases where you can't guarantee the order of concurrent requests, as is the case here, it's not advised because it can trigger the breach detection I think you're describing.

**Comment by xiawanan** [comment]
Hi @adamjmcgrath

> Are you using Refresh Token Rotation?

Yes, The program I'm actually developing is SPA, And long-lived refresh tokens are not suitable for SPAs because there is no persistent storage mechanism in a browser that can assure access by the intended application only. So I change this package logic to not set refresh token when session exists, but I think it's maybe not a good idea to resolve it. Do you other ways to solve this problem? Or can you suggest other options for us to use.

**Comment by adamjmcgrath** [comment]
Hi @xiawanan 

This SDK is for regular web apps - it keeps the tokens in an HttpOnly encrypted cookie which is not accessible to a browser. We usually recommend a SPA SDK like `auth0-spa-js` (which does have code to prevent concurrent requests triggering breach detection) if you want to access tokens on the browser

**Comment by xiawanan** [comment]
Hi @adamjmcgrath - thanks for your suggestion.

I will try `auth0-spa-js` it, you can close this comment.

**Comment by adamjmcgrath** [comment]
No problem @xiawanan 👍
