### ISSUE TITLE
Wrong interface links in the API reference

### ISSUE THREAD

**Issue by bcafuk** [auth0/express-openid-connect#409]
### Describe the problem

The API reference contains links to files with the wrong letter case. For example, it links to `AccessToken.html`, which does not exist. The file with the documentation for the interface is called `accesstoken.html` in the repository.

It also happens when clicking links for properties and methods of the interfaces.

This has happened with all of the interfaces I tried it with.

### What was the expected behavior?

I expected to click the `AccessToken` interface link in the docs and see documentation for that interface. Instead, I got a 404 error.

### Reproduction for inter-page links

- Go to https://auth0.github.io/express-openid-connect/index.html
- Click the link for the `AccessToken` interface and get taken to
https://auth0.github.io/express-openid-connect/interfaces/AccessToken.html
- This will show a GitHub Pages 404 page

_Note:_ The URL https://auth0.github.io/express-openid-connect/interfaces/accesstoken.html works, and it shows what I expected to see.

### Reproduction for intra-page links

- Manually go to https://auth0.github.io/express-openid-connect/interfaces/accesstoken.html
- Click the fragment link to go to the `access_token` property and get taken to
https://auth0.github.io/express-openid-connect/interfaces/AccessToken.html#access_token
- This will show a GitHub Pages 404 page

_Note:_ The URL https://auth0.github.io/express-openid-connect/interfaces/accesstoken.html#access_token works, and it shows what I expected to see.

**Comment by adamjmcgrath** [comment]
Thanks for spotting that @bcafuk - raised #411
