### ISSUE TITLE
Getting error when running tests

### ISSUE THREAD

**Issue by balazsorban44** [auth0/express-openid-connect#41]
### Description

When running tests, a particular test fails randomly.

![image](https://user-images.githubusercontent.com/18369201/70287318-c3914200-17ce-11ea-9825-b21d1f1193a3.png)

### Reproduction

1. run `npm test`
2. wait for the error to randomly appear 🙃

### Environment

> Please provide the following:

- **Version of this library used:** 0.5.0
- **Version of the platform or framework used, if applicable:** Node 12.12.0
- **Other relevant versions (language, server software, OS, browser):** Ubuntu 19.10
- **Other modules/plugins/libraries that might be involved:** -

**Comment by joshcanhelp** [comment]
Interesting ... I can't seem to reproduce this. But I see that this test uses a different issuer base URL and the network mocking library mocks `test.auth0.com` for the discovery document. What if you changed the value [here](https://github.com/auth0/express-openid-connect/blob/master/test/invalid_id_token_alg.tests.js#L14):

```dif
-    issuerBaseURL: 'https://flosser.auth0.com',
+   issuerBaseURL: 'https://test.auth0.com',
```
