### ISSUE TITLE
Dynamic Connection Resolution

### ISSUE THREAD

**Issue by DavidHudlow** [auth0/express-openid-connect#415]
### Describe the problem you'd like to have solved

We'd like to be able to dynamically switch between connections (Auth0), but that's not currently possible because that field of `authorizationParams` is set as a string type during `app.use` at server startup.

### Describe the ideal solution

We would like to be able to set fields in `authorizationParams` to functions that take the login state as an argument and return the desired value.

## Alternatives and current work-arounds

This patch is what we're using now:

```
diff --git a/lib/context.js b/lib/context.js
index 77ee5f3..ba11b19 100644
--- a/lib/context.js
+++ b/lib/context.js
@@ -249,6 +249,10 @@ class ResponseContext {
         ...authVerification,
       };
 
+      if (authParams.connection && typeof authParams.connection === 'function') {
+        authParams.connection = authParams.connection(stateValue);
+      }
+
       if (usePKCE) {
         authVerification.code_verifier = transient.generateNonce();
 

```

### Additional information, if any

The patch above only applies to the `connection` field but it might be useful to make various other fields in `ConfigParams` and especially `authorizationParams` since those get sent with the login request.

**Comment by adamjmcgrath** [comment]
Hi @DavidHudlow - you can achieve this by calling `res.oidc.login` directly (see [examples](https://github.com/auth0/express-openid-connect/blob/master/EXAMPLES.md#3-route-customization) for more info)

eg

```js
app.use(
  auth({
    routes: {
      // Override the default login route to use your own login route as shown below
      login: false
    },
  })
);

app.get('/login', (req, res) => {
   const connection = // something to do with the request.
   res.oidc.login({ authorizationParams: { connection } });
});
```

**Comment by DavidHudlow** [comment]
Perfect! Thanks, @adamjmcgrath! That's just what we needed.
