### ISSUE TITLE
Incorrect Type Definitions for Properties Added in SDK-3808

### ISSUE THREAD

**Issue by mmcxii** [auth0/express-openid-connect#428]
### Describe the problem

Ticket SDK-3808 (#419) added two properties to the `SessionConfigParams` type. I believe these types are meant to be optional based on their validation schema, however their actual type definitions require the user to set a value for the property.

```ts
// type definitions
signSessionStoreCookie: boolean;
requireSignedSessionStoreCookie: boolean;
```

```ts
 // validation schema
signSessionStoreCookie: Joi.boolean().optional().default(false),
requireSignedSessionStoreCookie: Joi.boolean()
  .optional()
  .default(Joi.ref('signSessionStoreCookie')),
```

### What was the expected behavior?

The properties should be defined using the optional property syntax so users are not required to set a value for the property.

```ts
signSessionStoreCookie?: boolean;
requireSignedSessionStoreCookie?: boolean;
```

### Reproduction

- Declare an object variable using the `SessionConfigParams` type.
- Do not set a value for `signSessionStoreCookie` or `requireSignedSessionStoreCookie`.
- Observe a type error thrown similar to this `Type '{}' is missing the following properties from type 'SessionConfigParams': signSessionStoreCookie, requireSignedSessionStoreCookie`

### Environment

- **Version of this library used:** v2.11.0
- **Which framework are you using, if applicable:** express@4.18.2
- **Other modules/plugins/libraries that might be involved:** connect-redis@6.1.3
- **Any other relevant information you think would be useful:** N/A

**Comment by adamjmcgrath** [comment]
Thanks for spotting that @mmcxii - will fix in #429
