### ISSUE TITLE
The 'expires' prop required in the cookiesConfig

### ISSUE THREAD

**Issue by younes-io** [auth0/express-openid-connect#431]
I need to configure the `expires` property in the `CookieConfigParams` but it's not available :

https://github.com/auth0/express-openid-connect/blob/44aa3cf6a8e30410c33fe45fb1202c478b569301/index.d.ts#L705
Even though it is available [here](https://expressjs.com/en/api.html#res.cookie)

I use this in the context of a `RedisStore` which acts as a session store; as you can see [here](https://github.com/tj/connect-redis/blob/master/lib/connect-redis.js#L138), I don't have access to the `expires` prop which is used by the function `_getTTL`. I am aware that things could be done another way, but still, the issue remains : I still need to have access to the `expires` prop (and maybe other props available in the `Express.Response` object)

What do you think ?

**Comment by adamjmcgrath** [comment]
`sess.cookie.expires` is derived from the [session expiry config](https://auth0.github.io/express-openid-connect/interfaces/SessionConfigParams.html)

So you can modify `sess.cookie.expires` by modifying the session expiry config - for example if I want the ttl of the entry in redis to be 1 hour from when the session is created, I would set the session expiry config to:

```js
{
  rolling: false,
  absoluteDuration: 60 * 60
}
```

Then when the entry is created the `sess.cookie.expires` will be set to `config.session.absoluteDuration * 1000 + Date.now()`

**Comment by adamjmcgrath** [comment]
Closing as I think https://github.com/auth0/express-openid-connect/issues/431#issuecomment-1351711546 has answered your question
