### ISSUE TITLE
Please support NestJS.

### ISSUE THREAD

**Issue by KieronWiltshire** [auth0/express-openid-connect#436]
### Describe the problem you'd like to have solved
NestJS is built on top of an abstraction of Express. It's difficult to integrate this package so I'm currently relying on passport-openidconnect. I don't think it would take much work to provide a nestjs equivalent of this package, it would just mean moving some of the middleware code out to helper functions so that they can be implemented as guards in NestJS too.

**Comment by adamjmcgrath** [comment]
Hi @KieronWiltshire 

We don't have any plans to support NestJS - but we're continually evaluating this, so thanks for your suggestion - it helps us prioritise new SDKs and features. (see also https://github.com/auth0/express-openid-connect/issues/221#issuecomment-822289818)

**Comment by gafigueroa** [comment]
Would be awesome to have this in nestjs

**Comment by RoopeHakulinen** [comment]
Surprised to hear NestJS support not being on the roadmap considering its rise in popularity. As others, would love to see that added.

**Comment by spuxx1701** [comment]
+1 for Nest!

**Comment by LukasGaebler** [comment]
+1 for nest

**Comment by dominik992** [comment]
+1 for nest

**Comment by Bravo2x** [comment]
+1 for nest

**Comment by jdockwarder** [comment]
+1 for nest

**Comment by idbentley** [comment]
+1 for nest
