### ISSUE TITLE
client_credentials flow support?

### ISSUE THREAD

**Issue by juliussuominen** [auth0/express-openid-connect#457]
### Describe the problem you'd like to have solved

Just clarify this for myself: Does this package support the `client_credentials` flow? I haven't been able to configure the `auth` middleware to accept client_credentials access tokens received from a locally running OIDC provider implemented with [`oidc-provider`](https://github.com/panva/node-oidc-provider/tree/main). Authorization code flow seems to work as expected.

### Describe the ideal solution

Get access token from OIDC provider `/token` endpoint, use (bearer) token for authenticating requests to a Node.js api protected by `express-openid-connect`.

## Alternatives and current work-arounds

Implement a custom middleware using https://github.com/panva/node-openid-client. 

### Additional information, if any

N/A

**Comment by adamjmcgrath** [comment]
Hi @juliussuominen - thanks fro raising this

>  for authenticating requests to a Node.js api protected by express-openid-connect.

This SDK is for doing web sign-on. To protect an API with an access token - we recommend using https://github.com/auth0/node-oauth2-jwt-bearer

**Comment by juliussuominen** [comment]
Great, thanks!
