### ISSUE TITLE
Question: `genid` function as async

### ISSUE THREAD

**Issue by Will956** [auth0/express-openid-connect#463]
### Describe the problem you'd like to have solved

Hey 👋 

I was just wondering if there is any specific reason to not have the `genid` function async?

We can probably have some async operation to generate IDs, so it can not be used for this at the moment.

Thanks 🙌

**Comment by adamjmcgrath** [comment]
Hey @Will956 

Yep - good point, it should be async. Not sure when I'll get round to adding this, but happy to accept a PR in the meantime.

**Comment by adamjmcgrath** [comment]
This got published in https://github.com/auth0/express-openid-connect/releases/tag/v2.15.0
