### ISSUE TITLE
Use of sync api 

### ISSUE THREAD

**Issue by maciekpaprocki** [auth0/express-openid-connect#474]
### Checklist

- [X] The issue can be reproduced in the [express-openid-connect sample app](https://github.com/auth0-samples/auth0-express-webapp-sample/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/express-openid-connect#readme), [Examples](https://github.com/auth0/express-openid-connect/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/express-openid-connect/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/express-openid-connect/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/express-openid-connect/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Seems like openid is using sync api. 

Not sure what implication it really has for performance, but it's definitely an issue when running with --trace-sync-io to make sure my app is flawless :) 

 

### Reproduction

1. run node with --trace-sync-io 
2. login
3. visit any page

### Additional context

(node:30875) WARNING: Detected use of sync API
    at randomFillSync (node:internal/crypto/random:140:19)
    at randomBytes (node:internal/crypto/random:102:5)
    at module.exports (somepath/node_modules/jose/lib/help/generate_iv.js:5:25)
    at encrypt (somepath/node_modules/jose/lib/jwe/encrypt.js:172:16)
    at single (somepath/node_modules/jose/lib/jwe/index.js:7:6)
    at encrypt (somepath/node_modules/express-openid-connect/lib/appSession.js:78:16)
    at setCookie (somepath/node_modules/express-openid-connect/lib/appSession.js:125:21)
    at setCookie (somepath/node_modules/express-openid-connect/lib/appSession.js:184:7)
    at somepath/node_modules/express-openid-connect/lib/appSession.js:391:34
    at writeHead (somepath/node_modules/on-headers/index.js:35:16)

### express-openid-connect version

2.16.0

### Express version

5 ( but it would be issue with 4 ) 

### Node.js version

18

**Comment by adamjmcgrath** [comment]
Thanks for raising this @maciekpaprocki 

This SDK currently supports older versions of Node which rely on the sync crypto API.

When we next do a new major, we will drop those old Node versions and upgrade to a crypto library that supports async crypto. But we'll need to wait until we schedule a new major, which I don't have a timeline for currently I'm afraid
