### ISSUE TITLE
AggregateError:  Issuer.discover() failed

### ISSUE THREAD

**Issue by mnadeem** [auth0/express-openid-connect#476]
### Checklist

- [X] The issue can be reproduced in the [express-openid-connect sample app](https://github.com/auth0-samples/auth0-express-webapp-sample/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/express-openid-connect#readme), [Examples](https://github.com/auth0/express-openid-connect/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/express-openid-connect/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/express-openid-connect/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/express-openid-connect/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I have deployed the application in Azure Container Apps, I am getting the following error, what could be the potential issue.

**Appreciate your help.**

```
AggregateError:  Issuer.discover() failed.\n    RequestError: Timeout awaiting 'request' for 5000ms\n    RequestError: Timeout awaiting 'request' for 5000ms\n    at Issuer.discover (/app/app-root/node_modules/openid-client/lib/issuer.js:265:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async get (/app/app-root/node_modules/express-openid-connect/lib/client.js:42:18)\n    at async ResponseContext.login (/app/app-root/node_modules/express-openid-connect/lib/context.js:188:22)
```

### Reproduction

NA

### express-openid-connect version

2.16.0

### Express version

4.18.2

### Node.js version

18

**Comment by adamjmcgrath** [comment]
Hi @mnadeem 

That error suggests that your application cannot reach the internet or the value for `ISSUER_BASE_URL` is incorrect.

- What happens when you do an http request to a resource on the internet from that container application?
- What value do you have for `issuerBaseURL`/`ISSUER_BASE_URL`?

**Comment by mnadeem** [comment]
Thanks a bundle, the issue has been fixed

The url was incorrect

**Comment by tonysson** [comment]
i have the same issue using 
"express-openid-connect": "2.18.1"
node : 14

`
const config = require('config');
const { auth } = require('express-openid-connect');


const AgentAuthorizer = require('../authorizer/AgentAuthorizer');



const oauthConfig = {
  authRequired: false,
  afterCallback: AgentAuthorizer.getUser,
  clientAuthMethod: 'client_secret_post',
  authorizationParams: {
    response_type: 'code',
    scope: 'my scope',
  },
};

const createAuthMiddleware = (clientID, clientSecret, domain) => {
  console.log(`Creating midleware for domain : ${domain}`);
  console.log(`Client ID : ${clientID}`);
  console.log(`Client secret : ${clientSecret}`);
  return auth({
    clientID,
    clientSecret,
    issuerBaseURL: 'my issuer url',
    ...oauthConfig,
  });
};

const middlewarePerDomain = Object.values(config.authentication.oidc.clients).map(c => ({
  domain: c.domain,
  id: c.id,
  secret: c.secret,
  middleware: createAuthMiddleware(c.id, c.secret, c.domain),
}));



module.exports = (req, res, next) => {
  const domain = req.hostname;
 
  const middlewareToExecute = middlewarePerDomain.find(m => domain.endsWith(m.domain));
  if (middlewareToExecute) {
    console.log('Using middleware for Domain:', middlewareToExecute.domain);
    console.log('Middleware config:', middlewareToExecute);
    console.log(`Client ID DANS MON MIDDLEWARE : ${middlewareToExecute.id}`);
    console.log(`Client secret DANS MON MIDDLAWARE : ${middlewareToExecute.secret}`);
    return middlewareToExecute.middleware(req, res, next);
  }
  next(new Error(`No OIDC middleware suitable for hostname ${req.hostname}`));
};

All my console are showing the values of my secrets , id and domain: But still have the same issuer : {"code":"500-000","message":"Issuer.discover() failed.\n    RequestError: Timeout awaiting 'request' for 5000ms\n    RequestError: Timeout awaiting 'request' for 5000ms"}  i ping and curl my issuerBaseURL from container and it responds too.
