### ISSUE TITLE
ES6 Modules are not yet supported completely.

### ISSUE THREAD

**Issue by techlism** [auth0/express-openid-connect#480]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/express-openid-connect#readme), [Examples](https://github.com/auth0/express-openid-connect/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/express-openid-connect/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/express-openid-connect/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/express-openid-connect/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Today I tried using `express-openid-connect` with ES6 modules ( use import instead of require) but it is not supported for example the `requiresAuth ` .
Now I am okay with common JS based system but my project was going good with ES6 modules so far but since Nodejs doesn't allow both types ( use either a commonJS type or ES6 module type), I have switch my complete project to commonJS.

### Describe the ideal solution

A possible solution in my opinion is to allow both  the types or mention explicitly that only Common JS will be supported.

### Alternatives and current workarounds

I tried importing the whole package and then use it still doesn't work.

### Additional context

![image](https://github.com/auth0/express-openid-connect/assets/105585386/5fb8a506-029a-49a7-913d-6845cc145afc)

**Comment by adamjmcgrath** [comment]
Hi @techlism - thanks for raising this

> Nodejs doesn't allow both types ( use either a commonJS type or ES6 module type)

This is not true, you can use commonJS in ES6 modules (see https://nodejs.org/docs/latest-v17.x/api/esm.html#esm_commonjs_namespaces)

The `module.exports` object is provided as the default export, so as your error message suggests, you just need to get `requiresAuth` from the default export eg

```js
import pkg from 'express-openid-connect';
const { requiresAuth } = pkg;
```

In a future major we will plan to support ES6 Modules, but for the time being this SDK is CommonJS only
