### ISSUE TITLE
node crypto hkdfSync vs hkdf

### ISSUE THREAD

**Issue by acberk** [auth0/express-openid-connect#487]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/express-openid-connect#readme), [Examples](https://github.com/auth0/express-openid-connect/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/express-openid-connect/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/express-openid-connect/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/express-openid-connect/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

What is the reason for using hkdfSync instead of the non-blocking hkdf function with a callback or as a Promise?

_I haven't been able to find anything addressing this choice._

### Describe the ideal solution

Option to use non-blocking hkdf

**Comment by adamjmcgrath** [comment]
Hi @acberk - thanks for raising this

`hkdfSync` is only used when the middleware is constructed (not for every request) so it's not a particularly hot code path and it's convenient to build middleware synchronously:

```js
const middleware = () => {
  // This bit happens once, is synchronous - we use hkdfSync here
  return async (req, res, next) => {
    // This bit happens a lot, is async
  }
}


app.use(middleware());
```

**Comment by acberk** [comment]
Very helpful, thanks for the explanation.
