### ISSUE TITLE
code samples, an interface, or middleware for fastify (express is becoming legacy)

### ISSUE THREAD

**Issue by jordanst3wart** [auth0/express-openid-connect#504]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/express-openid-connect#readme), [Examples](https://github.com/auth0/express-openid-connect/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/express-openid-connect/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/express-openid-connect/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/express-openid-connect/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Would it be possible to have code samples, middleware, or an interface for fastify?

I'm using `auth` for a nestjs app, using express, and this repository as express js middleware. I just became aware that express is basically dead in the water with updates. It still doesn't support http/2 despite it being a priority.

pr for http/2 (outstanding for 1.5 years): https://github.com/expressjs/compression/pull/170
top priorities of express js (including http/2): https://expressjs.github.io/statusboard/
code frequency of express js: https://github.com/expressjs/express/graphs/code-frequency

### Describe the ideal solution

Code samples, an interface/module that is usable, or a full middleware solution

### Alternatives and current workarounds

There is this repository:
https://www.npmjs.com/package/fastify-auth0-verify

It has poor documentation, and 15,000 weekly downloads, and is growing.

The official auht0 express openid connect middleware has 46,061 weekly downloads:
https://www.npmjs.com/package/express-openid-connect

I don't like using an unofficial npm repository for important security purposes

**Comment by adamjmcgrath** [comment]
Hi @jordanst3wart - thanks for raising this

Feature requests for new SDKs would be better raised https://community.auth0.com/t/how-do-i-submit-product-feedback-or-feature-requests/22150 - I've made a note of your request internally

> There is this repository:
> [npmjs.com/package/fastify-auth0-verify](https://www.npmjs.com/package/fastify-auth0-verify)

This SDK does login using OpenID Connect - the `fastify-auth0-verify` library protects API requests with Bearer access tokens (our equivalent express SDK would be https://github.com/auth0/node-oauth2-jwt-bearer/tree/main/packages/express-oauth2-jwt-bearer)

The fastify equivalent library for this SDK would be something like https://github.com/fastify/fastify-oauth2
