### ISSUE TITLE
BadRequestError: checks.state argument is missing

### ISSUE THREAD

**Issue by javiern8410** [auth0/express-openid-connect#543]
### Checklist

- [X] The issue can be reproduced in the [express-openid-connect sample app](https://github.com/auth0-samples/auth0-express-webapp-sample/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/express-openid-connect#readme), [Examples](https://github.com/auth0/express-openid-connect/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/express-openid-connect/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/express-openid-connect/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/express-openid-connect/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When update to versión 2.5.2 get the following error. 

BadRequestError: checks.state argument is missing
    at /home/app/node_modules/express-openid-connect/middleware/auth.js:121:31
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

In this version I cannot find the checks object that I found in older versions in the auth.js file. 

```js
const checks = {
    max_age,
    code_verifier,
    nonce,
    state,
};
```

### Reproduction

1 - I have a production app with auth0 integrated via openid connect
2 - Update openid-connect
3 - Get error provide in description 

### express-openid-connect version

2.5.2 

### Express version

4.17.1

### Node.js version

v16.15.0 and 18.17.1

**Comment by adamjmcgrath** [comment]
Hi @javiern8410 - thanks for raising this

I can't reproduce the error given the steps you've shared.

Take a look at https://github.com/auth0/express-openid-connect/issues/145#issuecomment-707024770 and https://github.com/auth0/express-openid-connect/issues/267#issuecomment-902715653 for an explanation of the error and some tips on debugging.

If you can provide a link, repo or HAR file (make sure you redact any secrets like passwords/session cookies) - I'd be happy to investigate for you.

**Comment by javiern8410** [comment]
Hi @adamjmcgrath, I can't send link or repo because it is a private repo. Reading the comments you shared with me I was able to fix it.
