### ISSUE TITLE
Using auth.handleCallback() appears to cause infinite redirect

### ISSUE THREAD

**Issue by ecs-hk** [auth0/express-openid-connect#58]
### Description

One of my applications that depends on express-openid-connect needs access to JWT in the routes. Prior to v.0.6.0, JWT was available in `req.openid.tokens.id_token`.

After upgrading to v.0.6.0 I have attempted to follow the instructions (in point numbers 4 and 5) at https://github.com/auth0/express-openid-connect/blob/master/EXAMPLES.md. But what I am seeing is when I add a `auth.handleCallback()` property, my RP becomes stuck in an infinite loop of requests between it and its OP.

In the RP log I see:
1. "GET /" - client requesting the RP resource 
2. Debugging information (console logging, as in my code in the Reproduction section below)
3. "POST /path/to/my/RP/redirectUriPath"

.. this pattern repeats over and over until I close the client web browser. If I remove the `auth.handleCallback()` property, then authentication completes normally. But then I don't have access to the JWT.

### Reproduction

Simplified Express (app.js) code, which still produces the issue:

```javascript
const sessionOpts = {
  secret: env.getSessionSecret(),
};

const authOpts = {
  issuerBaseURL: env.getOidcOpUri(),
  baseURL: env.getOidcRpUri(),
  clientID: env.getOidcClientId(),
  redirectUriPath: env.getOidcRedirectPath(),
  required: true,
  authorizationParams: {
    response_type: 'id_token',
    response_mode: 'form_post',
    scope: 'openid profile email',
  },
  appSessionSecret: false,
  handleCallback: async function(req, res, next) {
    req.session.oidcTokens = req.openidTokens;
    console.log('In the callback-handler');
    console.dir(req.openidTokens);
    next();
  },
};

// Set up session, body parser, authn
app.use(session(sessionOpts));
app.use(bodyParser.urlencoded({extended: false}));
app.use(bodyParser.json({strict: false}));
app.use(auth(authOpts));
```

### Environment

- express-openid-connect 0.6.0
- express 4.17.1
- express-session 1.17.0

**Comment by joshcanhelp** [comment]
@ecs-hk Sorry for the trouble here. What's happening is that your user session is not being set on the callback. `appSessionSecret` should be set to a secure, random string for the session (just consisting of the identity, no tokens) to be handled by the library. If you want to continue to use a session middleware for the user session and not the built-in cookie session, you'll just need to add a line to your `handleCallback` function:

```diff
const authOpts = {
  // ...
  appSessionSecret: false,
  handleCallback: async function(req, res, next) {
    req.session.oidcTokens = req.openidTokens;
+   req.session.userIdentity = req.openidTokens.claims();
    console.log('In the callback-handler');
    console.dir(req.openidTokens);
    next();
  },
};
```

The [Custom Session Handling example](https://github.com/auth0/express-openid-connect/blob/master/EXAMPLES.md) has a bit more information.

**Comment by ecs-hk** [comment]
@joshcanhelp No worries -- and thank you for the explanation / suggestion.

I rolled my main RP back to v.0.5.0 temporarily, and I'm in the process of building out a sandbox RP to test the fix you're describing in v.0.6.0. I should be able to confirm the fix within ~48 hours.

**Comment by ecs-hk** [comment]
@joshcanhelp Thanks again for taking a look at this.

After making the change you specified, and also adding a `getUser()` property to the auth options (as shown in the example code), the RP is behaving as expected. For posterity's sake, here is how I'm doing session handling with "express-session" + "connect-sqlite3":

```javascript
const sessionOpts = {
  store: new SQLiteStore({
    dir: files.createSessionDirectory(),
  }),
  secret: env.getSessionSecret(),
  resave: false,
  saveUninitialized: false,
  cookie: {
    secure: true,
    path: '/',
    httpOnly: true,
    sameSite: true,
    maxAge: 30 * 60 * 1000,
  },
};

const authOpts = {
  issuerBaseURL: env.getOidcOpUri(),
  baseURL: env.getOidcRpUri(),
  clientID: env.getOidcClientId(),
  redirectUriPath: env.getOidcRedirectPath(),
  required: env.isSsoEnabled(),
  routes: false,
  authorizationParams: {
    response_type: 'id_token',
    response_mode: 'form_post',
    scope: 'openid profile email',
  },
  appSessionSecret: false,
  handleCallback: async function(req, res, next) {
    req.session.openidTokens = req.openidTokens;
    req.session.userIdentity = req.openidTokens.claims();
    next();
  },
  getUser: async function(req) {
    return req.session.userIdentity;
  },
};
```

Within the routes, I am able to access, e.g.:
- `req.session.userIdentity.sub` (sub claim)
- `req.session.openidTokens.id_token` (JWT)
- `req.session.userIdentity` (the entire claims object)

The application is Dockerized and running as an OpenShift container/pod. That's why I am reading many of the values above in from the environment (as either environment variables or OpenShift secrets, depending on sensitivity).

This is my only application that needs access to JWT. For the rest of my apps that use your library, I will simply specify `appSessionSecret: env.getSessionSecret()` and not worry about all the session handling details.

**Comment by joshcanhelp** [comment]
@ecs-hk - Thank you for checking back in and sharing your config! That will undoubtedly help someone else out in the future 👍 

One thing that jumps out at me in your config ... the `authorizationParams` you have there is the default so you can leave that out.
