### ISSUE TITLE
Documentation gaps (readme.md), is this framework ONLY for auth0, or can work with any OIDC provider?

### ISSUE THREAD

**Issue by DmitriyAlergant-T1A** [auth0/express-openid-connect#613]
### Checklist

- [X] The issue can be reproduced in the [express-openid-connect sample app](https://github.com/auth0-samples/auth0-express-webapp-sample/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/express-openid-connect#readme), [Examples](https://github.com/auth0/express-openid-connect/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/express-openid-connect/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/express-openid-connect/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/express-openid-connect/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The documentation, FAQ, examples and readme.md do not give clarity on a very simple question: is this framework Auth0-specific, or can it be used directly with other OpenID providers (ex: Microsoft, Google)?

The framework name suggests it might be generic; Yet there is zero information on its configuration for other providers (without using Auth0 as a intermediary)... 

It's totally fine if it is actually Auth0-specific (this is your product after all), but then this deserves to be mentioned explicitly in the first line of README.MD.

Thanks!

### Reproduction

n/a

### express-openid-connect version

n/a

### Express version

n/a

### Node.js version

n/a

**Comment by frederikprijck** [comment]
This is not Auth0-Specific. But built by Auth0 so that is why the documentation is focussed on Auth0. But you are free to use it with other identity providers, and report issues along the way as the intention is to support them as long as they are OIDC compliant and the fixes are not vendor-specific.

We also refuse to add Auth0 specifics in this SDK to ensure it works with other IDPs that support OIDC, see: https://github.com/auth0/express-openid-connect/pull/615#issuecomment-2061949009

**Comment by DmitriyAlergant-T1A-Rogers** [comment]
Thanks for the comment; However my remark still stands - it would be great if README.md explicitly mentioned the status of this framework (in similar verbiage as you've put here). It was really confusing until I raised this issue.

**Comment by DmitriyAlergant-T1A-Rogers** [comment]
The readme now says...

**Getting Started**
...

**1. Configure Auth0**


It could have said "Getting started (if you will be using Auth0)" or something like that... You got it...
