### ISSUE TITLE
Remove hard-coded logout endpoint for broader provider compatibility

### ISSUE THREAD

**Issue by chesspro13** [auth0/express-openid-connect#621]
### Checklist

- [x] I have looked into the [Readme](https://github.com/auth0/express-openid-connect#readme), [Examples](https://github.com/auth0/express-openid-connect/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/express-openid-connect/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/express-openid-connect/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/express-openid-connect/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

When using express-openid-connect to authenticate users with Authentik, the logout URI endpoint is [hardcoded](https://github.com/auth0/express-openid-connect/blob/master/lib/client.js#L127) to be `/v2/logout` where Authentik's logout endpoint is `/end-session/`.
 

### Describe the ideal solution

Remove hard-coded logout endpoints and add it as a config parameter.

**Comment by frederikprijck** [comment]
Can you elaborate on what the problem is? We only hardcode that URL in the case when Auth0 is uses, which is done [here](https://github.com/auth0/express-openid-connect/blob/master/lib/client.js#L119-L120).

If it's not auth0, we expect the logout url to be defined in the `end_session_endpoint`, as per the OIDC specification.

**Comment by chesspro13** [comment]
I overlooked that. Thank you for your time.
