### ISSUE TITLE
AuthorizationParameters.nonce is discarded.

### ISSUE THREAD

**Issue by timvanoostrom** [auth0/express-openid-connect#622]
### Checklist

- [X] The issue can be reproduced in the [express-openid-connect sample app](https://github.com/auth0-samples/auth0-express-webapp-sample/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/express-openid-connect#readme), [Examples](https://github.com/auth0/express-openid-connect/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/express-openid-connect/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/express-openid-connect/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/express-openid-connect/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I'm not entirely sure if it's a bug in the interface or in the application code or part of functionality that I don't understand yet but here goes: 

The `nonce` option in `LoginOptions.authorizationParams` interface is not used in auth_verification cookie. See also: https://github.com/auth0/express-openid-connect/blob/master/lib/context.js#L245-L258 and https://github.com/auth0/express-openid-connect/blob/master/lib/context.js#L286

If not used in the cookie, where is it for?

### Reproduction

1. Use own login route
2. Provide authorizationParams.nonce value
3. Inspect auth_verification cookie

```
res.oidc.login({
  authorizationParams: { nonce: 'test-nonce' },
});
```

### express-openid-connect version

2.17.1

### Express version

4.18.3

### Node.js version

v21.7.3

**Comment by madaster97** [comment]
@timvanoostrom , the `nonce` parameter is part of the OIDC spec, and ties an id_token to a session in the application requesting it. All of that is handled by this library, and isn't something you need to set yourself. I think it's just exposed on the interface for completeness.

The `code_challenge` parameter is another example on the interface, and is part of the PKCE protocol. This library handles creating the right value and you don't need to provide it.

**Comment by timvanoostrom** [comment]
Alright, thanks for the explanation. I was fiddling with creating a local development oidc-server stub and a came up with a hacky way to mimic a real server. Having a static constant nonce would have come in handy.
