### ISSUE TITLE
Understanding - JWT

### ISSUE THREAD

**Issue by cmontois** [auth0/express-openid-connect#64]
Hey guys !

I am using your lib on my backend app. Everything works fine !
But I wonder how I should implement on my frontend app.

Does the makeTokenSet function generate an access_token which I can use by simply putting it in the header (Authorization: Bearer <access_token>) of my API calls ?

Currently it seems to be directly redirected to openId provider.

```
openId.auth({
        required:           req => !(req.originalUrl.includes('/checkAuthentication') || req.originalUrl.includes('/login')),
        issuerBaseURL:      config.issuerBaseURL,
        baseURL:            config.baseURL,
        clientID:           config.clientID,
        clientSecret:       config.clientSecret,
        appSessionSecret:   config.appSessionSecret,

        authorizationParams: {
            response_type: 'code',
            scope: 'openid profile email'
        },

        handleCallback: function (req, res, next) {
            // This will store the user identity claims in the session
            req.session.user         = req.openidTokens.claims();
            req.session.openidTokens = req.openidTokens;
            console.log(req.session.openidTokens);
            next();
        },
    })
```

**Comment by panva** [comment]
Hi @cmontois 

> But I wonder how I should implement on my frontend app.

Can you expand on this?

**Comment by adamjmcgrath** [comment]
Hi @cmontois

[Single-Page App Authentication Using Cookies](https://auth0.com/docs/login/spa/authenticate-with-cookies) is a good example of how to use this library to authenticate your SPA with cookies.

Going to close this, feel free to reopen if this doesn't answer your question
