### ISSUE TITLE
When will this lib be production ready?

### ISSUE THREAD

**Issue by danstod** [auth0/express-openid-connect#71]
Hello,

The README states:

"This library is currently in Beta status and has not had a complete security review. We do not recommend using this library in production yet"

Do you have an ETA for when this will be ready for production use please?

Thanks,
Dan

**Comment by joshcanhelp** [comment]
@danstod - Appreciate the interest here. It's tough to give an exact date as a beta period is meant to give us an opportunity to surface potential required features and breaking changes, as well as a security check, before we consider it production-ready. That said we've been working on it and using it internally for a while so we don't anticipate it will be long. 

I'm going to close this for now but feel free to ping back with any questions or to check status 👍

**Comment by danstod** [comment]
Thanks for the quick reply Josh. That's promising news and i will of course report any issues if they arise in our UAT phase 👍

**Comment by danstod** [comment]
Hi @joshcanhelp 

I realise this might not be the correct forum for this question and I can raise in the community page if not but I have had delayed responses there previously.

I am using the code from https://github.com/auth0-blog/spa-cookie-demo as per the suggestion in the article: https://auth0.com/docs/login/spa/authenticate-with-cookies

I am getting an error: "BadRequestError: id_token issued in the future" and was wondering if you have a better working example (preferably using React!) you could point me to?

I am having trouble using chrome when using express-openid-connect in my codebase (the auth0 universal login never appears) but it works for Safari.

A working example would be much appreciated as I've already looked on the community pages and read so much about this but it's still not quite working and I'm stuck.

Thanks, Dan
