### ISSUE TITLE
Document audience param

### ISSUE THREAD

**Issue by sir-dunxalot** [auth0/express-openid-connect#75]
### Describe the problem you'd like to have solved

Multiple places in the documentation refer to an `audience` param (examples [here](https://github.com/auth0/express-openid-connect/blob/master/EXAMPLES.md#2-require-authentication-for-specific-routes) and [here](https://github.com/auth0/express-openid-connect/blob/master/API.md#required-keys)). However, it's not clear to me what the value should be for `audience`.

### Describe the ideal solution

Add `audience` to the [API documentation](https://github.com/auth0/express-openid-connect/blob/master/API.md) and provide more specific examples than `"https://your-api-identifier"`.

## Alternatives and current work-arounds

None identified. I'm still Googling trying to figure out the correct value for `audience`.

### Additional context

I used the beta experimental Quickstart for Node to set up Auth0 in my app.

**Comment by sir-dunxalot** [comment]
I have figured out that `"https://your-api-identifier"` refers to an API (not application) like `https://{app-name}.auth0.com/api/v2/`. But it took me a while to figure out where that should come from (and which `clientSecret` to use).

**Comment by adamjmcgrath** [comment]
Glad you figured it out @sir-dunxalot 

Thanks for raising this, happy to accept a PR if you have any specific suggestions otherwise will close this.

Feel free to reopen if you want to continue the conversation
