### ISSUE TITLE
How to link directly to Sign-Up

### ISSUE THREAD

**Issue by JordashTalon** [auth0/express-openid-connect#83]
### Describe the problem you'd like to have solved

I'm trying to figure out how to create a route that will take people straight to Sign up (example: /register) 

### Describe the ideal solution

I tried this: 
```
app.get('/register', (req, res) => {
  res.openid.login({returnTo: '/', initialScreen: 'signUp'});
})  
```
But that just took them straight to login like usual.

How can I send them to login page with Sign-Up Pre-selected?

**Comment by adamjmcgrath** [comment]
Hi,

If you're using the new universal login page you can use the `screen_hint=signup` parameter:
https://auth0.com/docs/universal-login/new#signup

This can be passed through a custom parameter in `authorizationParams`
https://github.com/auth0/express-openid-connect/blob/master/API.md#authorization-params-key

Feel free to reopen if you need any more info

**Comment by JordashTalon** [comment]
Ok that worked great, but now /login always goes to sign-up how would I switch the setting based on route?

Example: 
/login works like normal
/register sends applies the new authorizationParams and takes them to the signup flow.

**Comment by adamjmcgrath** [comment]
This would probably work (looking at https://github.com/auth0/express-openid-connect/blob/master/lib/context.js#L62)

```js
app.get('/register', (req, res) => {
  res.openid.login({returnTo: '/', authorizationParams: { screen_hint: 'signup' } });
}) 
```

But beware dragons...

**Comment by adamjmcgrath** [comment]
Actually it's in the api so you should be good:
https://github.com/auth0/express-openid-connect/blob/master/API.md#response

**Comment by JordashTalon** [comment]
That worked perfect, thanks!

**Comment by JordashTalon** [comment]
Only other thing I need to figure out is how to prefill the email address, is that possible?

**Comment by adamjmcgrath** [comment]
For that you'd need to use the [classic universal login](https://auth0.com/docs/universal-login/classic) (the new one doesn't support pre-filling the email)

In the `authorizationParams` you'd pass: `login_hint=email@example.com` and `mode=signUp`

You'd also need to customize the classic login screen by adding some logic to handle the `mode` param:

```js
// retrieve screen mode from extra params if sent; default to 'login'
var mode = config.extraParams.mode || 'login';
...
var lock = new Auth0Lock(config.clientID, config.auth0Domain, {
  // add a selector for which screen to put up 
  initialScreen: mode,
  ...
});
```

**Comment by JordashTalon** [comment]
The login_hint is working but I can't figure out where to customize the lock.

Which file do I find this code in?

`var lock = new Auth0Lock(...`

**Comment by adamjmcgrath** [comment]
In your [tenant dashboard](https://manage.auth0.com/dashboard/): Universal Login > Login > Customize Login Page > Edit the default template

**Comment by JordashTalon** [comment]
Awesome, that's working perfect, thanks!

**Comment by danawoodman** [comment]
For those using `express-openid-connect`, this worked for me (placed after the `auth(config)` middleware based on @adamjmcgrath's solution above:

```ts
app.get("/signup", (req, res) => {
  res.oidc.login({
    returnTo: "/",
    authorizationParams: { screen_hint: "signup" },
  });
});
```

Key difference: using `oidc` instead of `openid`
