### ISSUE TITLE
Use access token without server-side session

### ISSUE THREAD

**Issue by YousefED** [auth0/express-openid-connect#89]
I'm trying to understand whether it's possible to combine this library with a JWT projected API. Use case: I want to use Auth0 roles, and on my Express app provide /login and /login functionality with express-openid-connect, but also protect the page /createbook with the permission create:book of an Auth0 API (books).

Setup:

```
 authorizationParams: {
 		response_type: "code",
 		audience: "books",
 		scope: "openid profile email access:gp create:book",
 	}
```

In the documentation, you mention we can use a server-side session storage to store the access_token. However, it should also be possible to store these client side right? I was thinking something like this:

```
handleCallback: async (req: any, res: any, next: any) => {
		req.identity.claims.access_token = req.openidTokens.access_token;
		next();
	},
```
We could then use `req.openid.user.access_token` combined with `express-jwt-authz` to validate the permissions on the `/createbook` route, correct?

Is this recommended / safe?  And / or would it be enough to store `req.openidTokens.scope` in the claims?

**Comment by adamjmcgrath** [comment]
Hi @YousefED - thanks fro your question -  we're currently looking to improve the documentation around this use case

What you're suggesting there looks fine, we'll update the docs shortly to improve messaging in this area.

Am closing for now, feel free to reopen if you have any more questions
