### ISSUE TITLE
Profile edit?

### ISSUE THREAD

**Issue by kenjura** [auth0/express-openid-connect#91]
I'm pretty clear on how to retrieve user profile info for display in my app, but how do I edit it?

Functionality within the library itself would be ideal, but is there a workaround where I can send users to an auth0 web page to edit their profiles?

**Comment by adamjmcgrath** [comment]
Hi @kenjura - editing user profiles would be outside of the scope of this library.

There's information on how to do this with Auth0 here https://auth0.com/docs/users/concepts/overview-user-profile#user-profile-data-modification
