### ISSUE TITLE
Make redirect optional for login, logout

### ISSUE THREAD

**Issue by bohdanz1997** [auth0/express-openid-connect#96]
### Describe the problem you'd like to have solved

I want to call the login endpoint via AJAX request and simply get the redirect URL in the response.
I've not found a way to change this behavior without modifying the library source code.

### Describe the ideal solution

So the possible solution is to have two methods: login, loginWithRedirect in the [RequestContext](https://github.com/auth0/express-openid-connect/blob/master/lib/context.js) class.

**Comment by adamjmcgrath** [comment]
Hi @bohdanz1997 - could you explain more about your use case? What would you do with the redirect URL when you got it back from an AJAX request?

**Comment by bohdanz1997** [comment]
> Hi @bohdanz1997 - could you explain more about your use case? What would you do with the redirect URL when you got it back from an AJAX request?

Just redirect via JavaScript
`window.location.href = url`

**Comment by adamjmcgrath** [comment]
So is there anything stopping you from doing: `window.location.href = '/login';`?

**Comment by bohdanz1997** [comment]
I plan to do redirect to auth0 login page, not to `/login` route

**Comment by adamjmcgrath** [comment]
The `/login` route will redirect you to the auth0 login page https://github.com/auth0/express-openid-connect/blob/master/lib/context.js#L103 - so `window.location.href = '/login';` will have exactly the same effect as `window.location.href = authorizeUrl;` - with the added bonus that you don't need to make an additional AJAX request to get the `authorizeUrl`

**Comment by bohdanz1997** [comment]
I'm doing an ajax request to the /login with axios. Browser is not able to proceed redirect response properly from ajax request. That's why I want to get redirect url in from the /login response and do perform the redirect manually

**Comment by bohdanz1997** [comment]
@adamjmcgrath is it clear, or I need to provide more details?

**Comment by adamjmcgrath** [comment]
Hi, sorry - we don't offer an API where you can get the authorize url - I recommend you have another look at https://github.com/auth0/express-openid-connect/issues/96#issuecomment-626548563 

If you really want to use the authorize url directly - it should be fairly trivial to create: https://github.com/auth0/node-auth0/issues/173#issuecomment-381767911

**Comment by bohdanz1997** [comment]
> Hi, sorry - we don't offer an API where you can get the authorize url - I recommend you have another look at [#96 (comment)](https://github.com/auth0/express-openid-connect/issues/96#issuecomment-626548563)
> 
> If you really want to use the authorize url directly - it should be fairly trivial to create: [auth0/node-auth0#173 (comment)](https://github.com/auth0/node-auth0/issues/173#issuecomment-381767911)

Thx
